declare @kontragent nvarchar(200)
declare @dogovor binary(16)
DECLARE @KONTRAGENT_GUID BINARY(16)
DECLARE @GETDAATE DATE
SET @GETDAATE = CAST(GETDATE() AS DATE)
SET @KONTRAGENT_GUID=0xA2337085C2A4312A11EB2239DB6D2527
--set @kontragent = 'GR - Агро ТОО'
--set @dogovor=0xA2337085C2A4312A11EB2239DB6D2527

SELECT GID.[NOMER_DOGOVORA]
,DENSE_RANK()OVER( ORDER BY GID.[DOGOVOR_GUID]) ID_GUID
,DENSE_RANK() OVER(PARTITION BY GID.[DOGOVOR_GUID] ORDER BY GID.[DOGOVOR_GUID],[DATA_PO_GRAFIKU]) ID_GRAFIK
      ,GID.[DOGOVOR_GUID]
      ,CAST([DATA_PO_GRAFIKU] AS DATE) AS [DATA_PO_GRAFIKU]
      ,GID.[SUMMA_OPLATY] AS SUMMA_GRAFIK
	  ,COALESCE(LEAD([DATA_PO_GRAFIKU]) OVER(PARTITION BY GID.[DOGOVOR_GUID] ORDER BY GID.[DOGOVOR_GUID],[DATA_PO_GRAFIKU]), GETDATE()) AS NEXT_GRAFIK,
	  PMT_ALL.DATA_OPLAYU
	  ,PMT.SUMMA_OPLAT
	  --,CASE WHEN GID.[SUMMA_OPLATY] <=PMT_ALL.DATA_OPLAYU THEN DATEDIFF(DAY,[DATA_PO_GRAFIKU],PMT_ALL.DATA_OPLAYU) ELSE DATEDIFF(DAY,[DATA_PO_GRAFIKU],GETDATE()) END 
	,NULL AS PROSROCHKA
FROM [L1].[dbo].[GRAFIK_ISPOLNENIYA_DOGOVORA] GID
LEFT JOIN L1.dbo.DOGOVORY_KONTRAGENTOV AS DK
	ON GID.DOGOVOR_GUID=DK.GUID
LEFT JOIN L1.dbo.KONTRAGENTY AS K
	ON DK.KONTRAGENT_GUID=K.GUID
CROSS APPLY(
	SELECT CAST([DATA_OPLATY_VOZVRATA] AS DATE) AS DATA_OPLAYU
	FROM L1.DBO.RASCHETY_S_KLIENTAMI_PO_DOKUMENTAM RSK
	LEFT JOIN L1.dbo.KONTRAGENTY AS K
		ON RSK.KONTRAGENT_GUID=K.GUID
	LEFT JOIN (SELECT DOGOVOR_GUID,
				MIN(DATA_PO_GRAFIKU) AS FIRST_GRAFIK_DATE
				FROM L1.DBO.GRAFIK_ISPOLNENIYA_DOGOVORA
				GROUP BY DOGOVOR_GUID
				) FG ON FG.DOGOVOR_GUID = GID.DOGOVOR_GUID
  WHERE TIP_DOKUMENTA IN (
  'Корректировка реализации',
'Расчет курсовых разниц',
'Приходный кассовый ордер',
'Списание задолженности',
'Ввод начальных остатков',
'Поступление безналичных денежных средств',
'Операция по платежной карте',
'Взаимозачет задолженности',
'Списание безналичных денежных средств'
  )
  --AND K.NAIMENOVANIE=@kontragent
  --AND KONTRAGENT_GUID=@KONTRAGENT_GUID
  AND RSK.DOGOVOR_GUID=GID.DOGOVOR_GUID
  AND (RSK.DATA_OPLATY_VOZVRATA >= GID.DATA_PO_GRAFIKU OR FG.FIRST_GRAFIK_DATE = GID.DATA_PO_GRAFIKU AND RSK.DATA_OPLATY_VOZVRATA < GID.DATA_PO_GRAFIKU)
  ) PMT_ALL
	CROSS APPLY(SELECT 
SUM(SUMMA) AS SUMMA_OPLAT
      --,SUM([SUMMA])*(-1) AS [SUMMA]
	  
  FROM [L1].[dbo].[RASCHETY_S_KLIENTAMI_PO_DOKUMENTAM] RSK
  LEFT JOIN L1.dbo.KONTRAGENTY AS K
	ON RSK.KONTRAGENT_GUID=K.GUID
	LEFT JOIN (SELECT DOGOVOR_GUID,
	MIN(DATA_PO_GRAFIKU) AS FIRST_GRAFIK_DATE
	FROM L1.DBO.GRAFIK_ISPOLNENIYA_DOGOVORA
	GROUP BY DOGOVOR_GUID) FG ON FG.DOGOVOR_GUID = GID.DOGOVOR_GUID
  WHERE TIP_DOKUMENTA IN (
  'Корректировка реализации',
'Расчет курсовых разниц',
'Приходный кассовый ордер',
'Списание задолженности',
'Ввод начальных остатков',
'Поступление безналичных денежных средств',
'Операция по платежной карте',
'Взаимозачет задолженности',
'Списание безналичных денежных средств'
  )
  --AND K.NAIMENOVANIE=@kontragent
  --AND KONTRAGENT_GUID=@KONTRAGENT_GUID
  AND RSK.DOGOVOR_GUID=GID.DOGOVOR_GUID
  AND (RSK.DATA_OPLATY_VOZVRATA >= GID.DATA_PO_GRAFIKU OR FG.FIRST_GRAFIK_DATE = GID.DATA_PO_GRAFIKU AND RSK.DATA_OPLATY_VOZVRATA < GID.DATA_PO_GRAFIKU)
  ) PMT


WHERE 1=1
--AND K.NAIMENOVANIE=@kontragent
AND DK.KONTRAGENT_GUID=@KONTRAGENT_GUID
AND GID.TIP_DOGOVORA='С покупателем / заказчиком'
AND GID.STATUS='Действует'
--AND DOGOVOR_GUID=@dogovor