
with KATEGORI as (
SELECT 
KN.NAIMENOVANIE
,KN.GUID
,ISNULL(KN.PARENT_1,KN.PARENT_0 ) AS PARENT
FROM L1.DBO.KATEGORII_NOMENKLATURY KN

)

,ALL_TABLE AS (

SELECT DISTINCT
	ATO.NAIMENOVANIE
	,KN.NAIMENOVANIE AS KATEGORIA
	,KN.PARENT
	,CCO.[NAIMENOVANIE] AS OBLAST
	,CCR.[NAIMENOVANIE] AS RAION
	,[flName]
	,[flNameCode]
	,S03.[productCode]
	,S03.[applicantIn]
	,S03.applicantName
	,SUM(SD.flAreaUsing)  OVER (PARTITION BY ATO.NAIMENOVANIE,[flName],CCO.[NAIMENOVANIE],CCR.[NAIMENOVANIE],S03.[applicantIn]) AS Area
	,CAST(ROUND(
				(SUM(SD.[quantityFact])OVER(PARTITION BY ATO.NAIMENOVANIE,[flName],CCO.[NAIMENOVANIE],CCR.[NAIMENOVANIE])/SUM(SD.[quantityFact])OVER(PARTITION BY ATO.NAIMENOVANIE,CCO.[NAIMENOVANIE],CCR.[NAIMENOVANIE]))*100
			,2)
		AS NUMERIC(5,2)
		)
	AS PROCENT

FROM [AA_DWH_X].[dbo].[subsidiesDetails] SD
LEFT JOIN [AA_DWH_X].[dbo].[subsidies_03] S03
	ON [applicantCatoCode]!=0 AND SD.appCodE=S03.appCode
LEFT JOIN L1.DBO.ASSORTIMENT_TOVARA ATO
	ON S03.productCode=ATO.CODE
LEFT JOIN KATEGORI KN
	ON ATO.KATEGORIYA_GUID=KN.GUID
LEFT JOIN [L1_X].[dbo].[CADASTR_CATO] CCO
	ON CCO.[CADASTR_Id]=(LEFT(cadNum,2)+'-000')
LEFT JOIN [L1_X].[dbo].[CADASTR_CATO] CCR
	ON CCR.[CADASTR_Id]=LEFT(cadNum,6)
  where 1=1
  AND PARENT='Пестициды'
  --AND isAA=1
  --AND ATO.NAIMENOVANIE='СТРАТОС УЛЬТРА, 10% к.э.'
  --AND [applicantCatoCode]!=0
  --AND S03.[applicantIn]='590927301722'
  --AND SD.appCode='01-2020-02-002'
    AND CCR.[NAIMENOVANIE]='Денисовский'
  --order by ATO.NAIMENOVANIE,CCR.[NAIMENOVANIE]


  )

  SELECT 
  AK.NAIMENOVANIE
  ,AK.applicantIn
  ,AK.applicantName
  ,AK.RAION
  ,AK.flName
  ,AK.flNameCode
  ,AK.KATEGORIA
  ,AK.OBLAST
  ,AK.PARENT
  ,AK.productCode
  ,CAST(AK.Area AS numeric(16,2)) AS Area
  ,CASE WHEN  ROW_NUMBER() OVER(PARTITION BY AK.NAIMENOVANIE,AK.RAION,AK.OBLAST,AK.flNAME ORDER BY AK.NAIMENOVANIE,AK.RAION,AK.OBLAST,AK.flNAME) = 1 
			THEN AK.PROCENT
		ELSE NULL
	END
AS PROCENT
  FROM ALL_TABLE AS AK

  ORDER BY AK.applicantIn,AK.RAION