declare @kontragent nvarchar(200)
declare @dogovor binary(16)
--set @kontragent = 'GR - Агро ТОО'
set @dogovor=0x80B900155D01C90111E74C1EBCB507AA
;
WITH DOGOVOR AS (
SELECT 
DK.[GUID]
,O.NAIMENOVANIE AS ORGANIZATSIYA
,K.NAIMENOVANIE AS [KONTRAGENT]
      ,[OSNOVNOY_DOGOVOR]
      ,[NOMER_DOP_SOGLASHENIYA]
      ,[AVTOSOGLASOVANIE]
      ,[VALYUTA_VZAIMORASCHETOV]
      ,[STATUS_PODPISANIYA]
      ,[TIP_DOGOVORA]
      ,[STATUS]
      ,DK.[NAIMENOVANIE]
      ,[DOGOVOR_VNUTRI_GRUPPY]
      ,[DATA_NACHALA_DEYSTVIYA]
      ,[DATA_OKONCHANIYA_DEYSTVIYA]
      ,CAST([DATA] AS DATE) AS [DATA]
      ,[NOMER]
      ,[SOGLASOVAN]
      ,[ORGANIZATSIYA_GUID]
      ,[KONTRAGENT_GUID]
      ,[MENEDZHER_GUID]
      ,[BIZNES_REGION_GUID]
      ,[STRUKTURA_PREDPRIYATIYA_GUID]
      ,[SEZON_GUID]
      ,[SKLAD_GUID]
      ,[MARZHINALNOST]
      ,[SUMMA]
      ,[PROGRAMMA_DOGOVORA]
      ,[STAVKA_NDS]
      ,[STAVKA_NSP]
      ,[VIDSTAVKI_NDS]
      ,[BEZNALICHNYY_RASCHET]
      ,[USLOVIYA_OPLATY]
      ,DK.[SOURCE_BASE]
      ,[AGENT_PARTNER_GUID]
      ,[PROTSENT_AGENTSKIKH]
      ,[SUMMA_AGENTSKIKH]
      ,[ZAKAZ_KLIENTA_GUID]
      ,[SPOSOB_DOSTAVKI]
      ,[ADRES_DOSTAVKI]
      ,[SOSTOYANIE]
      ,[STANDARTNYE_USLOVIYA_ZAKLYUCHENIYA]
      ,[SUMMA_KZ_TG]
  FROM [L1].[dbo].[DOGOVORY_KONTRAGENTOV] AS DK
	LEFT JOIN L1.dbo.KONTRAGENTY AS K
		ON DK.KONTRAGENT_GUID=K.GUID
	LEFT JOIN L1.dbo.ORGANIZATSII AS O
		ON DK.ORGANIZATSIYA_GUID=O.GUID
  WHERE 1=1
  AND TIP_DOGOVORA='С покупателем / заказчиком'
  AND PROGRAMMA_DOGOVORA not in ('Фьючерсный(Трейдинг)')
  AND STATUS='Действует'
  --AND ORGANIZATSIYA_GUID=0x80DE000C29E67B2E11E636A5C3C5D8AE
 --AND K.NAIMENOVANIE=@kontragent 
 --AND DK.GUID=@dogovor

  --ORDER BY K.NAIMENOVANIE
  --,DK.GUID
  )

, OPLATA AS (
  SELECT 
CAST([DATA_OPLATY_VOZVRATA] AS DATE) AS [DATA_OPLATY_VOZVRATA]
      ,[NOMER_DOGOVORA]
      ,SUM([SUMMA])*(-1) AS [SUMMA]
      ,[ORGANIZATSYA_GUID]
      ,[KONTRAGENT_GUID]
      ,[DOGOVOR_GUID]
      ,[KASPI]
  FROM [L1].[dbo].[RASCHETY_S_KLIENTAMI_PO_DOKUMENTAM] RSK
  LEFT JOIN L1.dbo.KONTRAGENTY AS K
	ON RSK.KONTRAGENT_GUID=K.GUID
  WHERE TIP_DOKUMENTA IN (
  'Корректировка реализации',
'Расчет курсовых разниц',
'Приходный кассовый ордер',
'Списание задолженности',
'Ввод начальных остатков',
'Поступление безналичных денежных средств',
'Операция по платежной карте',
'Взаимозачет задолженности',
'Списание безналичных денежных средств'
  )
  --AND K.NAIMENOVANIE=@kontragent
  --AND DOGOVOR_GUID=0xAF7AD4F5EF10792511EBA422716549E3

GROUP BY CAST([DATA_OPLATY_VOZVRATA] AS DATE)
      ,[NOMER_DOGOVORA]
      ,[ORGANIZATSYA_GUID]
      ,[KONTRAGENT_GUID]
      ,[DOGOVOR_GUID]
      ,[KASPI]
  --order by [DOGOVOR_GUID]
  )

  ,GRAFIK AS (
  /****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT [NOMER_DOGOVORA]
      ,GID.[TIP_DOGOVORA]
      ,GID.[STATUS]
      ,[DOGOVOR_GUID]
      ,CAST([DATA_PO_GRAFIKU] AS DATE) AS [DATA_PO_GRAFIKU]
      ,[PROTSENT_OPLATY]
      ,[SUMMA_OPLATY]
      ,[PERIOD]
      ,GID.[SOURCE_BASE]
	  ,CAST(DATEDIFF_BIG(ms, '1970-01-01', CAST(DATA_PO_GRAFIKU AS DATE)) AS BIGINT) AS UnixTimestamp
	  ,'GRAFIK' + CAST(ROW_NUMBER() OVER(PARTITION BY [NOMER_DOGOVORA] ORDER BY [DATA_PO_GRAFIKU]) AS NVARCHAR(2)) [ROW_NUMBER]
  FROM [L1].[dbo].[GRAFIK_ISPOLNENIYA_DOGOVORA] GID
	LEFT JOIN L1.dbo.DOGOVORY_KONTRAGENTOV AS DK
		ON GID.DOGOVOR_GUID=DK.GUID
	LEFT JOIN L1.dbo.KONTRAGENTY AS K
		ON DK.KONTRAGENT_GUID=K.GUID
WHERE 1=1
--AND K.NAIMENOVANIE=@kontragent
AND GID.TIP_DOGOVORA='С покупателем / заказчиком'
--AND DOGOVOR_GUID=@dogovor

--order by [DOGOVOR_GUID]
)
,DOLG AS (
SELECT 
	G.DOGOVOR_GUID
	,SUM(G.SUMMA_OPLATY) AS SUMMA_PO_GRAFIGU
	,SUM(O.SUMMA) AS SUMMA_PO_OPLATE
	,SUM(G.SUMMA_OPLATY) + ISNULL(SUM(O.SUMMA),0) AS DOLG
FROM (SELECT
		GRAFIK.DOGOVOR_GUID
		,SUM(GRAFIK.SUMMA_OPLATY) AS SUMMA_OPLATY
	  FROM GRAFIK
	  GROUP BY GRAFIK.DOGOVOR_GUID
	  ) AS G
LEFT JOIN (SELECT
			OPLATA.DOGOVOR_GUID
			,SUM(OPLATA.SUMMA) AS SUMMA
			FROM OPLATA
			GROUP BY OPLATA.DOGOVOR_GUID
			) AS O
	ON G.DOGOVOR_GUID=O.DOGOVOR_GUID

WHERE 1=1
--AND DOLG !=0
--AND TIP_DOGOVORA='С покупателем / заказчиком'
--AND G.DOGOVOR_GUID=@dogovor

GROUP BY 
G.DOGOVOR_GUID
)


,SPRAVICHNIK AS (
--SELECT 
--GUID AS DOGOVOR_GUID
--,DATA AS DATE
--,'DOGOVOR' AS TIP
--FROM DOGOVOR
--LEFT JOIN DOLG
--	ON DOLG.DOGOVOR_GUID=DOGOVOR.GUID
--WHERE DOLG !=0

--UNION 

SELECT 
OPLATA.DOGOVOR_GUID AS DOGOVOR_GUID
,DATA_OPLATY_VOZVRATA AS DATE
--,'OPLATA' AS TIP
FROM OPLATA
LEFT JOIN DOLG
	ON DOLG.DOGOVOR_GUID=OPLATA.DOGOVOR_GUID
WHERE DOLG > 0

UNION

SELECT 
GRAFIK.DOGOVOR_GUID AS DOGOVOR_GUID
,DATA_PO_GRAFIKU AS DATE
--,ROW_NUMBER AS TIP
FROM GRAFIK
LEFT JOIN DOLG
	ON DOLG.DOGOVOR_GUID=GRAFIK.DOGOVOR_GUID
WHERE DOLG > 0
)

,ALLDATE AS (
SELECT 
S.DOGOVOR_GUID
--,TIP
,D.NOMER
,S.DATE
,ISNULL(D.SUMMA,0) AS SUMMA_PO_DOGOVORU
,ISNULL(G.SUMMA_OPLATY,0) AS SUMMA_PA_GRAFIGU
,ISNULL(O.SUMMA,0) AS SUMMA_PO_OPLATE


FROM SPRAVICHNIK AS S
LEFT JOIN DOGOVOR AS D
	ON S.DOGOVOR_GUID=D.GUID
	AND S.DATE=D.DATA
LEFT JOIN GRAFIK AS G
	ON S.DOGOVOR_GUID=G.DOGOVOR_GUID
	AND S.DATE=G.DATA_PO_GRAFIKU
LEFT JOIN OPLATA AS O
	ON S.DOGOVOR_GUID=O.DOGOVOR_GUID
	AND S.DATE=O.DATA_OPLATY_VOZVRATA

--ORDER BY S.DATE
)

,SALSONGI AS (
SELECT 
DOGOVOR_GUID
--,TIP
,NOMER
,DATE
,SUMMA_PO_DOGOVORU
,SUMMA_PA_GRAFIGU
,SUMMA_PO_OPLATE
--,SUM(SUMMA_PO_OPLATE) OVER(ORDER BY DOGOVOR_GUID,DATE  ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS OPLATY_SUM
,SUM(SUMMA_PO_OPLATE) OVER(PARTITION BY DOGOVOR_GUID ORDER BY DOGOVOR_GUID,DATE  ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) - SUMMA_PA_GRAFIGU AS OPLATY_SUM
,SUM(SUMMA_PO_OPLATE) OVER(PARTITION BY DOGOVOR_GUID ORDER BY DOGOVOR_GUID,DATE  ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) + SUMMA_PA_GRAFIGU AS OPLATY_SUM2
,SUMMA_PO_OPLATE+SUMMA_PA_GRAFIGU as summa
FROM ALLDATE

--ORDER BY DOGOVOR_GUID,DATE
)
,ZADOLZNOST AS (
SELECT * FROM (
SELECT 
	SALSONGI.DOGOVOR_GUID
	--,SALSONGI.DOGOVOR.NOMER
	--,TIP
	,SUMMA_PA_GRAFIGU
	,SALSONGI.SUMMA_PO_OPLATE
	,OPLATY_SUM
	,OPLATY_SUM2
	--,SUM(OPLATY_SUM)OVER(PARTITION BY SALSONGI.DOGOVOR_GUID ORDER BY SALSONGI.DOGOVOR_GUID,DATE  ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
	,SUM(SALSONGI.summa)OVER(PARTITION BY SALSONGI.DOGOVOR_GUID ORDER BY SALSONGI.DOGOVOR_GUID,DATE  ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS SUMMA
	,DATE
FROM SALSONGI
LEFT JOIN DOLG
	ON SALSONGI.DOGOVOR_GUID=DOLG.DOGOVOR_GUID
WHERE 1=1
	--AND TIP LIKE ('GRAFIK_')
	--AND SALSONGI.DOGOVOR_GUID=0xAF9AD4F5EF10792511EDFB859ED5E77E
	--AND DATE<GETDATE()
--ORDER BY DOGOVOR_GUID,DATE
) A

WHERE 1=1
--AND DATE>CAST(GETDATE() AS DATE)
--AND A.TIP LIKE ('GRAFIK_')
--AND DOGOVOR_GUID IN (0xAF7AD4F5EF10792511EBA422716549E3,0xAF99D4F5EF10792511EDCE13FCE1E68B,
--0xAF9AD4F5EF10792511EDF9490334D5F4)
)
,ZADOLZNOST_NA_SEGODNYA AS (
SELECT
*
FROM ZADOLZNOST
WHERE DATE<GETDATE()
)
--SELECT 
--KONTRAGENT
--,GUID
--,NOMER
--,DOLG
--,ZADOLZNOST.SUMMA AS 'Общая сумма задолженности по просроченным'
----,MAX(ZADOLZNOST.SUMMA ) OVER(PARTITION BY GUID
--,TIP
--FROM DOGOVOR 
--LEFT JOIN ZADOLZNOST
--	ON GUID=DOGOVOR_GUID
--LEFT JOIN DOLG
--	ON GUID=DOLG.DOGOVOR_GUID

--ORDER BY KONTRAGENT
--,NOMER
SELECT
DISTINCT
KONTRAGENT
--,DOGOVOR.GUID
--,NOMER as NOMER_DOGOVORA
,SUM(DOGOVOR.SUMMA) OVER(PARTITION BY KONTRAGENT) AS SUMMA_DOOVORA
,SUM(SUMMA_ZADOLZHNOSTY) OVER(PARTITION BY KONTRAGENT) AS SUMMA_ZADOLZHNOSTY 
,SUM(ISNULL(PROSROSHKA.SUMMA,0)) OVER(PARTITION BY KONTRAGENT)  AS SUMMA_PROROCHKI
,COUNT(SUMMA_ZADOLZHNOSTY) OVER (PARTITION BY KONTRAGENT) AS OBSHOE_KOLICHESTVO
,COUNT(ZADOLZNOST_NA_SEGODNYA_SUMMA) OVER (PARTITION BY KONTRAGENT) KOLICHESTVO_PROSROSHKI
FROM DOGOVOR
INNER JOIN (SELECT ZADOLZNOST.SUMMA AS SUMMA_ZADOLZHNOSTY , ZADOLZNOST.DOGOVOR_GUID
				FROM ZADOLZNOST
				INNER JOIN (SELECT MAX(ZADOLZNOST.DATE) AS TIP	, DOGOVOR_GUID
								FROM ZADOLZNOST
								--WHERE TIP LIKE 'GRAFIK_'
								GROUP BY DOGOVOR_GUID
							) A	ON A.DOGOVOR_GUID=ZADOLZNOST.DOGOVOR_GUID
								AND A.TIP=ZADOLZNOST.DATE
			) AS ZADOLZNOST ON ZADOLZNOST.DOGOVOR_GUID=DOGOVOR.GUID

LEFT JOIN (SELECT ZADOLZNOST_NA_SEGODNYA.DOGOVOR_GUID , ZADOLZNOST_NA_SEGODNYA.SUMMA , CASE WHEN ZADOLZNOST_NA_SEGODNYA.SUMMA<=0 THEN NULL ELSE ZADOLZNOST_NA_SEGODNYA.SUMMA END ZADOLZNOST_NA_SEGODNYA_SUMMA
			FROM ZADOLZNOST_NA_SEGODNYA 
			JOIN (SELECT MAX(DATE) AS DATE , DOGOVOR_GUID
					FROM ZADOLZNOST_NA_SEGODNYA
					GROUP BY DOGOVOR_GUID
					) AS Z2 ON Z2.DOGOVOR_GUID=ZADOLZNOST_NA_SEGODNYA.DOGOVOR_GUID
							AND Z2.DATE=ZADOLZNOST_NA_SEGODNYA.DATE
			) AS PROSROSHKA ON PROSROSHKA.DOGOVOR_GUID=DOGOVOR.GUID

--ORDER BY KONTRAGENT,NOMER