
DECLARE @NAME_NOMENKLATUR BINARY(16)=0x801E00155D01C90111E6E868DD13CE97
DECLARE @OSY_weeek int /*** Осы аптаны шыгарып +4 апта косу ушин, болашақта керек болады ***/
SET @OSY_weeek  = datepart(week,GETDATE())+4;

DECLARE @ALL_DATA_TABLE 
TABLE (
		ID INT IDENTITY(1,1) PRIMARY KEY  
		,NOMENKLATURA_GUID BINARY(16) NULL
		--,SKLAD_OTGRUZKI NVARCHAR(150) NULL
		,WEEK_ID INT NULL
		,week INT  NULL
		--,[SKLAD_OTGRUZKI_GUID] BINARY(16) NULL
		,OSTALOS_OTGRUZIT NUMERIC(15,2) NULL
		,NEED NUMERIC(15,2)NULL
		)
DECLARE @STOKS
TABLE (
		ID INT 
		,NOMENKLATURA_GUID BINARY(16) NULL
		--,[SKLAD_OTGRUZKI_GUID] BINARY(16) NULL
		,OSTALOS_STOK NUMERIC(15,2) NULL
		,OSTALOS_OTGRUZIT NUMERIC(15,2) NULL
		,WEEK_ID INT NULL
		,week INT  NULL
		,NEED NUMERIC(15,2) NULL
		)

SELECT 
	   a.NOMENKLATURA_GUID AS NOMENKLATURA_GUID
	  --,sk.GUID AS sklad_guid
	  ,CAST(sum(a.KOLICHESTVO) AS NUMERIC(15,2)) AS OSTALOS_STOK
	  --,dateadd(WEEK,(a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI/7)+datepart(week,getdate()),'25/12/2022')  AS date
	  --,CAST((a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI/7)+datepart(week,getdate()) AS INT) AS week
	  ,CAST(datepart(week,GETDATE()) AS INT ) AS week
INTO #STOKKOI
FROM [L1].[dbo].[TOVARY_NA_SKLADAKH_OSTATKI_PO_SROKAM_GODNOSTI] a
	left join [L1].[dbo].[NOMENKLATURA] s 
	on s.GUID=a.NOMENKLATURA_GUID
	left join L1.dbo.SKLADY sk
	on a.SKLAD_GUID=sk.GUID

where 1=1
	and a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI!=0
	and a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI>90
	and s.KATEGORII_NOMENKLATURY_GROUP in  ('СЗР ','Семена ','Удобрения')
--AND NOMENKLATURA_GUID=@NAME_NOMENKLATUR
group by a.NOMENKLATURA_GUID
		--,sk.GUID
		--,dateadd(WEEK,(a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI/7)+datepart(week,getdate()),'25/12/2022')
		--,(a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI/7)+datepart(week,getdate())

SELECT 
		[DOGOVOR_GUID]
		,VISP.[KONTRAGENT_GUID]
		,[NOMENKLATURA_GUID]
		,VISP.[ORGANIZATSIYA_GUID]
		--,VISP.SKLAD_GUID
		,SUM([KOLICHESTVO]) AS [KOLICHESTVO]

INTO #VYRUCHKS 

	FROM [L1].[dbo].[VYRUCHKA_I_SEBESTOIMOST_PRODAZH] VISP
--WHERE NOMENKLATURA_GUID=@NAME_NOMENKLATUR

GROUP BY [DOGOVOR_GUID]
		,VISP.[KONTRAGENT_GUID]
		,[NOMENKLATURA_GUID]
		,VISP.[ORGANIZATSIYA_GUID]
		--,VISP.SKLAD_GUID
/*** Заключено ***/
SELECT [DOGOVOR_GUID]
      ,[NOMENKLATURA_GUID]
      ,SUM([KOLICHESTVO]) AS [KOLICHESTVO]
      ,MIN([DATA_OTGRUZKI])[DATA_OTGRUZKI]
     -- ,[SKLAD_OTGRUZKI_GUID]
      --,[SKLAD_OTGRUZKI]
INTO #SPEKA 
  FROM [L1].[dbo].[SPETSIFIKATSIYA_PO_DOGOVORU]
--WHERE NOMENKLATURA_GUID=@NAME_NOMENKLATUR

  GROUP BY [DOGOVOR_GUID]
      ,[NOMENKLATURA_GUID]
      --,[SKLAD_OTGRUZKI_GUID]
      --,[SKLAD_OTGRUZKI]


INSERT INTO @ALL_DATA_TABLE(NOMENKLATURA_GUID,week,OSTALOS_OTGRUZIT)--,SKLAD_OTGRUZKI_GUID
SELECT 
	SPEKA.NOMENKLATURA_GUID
	--,SPEKA.SKLAD_OTGRUZKI
	--,datepart(week,SPEKA.DATA_OTGRUZKI) AS week
	,CAST(datepart(week,GETDATE()) AS INT ) AS week /*** осы апта +4 аптаға дейінгілерді қосып осы аптанын санын қоямыз ***/
	--,DATEADD(WEEK,datepart(week,SPEKA.DATA_OTGRUZKI),'25/12/2022') AS POS_DATE_WEEK
	--,V.KOLICHESTVO OTGRUZKA
	--,SPEKA.KOLICHESTVO SPEKA
	--,[SKLAD_OTGRUZKI_GUID]
	,CAST(sum(CASE WHEN V.KOLICHESTVO IS NULL THEN SPEKA.KOLICHESTVO ELSE SPEKA.KOLICHESTVO-V.KOLICHESTVO END) AS NUMERIC(15,2)) AS OSTALOS_OTGRUZIT /*** біз жіберу керек қалған көлем ***/



FROM L1.dbo.DOGOVORY_KONTRAGENTOV AS DK
INNER JOIN #SPEKA SPEKA
	ON DK.GUID=SPEKA .DOGOVOR_GUID
LEFT JOIN #VYRUCHKS AS V
	ON SPEKA.DOGOVOR_GUID=V.DOGOVOR_GUID
	AND SPEKA.NOMENKLATURA_GUID=V.NOMENKLATURA_GUID
	--AND SPEKA.SKLAD_OTGRUZKI_GUID=V.SKLAD_GUID
INNER JOIN  L1.dbo.SEZONY AS S
	ON S.GUID=DK.SEZON_GUID
INNER JOIN L1.DBO.ORGANIZATSII AS O
	ON DK.ORGANIZATSIYA_GUID=O.GUID

WHERE 1=1
	-- AND SPD.DOGOVOR_GUID=0x8113000C29EF79CA11E9073C777BFB09 
	AND S.NAIMENOVANIE = 'Сезон 2023'
	AND DK.STATUS='Действует'
	AND DK.TIP_DOGOVORA='С покупателем / заказчиком'
	AND O.NAIMENOVANIE=N'ТОО «Alem Agro Holding (АлемАгро Холдинг)»'
--	AND SPEKA.NOMENKLATURA_GUID IN (0x801E00155D01C90111E6E868DD13CE97,
--0x80D3000C2910767B11E5D46451E5A871)
	AND datepart(week,SPEKA.DATA_OTGRUZKI) <=@OSY_weeek /*** осы апта +4 аптаға дейінгілерді шығарамыз ***/
GROUP BY SPEKA.NOMENKLATURA_GUID
		--,SPEKA.SKLAD_OTGRUZKI
		--,[SKLAD_OTGRUZKI_GUID]
		--,DATEADD(WEEK,datepart(week,SPEKA.DATA_OTGRUZKI),'25/12/2022')

--ORDER BY SPEKA.NOMENKLATURA_GUID,[SKLAD_OTGRUZKI_GUID]
--union 
INSERT INTO @ALL_DATA_TABLE(NOMENKLATURA_GUID,week,OSTALOS_OTGRUZIT)--SKLAD_OTGRUZKI,,SKLAD_OTGRUZKI_GUID
SELECT 
	SPEKA.NOMENKLATURA_GUID
	--,SPEKA.SKLAD_OTGRUZKI
	,CAST(datepart(week,SPEKA.DATA_OTGRUZKI)-4 AS INT) AS  week /*** -4 апта ***/
	--,datepart(week,GETDATE()) AS week
	--,DATEADD(WEEK,datepart(week,SPEKA.DATA_OTGRUZKI),'25/12/2022') AS POS_DATE_WEEK
	--,V.KOLICHESTVO OTGRUZKA
	--,SPEKA.KOLICHESTVO SPEKA
	--,[SKLAD_OTGRUZKI_GUID]
	,CAST(sum(CASE WHEN V.KOLICHESTVO IS NULL THEN SPEKA.KOLICHESTVO ELSE SPEKA.KOLICHESTVO-V.KOLICHESTVO END) AS NUMERIC(15,2)) AS OSTALOS_OTGRUZIT



FROM L1.dbo.DOGOVORY_KONTRAGENTOV AS DK
INNER JOIN #SPEKA  SPEKA
	ON DK.GUID=SPEKA.DOGOVOR_GUID
LEFT JOIN #VYRUCHKS AS V
	ON SPEKA.DOGOVOR_GUID=V.DOGOVOR_GUID
	AND SPEKA.NOMENKLATURA_GUID=V.NOMENKLATURA_GUID
	--AND SPEKA.SKLAD_OTGRUZKI_GUID=V.SKLAD_GUID
INNER JOIN  L1.dbo.SEZONY AS S
	ON S.GUID=DK.SEZON_GUID
INNER JOIN L1.DBO.ORGANIZATSII AS O
	ON DK.ORGANIZATSIYA_GUID=O.GUID

WHERE 1=1
	-- AND SPD.DOGOVOR_GUID=0x8113000C29EF79CA11E9073C777BFB09 
	AND S.NAIMENOVANIE = 'Сезон 2023'
	AND DK.STATUS='Действует'
	AND DK.TIP_DOGOVORA='С покупателем / заказчиком'
	AND O.NAIMENOVANIE=N'ТОО «Alem Agro Holding (АлемАгро Холдинг)»'
--	AND SPEKA.NOMENKLATURA_GUID IN (0x801E00155D01C90111E6E868DD13CE97,
--0x80D3000C2910767B11E5D46451E5A871)
	AND datepart(week,SPEKA.DATA_OTGRUZKI) > @OSY_weeek /***  ***/
GROUP BY SPEKA.NOMENKLATURA_GUID
	--,SPEKA.SKLAD_OTGRUZKI
	--,[SKLAD_OTGRUZKI_GUID]
	--,DATEADD(WEEK,datepart(week,SPEKA.DATA_OTGRUZKI),'25/12/2022')
	,datepart(week,SPEKA.DATA_OTGRUZKI)
	
INSERT INTO @STOKS
SELECT DISTINCT
     DENSE_RANK() OVER(ORDER BY ADT.NOMENKLATURA_GUID) AS ID
	,ADT.NOMENKLATURA_GUID
	,ISNULL(ST.OSTALOS_STOK,0)OSTALOS_STOK
	--,ST.OSTALOS_STOK
	,ADT.OSTALOS_OTGRUZIT
	,ROW_NUMBER() OVER(PARTITION BY ADT.NOMENKLATURA_GUID ORDER BY ADT.week) AS WEEK_ID
	,ADT.week
	,NULL AS NEED
	--,CAST(datepart(week,GETDATE()) AS INT ) AS week
FROM @ALL_DATA_TABLE ADT
  LEFT JOIN #STOKKOI AS ST
	ON ADT.NOMENKLATURA_GUID=ST.NOMENKLATURA_GUID
	  AND ST.week=ADT.week

-- DECLARING VARIABLES

DECLARE @NOMENKLATURA_ID AS INT = 1
	
DECLARE @MAX_NOMENKLATURA_ID AS INT 
SELECT 
	@MAX_NOMENKLATURA_ID = MAX(S.ID)
FROM @STOKS S

DECLARE @CURRENT_STOCK AS NUMERIC(15,2) 
  
DECLARE @STOCK AS NUMERIC(15,2) 

DECLARE @NEED AS NUMERIC(15,2) 



-- LOOP

WHILE @NOMENKLATURA_ID <= @MAX_NOMENKLATURA_ID
  BEGIN 
    SELECT 
	  @CURRENT_STOCK = S.OSTALOS_STOK      
	FROM @STOKS S
	WHERE 1=1
	  AND S.ID = @NOMENKLATURA_ID
	  AND S.WEEK_ID = 1
    
	DECLARE @CURRENT_WEEK AS INT
    SELECT 
	  @CURRENT_WEEK = MIN(S.WEEK_ID)
    FROM @STOKS S
    WHERE 1=1
	
	DECLARE @MAX_WEEK AS INT
	SELECT 
	  @MAX_WEEK = MAX(S.WEEK_ID)
	FROM @STOKS S
	WHERE 1=1
	  AND S.ID = @NOMENKLATURA_ID
    
	DECLARE @OTGRUZKA AS NUMERIC(15,2) 
    
	--SET @CURRENT_STOCK = @STOCK

	WHILE @CURRENT_WEEK <= @MAX_WEEK
	  BEGIN 
	    SELECT 
	      @OTGRUZKA = S.OSTALOS_OTGRUZIT
 	    FROM @STOKS S
	     WHERE 1=1
	        AND S.ID = @NOMENKLATURA_ID
	        AND S.WEEK_ID = @CURRENT_WEEK
	    IF @CURRENT_STOCK > @OTGRUZKA
		  BEGIN 
		    SET @NEED = 0
		    SET @CURRENT_STOCK = @CURRENT_STOCK - @OTGRUZKA
		    UPDATE @STOKS 
		    SET 
		      NEED = @NEED 
		    WHERE 1=1
		      AND ID = @NOMENKLATURA_ID
			  AND WEEK_ID = @CURRENT_WEEK;

            UPDATE @STOKS 
		    SET 
		      OSTALOS_STOK = @CURRENT_STOCK 
		    WHERE 1=1
		      AND ID = @NOMENKLATURA_ID
			  AND WEEK_ID = @CURRENT_WEEK + 1;

		  END
	    ELSE 
		  BEGIN 
		    SET @NEED = @OTGRUZKA - @CURRENT_STOCK
			SET @CURRENT_STOCK = 0
			UPDATE @STOKS 
		    SET 
		      NEED = @NEED 
		    WHERE 1=1
		      AND ID = @NOMENKLATURA_ID
			  AND WEEK_ID = @CURRENT_WEEK 

		  END
	    SET @CURRENT_WEEK = @CURRENT_WEEK + 1
	  END


    SET @NOMENKLATURA_ID = @NOMENKLATURA_ID + 1
  END

SELECT *
FROM @STOKS
--WHERE NOMENKLATURA_GUID=0xA22A7085C2A4312A11EA4995ABE835A2
ORDER BY 
   NOMENKLATURA_GUID
  ,week
	
DROP TABLE #SPEKA
DROP TABLE #VYRUCHKS
DROP TABLE #STOKKOI
