
DECLARE @NAME_NOMENKLATUR BINARY(16)=0x80DE00155D01C90111E81D3D435F43B3
DECLARE @OSY_weeek int /*** Осы аптаны шыгарып +4 апта косу ушин, болашақта керек болады ***/
SET @OSY_weeek  = datepart(week,GETDATE())+4;

DECLARE @ALL_DATA_TABLE 
TABLE (
		ID INT IDENTITY(1,1) PRIMARY KEY  
		,NOMENKLATURA_GUID BINARY(16) NULL
		--,SKLAD_OTGRUZKI NVARCHAR(150) NULL
		,week INT  NULL
		--,[SKLAD_OTGRUZKI_GUID] BINARY(16) NULL
		,OSTALOS_OTGRUZIT NUMERIC(15,2) NULL
		,NEED NUMERIC(15,2)NULL
		)
DECLARE @STOKS
TABLE (
		ID INT IDENTITY(1,1) PRIMARY KEY  
		,NOMENKLATURA_GUID BINARY(16) NULL
		--,[SKLAD_OTGRUZKI_GUID] BINARY(16) NULL
		,OSTALOS_STOK NUMERIC(15,2) NULL
		,week INT  NULL
		)
INSERT INTO @STOKS
SELECT 
	   a.NOMENKLATURA_GUID AS NOMENKLATURA_GUID
	  --,sk.GUID AS sklad_guid
	  ,CAST(sum(a.KOLICHESTVO) AS NUMERIC(15,2)) AS OSTALOS_STOK
	  --,dateadd(WEEK,(a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI/7)+datepart(week,getdate()),'25/12/2022')  AS date
	  ,CAST((a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI/7)+datepart(week,getdate()) AS INT) AS week
FROM [L1].[dbo].[TOVARY_NA_SKLADAKH_OSTATKI_PO_SROKAM_GODNOSTI] a
	left join [L1].[dbo].[NOMENKLATURA] s 
	on s.GUID=a.NOMENKLATURA_GUID
	left join L1.dbo.SKLADY sk
	on a.SKLAD_GUID=sk.GUID

where 1=1
	and a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI!=0
	and a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI>90
	and s.KATEGORII_NOMENKLATURY_GROUP in  ('СЗР ','Семена ','Удобрения')
	--AND NOMENKLATURA_GUID=@NAME_NOMENKLATUR
group by a.NOMENKLATURA_GUID
		,sk.GUID
		--,dateadd(WEEK,(a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI/7)+datepart(week,getdate()),'25/12/2022')
		,(a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI/7)+datepart(week,getdate())

SELECT 
		[DOGOVOR_GUID]
		,VISP.[KONTRAGENT_GUID]
		,[NOMENKLATURA_GUID]
		,VISP.[ORGANIZATSIYA_GUID]
		--,VISP.SKLAD_GUID
		,SUM([KOLICHESTVO]) AS [KOLICHESTVO]

INTO #VYRUCHKS 

	FROM [L1].[dbo].[VYRUCHKA_I_SEBESTOIMOST_PRODAZH] VISP
--WHERE NOMENKLATURA_GUID=@NAME_NOMENKLATUR

GROUP BY [DOGOVOR_GUID]
		,VISP.[KONTRAGENT_GUID]
		,[NOMENKLATURA_GUID]
		,VISP.[ORGANIZATSIYA_GUID]
		--,VISP.SKLAD_GUID
/*** Заключено ***/
SELECT [DOGOVOR_GUID]
      ,[NOMENKLATURA_GUID]
      ,SUM([KOLICHESTVO]) AS [KOLICHESTVO]
      ,MIN([DATA_OTGRUZKI])[DATA_OTGRUZKI]
     -- ,[SKLAD_OTGRUZKI_GUID]
      --,[SKLAD_OTGRUZKI]
INTO #SPEKA 
  FROM [L1].[dbo].[SPETSIFIKATSIYA_PO_DOGOVORU]
  --WHERE NOMENKLATURA_GUID=@NAME_NOMENKLATUR

  GROUP BY [DOGOVOR_GUID]
      ,[NOMENKLATURA_GUID]
      --,[SKLAD_OTGRUZKI_GUID]
      --,[SKLAD_OTGRUZKI]


INSERT INTO @ALL_DATA_TABLE(NOMENKLATURA_GUID,week,OSTALOS_OTGRUZIT)--,SKLAD_OTGRUZKI_GUID
SELECT 
	SPEKA.NOMENKLATURA_GUID
	--,SPEKA.SKLAD_OTGRUZKI
	--,datepart(week,SPEKA.DATA_OTGRUZKI) AS week
	,CAST(datepart(week,GETDATE()) AS INT ) AS week /*** осы апта +4 аптаға дейінгілерді қосып осы аптанын санын қоямыз ***/
	--,DATEADD(WEEK,datepart(week,SPEKA.DATA_OTGRUZKI),'25/12/2022') AS POS_DATE_WEEK
	--,V.KOLICHESTVO OTGRUZKA
	--,SPEKA.KOLICHESTVO SPEKA
	--,[SKLAD_OTGRUZKI_GUID]
	,CAST(sum(CASE WHEN V.KOLICHESTVO IS NULL THEN SPEKA.KOLICHESTVO ELSE SPEKA.KOLICHESTVO-V.KOLICHESTVO END) AS NUMERIC(15,2)) AS OSTALOS_OTGRUZIT /*** біз жіберу керек қалған көлем ***/



FROM L1.dbo.DOGOVORY_KONTRAGENTOV AS DK
INNER JOIN #SPEKA SPEKA
	ON DK.GUID=SPEKA .DOGOVOR_GUID
LEFT JOIN #VYRUCHKS AS V
	ON SPEKA.DOGOVOR_GUID=V.DOGOVOR_GUID
	AND SPEKA.NOMENKLATURA_GUID=V.NOMENKLATURA_GUID
	--AND SPEKA.SKLAD_OTGRUZKI_GUID=V.SKLAD_GUID
INNER JOIN  L1.dbo.SEZONY AS S
	ON S.GUID=DK.SEZON_GUID
INNER JOIN L1.DBO.ORGANIZATSII AS O
	ON DK.ORGANIZATSIYA_GUID=O.GUID

WHERE 1=1
	-- AND SPD.DOGOVOR_GUID=0x8113000C29EF79CA11E9073C777BFB09 
	AND S.NAIMENOVANIE = 'Сезон 2023'
	AND DK.STATUS='Действует'
	AND DK.TIP_DOGOVORA='С покупателем / заказчиком'
	AND O.NAIMENOVANIE=N'ТОО «Alem Agro Holding (АлемАгро Холдинг)»'
--	AND SPEKA.NOMENKLATURA_GUID IN (0x801E00155D01C90111E6E868DD13CE97,
--0x80D3000C2910767B11E5D46451E5A871)
	AND datepart(week,SPEKA.DATA_OTGRUZKI) <=@OSY_weeek /*** осы апта +4 аптаға дейінгілерді шығарамыз ***/
GROUP BY SPEKA.NOMENKLATURA_GUID
		--,SPEKA.SKLAD_OTGRUZKI
		--,[SKLAD_OTGRUZKI_GUID]
		--,DATEADD(WEEK,datepart(week,SPEKA.DATA_OTGRUZKI),'25/12/2022')

--ORDER BY SPEKA.NOMENKLATURA_GUID,[SKLAD_OTGRUZKI_GUID]
--union 
INSERT INTO @ALL_DATA_TABLE(NOMENKLATURA_GUID,week,OSTALOS_OTGRUZIT)--SKLAD_OTGRUZKI,,SKLAD_OTGRUZKI_GUID
SELECT 
	SPEKA.NOMENKLATURA_GUID
	--,SPEKA.SKLAD_OTGRUZKI
	,CAST(datepart(week,SPEKA.DATA_OTGRUZKI)-4 AS INT) AS  week /*** -4 апта ***/
	--,datepart(week,GETDATE()) AS week
	--,DATEADD(WEEK,datepart(week,SPEKA.DATA_OTGRUZKI),'25/12/2022') AS POS_DATE_WEEK
	--,V.KOLICHESTVO OTGRUZKA
	--,SPEKA.KOLICHESTVO SPEKA
	--,[SKLAD_OTGRUZKI_GUID]
	,CAST(sum(CASE WHEN V.KOLICHESTVO IS NULL THEN SPEKA.KOLICHESTVO ELSE SPEKA.KOLICHESTVO-V.KOLICHESTVO END) AS NUMERIC(15,2)) AS OSTALOS_OTGRUZIT



FROM L1.dbo.DOGOVORY_KONTRAGENTOV AS DK
INNER JOIN #SPEKA  SPEKA
	ON DK.GUID=SPEKA.DOGOVOR_GUID
LEFT JOIN #VYRUCHKS AS V
	ON SPEKA.DOGOVOR_GUID=V.DOGOVOR_GUID
	AND SPEKA.NOMENKLATURA_GUID=V.NOMENKLATURA_GUID
	--AND SPEKA.SKLAD_OTGRUZKI_GUID=V.SKLAD_GUID
INNER JOIN  L1.dbo.SEZONY AS S
	ON S.GUID=DK.SEZON_GUID
INNER JOIN L1.DBO.ORGANIZATSII AS O
	ON DK.ORGANIZATSIYA_GUID=O.GUID

WHERE 1=1
	-- AND SPD.DOGOVOR_GUID=0x8113000C29EF79CA11E9073C777BFB09 
	AND S.NAIMENOVANIE = 'Сезон 2023'
	AND DK.STATUS='Действует'
	AND DK.TIP_DOGOVORA='С покупателем / заказчиком'
	AND O.NAIMENOVANIE=N'ТОО «Alem Agro Holding (АлемАгро Холдинг)»'
--	AND SPEKA.NOMENKLATURA_GUID IN (0x801E00155D01C90111E6E868DD13CE97,
--0x80D3000C2910767B11E5D46451E5A871)
	AND datepart(week,SPEKA.DATA_OTGRUZKI) > @OSY_weeek /***  ***/
GROUP BY SPEKA.NOMENKLATURA_GUID
	--,SPEKA.SKLAD_OTGRUZKI
	--,[SKLAD_OTGRUZKI_GUID]
	--,DATEADD(WEEK,datepart(week,SPEKA.DATA_OTGRUZKI),'25/12/2022')
	,datepart(week,SPEKA.DATA_OTGRUZKI)
	

DECLARE @I INT = 0;
DECLARE @LEN INT = (SELECT COUNT(*)FROM @ALL_DATA_TABLE)

WHILE @i < @len
BEGIN
DECLARE  @NOMENKLATURA BINARY(16) = (SELECT NOMENKLATURA_GUID FROM @ALL_DATA_TABLE WHERE ID = @I);
--DECLARE  @SKLAD_GUID BINARY(16) = (SELECT SKLAD_OTGRUZKI_GUID FROM @ALL_DATA_TABLE WHERE ID = @I);
DECLARE  @WEEK INT = (SELECT week FROM @ALL_DATA_TABLE WHERE ID = @I);
DECLARE  @KOLICHESTVO NUMERIC(15,2) = (SELECT OSTALOS_OTGRUZIT FROM @ALL_DATA_TABLE WHERE ID = @I);

DECLARE @SIKL TABLE (ID INT);
INSERT INTO @SIKL (ID)
SELECT ID FROM @STOKS 
WHERE NOMENKLATURA_GUID = @NOMENKLATURA 
						--AND SKLAD_OTGRUZKI_GUID=@SKLAD_GUID 
						AND  week >= @week ;

DECLARE @j INT;
DECLARE @r INT = @KOLICHESTVO


DECLARE @stoks_UPDATE TABLE (ID INT, OSTALOS_STOK NUMERIC(15,2));
INSERT INTO @stoks_UPDATE (ID, OSTALOS_STOK)
SELECT ID, OSTALOS_STOK FROM @STOKS; -- замените your_stoks_table на вашу таблицу запасов

DECLARE @s INT;



WHILE @r > 0 AND EXISTS (SELECT * FROM @SIKL)
BEGIN
    SELECT TOP 1 @j = ID  FROM @SIKL ;

    IF @r > (SELECT TOP 1 OSTALOS_STOK FROM @stoks_UPDATE WHERE ID = @j)
    BEGIN
        SET @r = @r - (SELECT TOP 1 OSTALOS_STOK FROM @stoks_UPDATE WHERE ID = @j);
        UPDATE @stoks_UPDATE SET OSTALOS_STOK = 0 WHERE ID = @j;
    END
    ELSE IF @r < (SELECT TOP 1 OSTALOS_STOK FROM @stoks_UPDATE WHERE ID = @j)
    BEGIN
        SET @s = (SELECT TOP 1 OSTALOS_STOK FROM @stoks_UPDATE WHERE ID = @j) - @r;
        SET @r = 0;
        UPDATE @stoks_UPDATE SET OSTALOS_STOK = @s WHERE ID = @j;
    END
    ELSE
    BEGIN
        SET @r = 0;
        UPDATE @stoks_UPDATE SET OSTALOS_STOK = 0 WHERE ID = @j;
    END

    DELETE FROM @SIKL WHERE ID  = @j;
END;

IF @r <= 0
BEGIN
    UPDATE @ALL_DATA_TABLE SET NEED=(0) WHERE NOMENKLATURA_GUID=@NOMENKLATURA AND week=@WEEK-- AND SKLAD_OTGRUZKI_GUID=@SKLAD_GUID;
END
ELSE
BEGIN
    UPDATE @ALL_DATA_TABLE SET NEED=(@r)WHERE NOMENKLATURA_GUID=@NOMENKLATURA AND week=@WEEK --AND SKLAD_OTGRUZKI_GUID=@SKLAD_GUID;
END;


SET @i = @i + 1;


END 

SELECT 
*
FROM  @ALL_DATA_TABLE ADT
--where ADT.NOMENKLATURA_GUID=0x80D9000C29E67B2E11E600940107E2DD
ORDER BY ADT.NOMENKLATURA_GUID,ADT.week

--SELECT 
--*
--FROM  @STOKS 


DROP TABLE #SPEKA
DROP TABLE #VYRUCHKS
--DROP TABLE #ALL_DATA