
WITH DOGOVORY AS (
--only dogovors without discount products. Check dates. There are dogovors with 2 or more data otgruzki, and so i take max of data otgruzki.
  SELECT 
     DK.[GUID]
	,MAX(SPD.DATA_OTGRUZKI) AS MAX_DATA_OTGRUZKI
	,GID.DATA_PO_GRAFIKU
	,GID.PROTSENT_OPLATY
  FROM [L1].[dbo].[DOGOVORY_KONTRAGENTOV]DK
    LEFT JOIN L1.DBO.SPETSIFIKATSIYA_PO_DOGOVORU SPD 
      ON SPD.DOGOVOR_GUID=DK.GUID
    LEFT JOIN L1.dbo.GRAFIK_ISPOLNENIYA_DOGOVORA GID
	  ON GID.DOGOVOR_GUID = DK.GUID
  WHERE 1=1
	AND DK.DATA BETWEEN '30.05.2022' AND '12.06.2022'
	AND DK.DOGOVOR_VNUTRI_GRUPPY=0
	AND dk.TIP_DOGOVORA='С покупателем / заказчиком'
	AND GID.DATA_PO_GRAFIKU <= '2022-12-31'

  GROUP BY
     DK.[GUID]
	,GID.DATA_PO_GRAFIKU
	,GID.PROTSENT_OPLATY
    
)
,OTGRUZKI_2022 AS (
--GO (god otgruzki) = 2022 and oplata do 2023. 
  SELECT
     DK.[GUID]
    ,DK.MAX_DATA_OTGRUZKI
    ,MAX(DK.DATA_PO_GRAFIKU) AS MAX_DATA_PO_GRAFIKU
    ,SUM(DK.PROTSENT_OPLATY) AS SUM_PROTSENT_OPLATY
  FROM DOGOVORY DK
  WHERE 1=1
    AND YEAR(DK.MAX_DATA_OTGRUZKI) = 2022 
  GROUP BY
     DK.[GUID]
	,DK.MAX_DATA_OTGRUZKI
  HAVING ( SUM(DK.PROTSENT_OPLATY) = 100)

)
,OTGRUZKI_2023 AS(
  
  SELECT 
     DK.[GUID]
    ,DK.MAX_DATA_OTGRUZKI
    ,MAX(DK.DATA_PO_GRAFIKU) MAX_DATA_PO_GRAFIKU
    ,SUM(DK.PROTSENT_OPLATY) AS SUM_PROTSENT_OPLATY
  FROM DOGOVORY DK
  WHERE 1=1
    AND YEAR(DK.MAX_DATA_OTGRUZKI) = 2023
	AND DK.DATA_PO_GRAFIKU < '2022-10-01'
  GROUP BY 
    DK.[GUID]
    ,DK.MAX_DATA_OTGRUZKI
  HAVING 
     SUM(DK.PROTSENT_OPLATY) >= 50
)
,FILTERED_DOGOVORS AS(
  SELECT 
     G23.[GUID]
  FROM OTGRUZKI_2023 G23
   UNION
  SELECT 
     G22.[GUID]
  FROM OTGRUZKI_2022 G22
)
,DOGOVORS_WITH_PROMOTIONAL_PRODUCTS AS( 
--Добавляем акционные продукты
  SELECT 
     DK.[GUID]
	,DK.NOMER
	,DK.DATA
	,N.NAIMENOVANIE AS NOMENKLATURA
	,DK.SUMMA AS SUMMA_DOGOVORA
	,SPD.SUMMA AS SPEKA_SUMMA
	,DK.KONTRAGENT_GUID
	,DK.MENEDZHER_GUID
	,CONVERT(INT,(TRIM ('%' FROM [USLOVIYA_OPLATY])),1) AS [USLOVIYA_OPLATY]
	,CONVERT(NUMERIC(10,2),(ROUND((SPD.SUMMA / DK.SUMMA)*100,2)),1) AS [%] 
	--,CASE 
	--   WHEN N.AKSSIONNI=1 
 --         AND CONVERT(NUMERIC(10,2),(ROUND((SPD.SUMMA / DK.SUMMA)*100,2)),1)>=10
 --          THEN 1
 --      ELSE 0 
 --    END AS IS_SKIDKA
  FROM [L1].[dbo].[DOGOVORY_KONTRAGENTOV]DK
    JOIN FILTERED_DOGOVORS FD
	  ON FD.GUID = DK.GUID
	LEFT JOIN L1.DBO.SPETSIFIKATSIYA_PO_DOGOVORU SPD 
      ON SPD.DOGOVOR_GUID=DK.GUID
    LEFT JOIN [L1].dbo.[NOMENKLATURA] n
	  ON SPD.NOMENKLATURA_GUID=N.GUID 
  WHERE 1=1
	AND DK.DATA BETWEEN '30.05.2022' AND '12.06.2022'
	AND N.AKSSIONNI=1 
	AND CONVERT(NUMERIC(10,2),(ROUND((SPD.SUMMA / DK.SUMMA)*100,2)),1)>=10
	AND DK.DOGOVOR_VNUTRI_GRUPPY=0
	AND dk.TIP_DOGOVORA='С покупателем / заказчиком'
)
--,PROMOTIONAL_DOGOVORS AS (
-- Только договоры с акционными продуктами
--  SELECT 
--     DK.[GUID]
--	,DK.NOMER
--	,DK.DATA
--	,DK.NOMENKLATURA
--	,DK.SUMMA_DOGOVORA
--	,DK.SPEKA_SUMMA
--	,DK.KONTRAGENT_GUID
--	,DK.MENEDZHER_GUID
--	,DK.USLOVIYA_OPLATY
--	,DK.[%]
--	,DK.IS_SKIDKA
--  FROM DOGOVORS_WITH_PROMOTIONAL_PRODUCTS  DK
--  WHERE IS_SKIDKA = 1
--)
,NEW_CLIENTS AS(
--Новые клиенты
  SELECT 
     KONTRAGENT_GUID
  FROM DOGOVORS_WITH_PROMOTIONAL_PRODUCTS PD

   EXCEPT

  SELECT 
     DK.KONTRAGENT_GUID
  FROM L1.dbo.DOGOVORY_KONTRAGENTOV DK
  WHERE 1=1
    AND DK.TIP_DOGOVORA = 'С покупателем / заказчиком'
    AND DK.DATA < '2022-05-30' 
)
, ALL_CONDITIONS AS (
--Все условия не включая условия оплаты
   SELECT 
     PD.[GUID]
	,PD.NOMER
	--,PD.DATA
	,PD.NOMENKLATURA
	,PD.SUMMA_DOGOVORA
	,PD.SPEKA_SUMMA
	,PD.KONTRAGENT_GUID
	--,NC.KONTRAGENT_GUID 
	,PD.MENEDZHER_GUID
	,PD.USLOVIYA_OPLATY 
	,PD.[%] 
	--,PD.DATA_OTGRUZKI
	--,PD.IS_SKIDKA
    ,CASE 
	   WHEN MIN(PD.DATA) OVER (PARTITION BY PD.KONTRAGENT_GUID,PD.MENEDZHER_GUID ) = PD.DATA 
         THEN 30 
       ELSE 0 
     END AS NOVOE_DOPSOGLASHENIYE_30
    ,case 
	   when NC.KONTRAGENT_GUID is not null 
         and MIN(PD.DATA) OVER (PARTITION BY PD.KONTRAGENT_GUID,PD.MENEDZHER_GUID) = PD.DATA 
           then 50 
       else 0 
     end as NEW_CLIENT_50
    --,MIN(PD.DATA) OVER (PARTITION BY PD.KONTRAGENT_GUID,PD.MENEDZHER_GUID) AS MIN_DATA
    ,CONVERT(INT,(PD.SPEKA_SUMMA/100000),1) AS [1_OCHKO]
  FROM DOGOVORS_WITH_PROMOTIONAL_PRODUCTS as PD
    LEFT JOIN NEW_CLIENTS NC
      ON PD.KONTRAGENT_GUID=NC.KONTRAGENT_GUID

)
SELECT 
   DISTINCT CONVERT(nvarchar(50), AC.GUID, 1) AS GUID
  --,AC.DATA
  ,K.NAIMENOVANIE KONTRAGENT
  , CONVERT(nvarchar(50), M.GUID, 1) AS MENEDZHER_GUID
  ,M.NAIMENOVANIE  as MENEDZHER
  ,ISNULL(RODITEL2,RODITEL) AS DIREKTSIYA
  ,SUM(AC.SPEKA_SUMMA) OVER (PARTITION BY AC.GUID,AC.KONTRAGENT_GUID,AC.MENEDZHER_GUID) AS SPEKA_SUMMA
  ,SUM(AC.[1_OCHKO]) OVER (PARTITION BY AC.GUID,AC.KONTRAGENT_GUID,AC.MENEDZHER_GUID) + AC.NOVOE_DOPSOGLASHENIYE_30 + AC.NEW_CLIENT_50 + ( (SUM(AC.[1_OCHKO]) OVER (PARTITION BY AC.GUID,AC.KONTRAGENT_GUID,AC.MENEDZHER_GUID) + AC.NOVOE_DOPSOGLASHENIYE_30 + AC.NEW_CLIENT_50) * AC.USLOVIYA_OPLATY / 100) AS TOTAL_POINTS
FROM ALL_CONDITIONS AC
  LEFT JOIN L1.DBO.MENEDZHERY M 
    ON AC.MENEDZHER_GUID=M.GUID
  LEFT JOIN L1.DBO.KONTRAGENTY K 
    ON AC.KONTRAGENT_GUID=K.GUID
  LEFT JOIN L1.DBO.DOGOVORY_KONTRAGENTOV DK
    ON AC.GUID=DK.GUID
  LEFT JOIN L1.DBO.STRUKTURA_PREDPRIYATIYA SP 
    ON DK.STRUKTURA_PREDPRIYATIYA_GUID=SP.GUID
WHERE 1=1
  AND ISNULL(RODITEL2,RODITEL) <> 'Головной офис'
