WITH NEW_KLIENT AS (
SELECT 
	distinct [KONTRAGENT_GUID]
FROM [L1].[dbo].[DOGOVORY_KONTRAGENTOV]
  WHERE 1=1
  AND SEZON_GUID=0xAF90D4F5EF10792511ECEC824678758E

  except

SELECT
      distinct [KONTRAGENT_GUID]
  FROM [L1].[dbo].[DOGOVORY_KONTRAGENTOV]
  WHERE 1=1

  AND SEZON_GUID!=0xAF90D4F5EF10792511ECEC824678758E
  )
,DOGOVOR AS ( 
 SELECT 
  DK.GUID
  ,K.KATO
  FROM L1.dbo.DOGOVORY_KONTRAGENTOV AS DK
  INNER JOIN NEW_KLIENT AS NK
  ON DK.KONTRAGENT_GUID=NK.KONTRAGENT_GUID
  INNER JOIN L1.dbo.KONTRAGENTY AS K
	ON DK.KONTRAGENT_GUID=K.GUID
)
SELECT 
*
FROM L2.dbo.DOGOVOROV_S_KLIENTAMI AS DSK
INNER JOIN DOGOVOR AS D
	ON DSK.DOGOVOR_GUID=D.GUID
WHERE DIREKSIA = 'Дирекция "ЗАПАД"'