/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
WITH MAX AS (
SELECT SOO.[PERIOD]
      ,SOO.[SYNONYM_REGISTRATOR]
      ,SOO.[REGISTRATOR_GUID]
      ,SOO.[OBEKTY_EKSPLUATATSII_GUID]
      ,SOO.[ORGANIZATSIYA_GUID]
      ,SOO.[SOSTOYANI_GUID]
  FROM [L1].[dbo].[SOSTOYANIYA_OS_ORGANIZATSIY] SOO
INNER JOIN (
SELECT MAX([PERIOD])[PERIOD]
      ,[OBEKTY_EKSPLUATATSII_GUID]
      ,[ORGANIZATSIYA_GUID]
  FROM [L1].[dbo].[SOSTOYANIYA_OS_ORGANIZATSIY]
  --where [OBEKTY_EKSPLUATATSII_GUID]=0xA22B7085C2A4312A11EA854818208469
  GROUP BY
      [OBEKTY_EKSPLUATATSII_GUID]
      ,[ORGANIZATSIYA_GUID]
) SOO2
ON SOO.[ORGANIZATSIYA_GUID]=SOO2.[ORGANIZATSIYA_GUID] AND SOO.[PERIOD]=SOO2.[PERIOD] AND SOO.[OBEKTY_EKSPLUATATSII_GUID]=SOO2.[OBEKTY_EKSPLUATATSII_GUID]
	  )

SELECT [guid]
      ,[NAIMENOVANIE]
      ,[RODITEL]
      ,[NAIMENOVANIE_POLNOE]
      ,[INVENTARNYY_NOMER]
      ,[GOS_NOMER]
      ,[ID_WIALON]
      ,[NAME_WIALON]
	  ,[SYNONYM_REGISTRATOR]
  FROM [L1].[dbo].[OBEKTY_EKSPLUATATSII] OE 
LEFT JOIN MAX SOO
	ON OE.guid=SOO.[OBEKTY_EKSPLUATATSII_GUID]
WHERE 1=1
AND RODITEL='Автопарк'
--AND NAIMENOVANIE LIKE '%652%'
--	OR NAIMENOVANIE LIKE '%870%'
and [SYNONYM_REGISTRATOR] is not null
ORDER BY [GOS_NOMER],ID_WIALON