/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT 
      --[AGENT_PARTNER_GUID]
	  --,DK.NOMER AS NOMER_DOGOVORA
	  CAST(DK.DATA AS DATE) AS DATA_DOGOVORA
	  ,K.NAIMENOVANIE AS PARTNER
	  ,S.NAIMENOVANIE AS SEZON
      ,[PROTSENT_AGENTSKIKH]
	  ,[SUMMA_AGENTSKIKH]
      --,SUM([SUMMA_AGENTSK\IKH]) AS [SUMMA_AGENTSKIKH]
FROM [L1].[dbo].[DOGOVORY_KONTRAGENTOV] AS DK
LEFT JOIN L1.DBO.KONTRAGENTY AS K
	ON DK.AGENT_PARTNER_GUID=K.GUID_PARTNER
LEFT JOIN L1.DBO.SEZONY AS S 
	ON DK.SEZON_GUID=S.GUID
WHERE 1=1
AND DK.DATA>='2018-01-01'
AND DK.SUMMA_AGENTSKIKH>0
--GROUP BY [AGENT_PARTNER_GUID]
--	  ,K.NAIMENOVANIE
--	  ,S.NAIMENOVANIE
--	  ,CAST(DK.DATA AS DATE) 
--	  ,DK.NOMER
--	  ,[PROTSENT_AGENTSKIKH]
ORDER BY 
[PROTSENT_AGENTSKIKH]
	  ,K.NAIMENOVANIE
	  ,S.NAIMENOVANIE

	  asc
	  