
	WITH SALDO_1 AS(/**все данные по салдо на начало периюда**/

	SELECT 
		  CAST([PERIOD] AS DATE) AS[PERIOD] 
		  ,[ORGANIZACIYA] AS ORGANIZACIYA_GUID
		  ,O.NAIMENOVANIE AS ORGANIZACIYA
		  ,ISNULL(BSO.[ssilka],BSO_2.[ssilka]) AS BANKOVSKIE_SCHETA_ORGANIZACII_GUID
		  ,ISNULL(BSO.naimenovanie,BSO_2.naimenovanie) AS BANKOVSKIE_SCHETA_ORGANIZACII
		  ,SUM(CASE WHEN RBX.SCHET_DT in ('1030','1050') THEN RBX.SUMMA ELSE 0 END) 	AS Дт
		,SUM(CASE WHEN RBX.SCHET_KT in('1030','1050') THEN RBX.SUMMA ELSE 0 END)	AS Кт
	  FROM [L1].[dbo].[REGISTR_BUHGALTERII_HOZRASCHETNYI] AS RBX
	  LEFT JOIN L1.DBO.ORGANIZATSII O
	 ON RBX.ORGANIZACIYA=O.GUID
	  LEFT JOIN L0.dbo.bankovskie_scheta_organizacii AS BSO
			ON BSO.ssilka=
					(CASE
		WHEN RBX.subconto_ct_1_type ='БанковскиеСчетаОрганизаций' THEN subconto_ct_1_guid
		WHEN RBX.subconto_ct_2_type ='БанковскиеСчетаОрганизаций' THEN subconto_ct_2_guid
		WHEN RBX.subconto_ct_3_type ='БанковскиеСчетаОрганизаций' THEN subconto_ct_3_guid
	  END)
	  LEFT JOIN L0.dbo.bankovskie_scheta_organizacii AS BSO_2
			ON BSO_2.ssilka=--RBX.subconto_dt_1_guid
					(CASE
		WHEN RBX.subconto_dt_1_type ='БанковскиеСчетаОрганизаций' THEN subconto_dt_1_guid
		WHEN RBX.subconto_dt_2_type ='БанковскиеСчетаОрганизаций' THEN subconto_dt_2_guid
		WHEN RBX.subconto_dt_3_type ='БанковскиеСчетаОрганизаций' THEN subconto_dt_3_guid
	  END)



	  WHERE 1=1
	  AND (RBX.SCHET_DT IN ('1030','1050') OR RBX.SCHET_KT IN ('1030','1050')) 
	  AND O.GUID IN(0x80DE000C29E67B2E11E636A5C3C5D8AE,
					0x80DE000C29E67B2E11E636C101BBCFE5,
					0x8D7000115B5E9E4F11DDE08A5E3D9BEF
					) 

	--AND BSO.naimenovanie='5534 в АО "KASPI BANK", ТОО «Alem Agro Holding (Алем Агро Холдинг)»'
	  GROUP BY CAST([PERIOD] AS DATE) 
		  ,[ORGANIZACIYA]
		  ,ISNULL(BSO.[ssilka],BSO_2.[ssilka])
		  ,ISNULL(BSO.naimenovanie,BSO_2.naimenovanie)
		  ,O.NAIMENOVANIE

	--ORDER BY O.NAIMENOVANIE,[PERIOD]

	)
	,BAOLDY AS(
	SELECT
	SALDO_1.ORGANIZACIYA_GUID
	,SALDO_1.PERIOD
	,ORGANIZACIYA
	,BANKOVSKIE_SCHETA_ORGANIZACII
	,SUM(Дт) OVER(PARTITION BY ORGANIZACIYA,bankovskie_scheta_organizacii
						ORDER BY [PERIOD]
						ROWS BETWEEN UNBOUNDED PRECEDING
							AND CURRENT ROW) 
	-SUM(Кт) OVER(
				PARTITION BY ORGANIZACIYA,bankovskie_scheta_organizacii
				ORDER BY [PERIOD]
				ROWS BETWEEN UNBOUNDED PRECEDING
							AND CURRENT ROW) AS SALDO

	FROM SALDO_1


	WHERE 1=1
	AND BANKOVSKIE_SCHETA_ORGANIZACII_GUID IN (0xA2337085C2A4312A11EB03D9ED8DF69D,/***6086 в АО "Евразийский Банк", Оператор финансовой поддержки сельского хозяйства***/
												0xA2337085C2A4312A11EB03DABE507B53,/***6090 в АО "Евразийский Банк", ТОО "Alem Agro Trade"***/
												0xA2337085C2A4312A11EB0E041BD700E2,/***6087 АО "Евразийский Банк", ТОО «Alem Agro Holding (АлемАгро Холдинг)» (KZT)***/
												0xAF8ED4F5EF10792511ECC630D8DB6985,/***БЦК 5290 Alem Agro Holding (АлемАгро Холдинг) (KZT)***/
												0xAF95D4F5EF10792511ED706CA73A7919,/***БЦК депозит 9998, ТОО «Alem Agro Holding (АлемАгро Холдинг)»***/
												0xAF95D4F5EF10792511ED7C7397CEE00D/***депозит 0182 в АО "Евразийский Банк", ТОО «Alem Agro Holding (АлемАгро Холдинг)»***/
												)

	--ORDER BY 
	--[PERIOD],
	----ORGANIZACIYA_GUID,
	--bankovskie_scheta_organizacii
	)

	,POSLE_2022 AS (
	SELECT
		MAX_DATE.BANKOVSKIE_SCHETA_ORGANIZACII
		,MAX_DATE.ORGANIZACIYA
		,MAX_DATE.ORGANIZACIYA_GUID
		,CONVERT(DATE,'2022-01-01') AS PERIOD
		--,MAX_DATE.PERIOD
		,BAOLDY.SALDO
	FROM (SELECT 
				BD.ORGANIZACIYA_GUID
				,BD.ORGANIZACIYA
				,BD.BANKOVSKIE_SCHETA_ORGANIZACII
				,MAX(BD.PERIOD) AS PERIOD
			FROM BAOLDY AS BD
			WHERE BD.PERIOD<'2022'
			GROUP BY 
				BD.ORGANIZACIYA_GUID
				,BD.ORGANIZACIYA
				,BD.BANKOVSKIE_SCHETA_ORGANIZACII
		
			) MAX_DATE
	LEFT JOIN BAOLDY
		ON  MAX_DATE.BANKOVSKIE_SCHETA_ORGANIZACII=BAOLDY.BANKOVSKIE_SCHETA_ORGANIZACII
		AND MAX_DATE.PERIOD=BAOLDY.PERIOD

		--ORDER BY MAX_DATE.ORGANIZACIYA_GUID


	UNION 


	SELECT 
	BAOLDY .BANKOVSKIE_SCHETA_ORGANIZACII
	,BAOLDY.ORGANIZACIYA
	,BAOLDY.ORGANIZACIYA_GUID
	,BAOLDY .PERIOD
	,BAOLDY .SALDO
	FROM BAOLDY 
	WHERE PERIOD >'2022-01-01'
	)


	,ORGENIZASYA_CALENDAR AS (
	SELECT 
	DISTINCT
	FC.[CalendarDate] AS PERIOD
	,POSLE_2022.ORGANIZACIYA_GUID
	,POSLE_2022.ORGANIZACIYA
	,BANKOVSKIE_SCHETA_ORGANIZACII
	FROM
	 L1_X.dbo.FIN_CALENDAR AS FC
	 ,POSLE_2022
	 --ORDER BY [CalendarDate]--ORGANIZACIYA.ORGANIZACIYA_GUID
	)


	SELECT 
	AILAR_ORGANIZASSYA.ORGANIZACIYA
	,CONVERT(NVARCHAR(50),AILAR_ORGANIZASSYA.ORGANIZACIYA_GUID,1) AS ORGANIZACIYA_GUID
	,AILAR_ORGANIZASSYA.BANKOVSKIE_SCHETA_ORGANIZACII
	,AILAR_ORGANIZASSYA.PERIOD
	,POSLE_2022.SALDO
	FROM ORGENIZASYA_CALENDAR AS AILAR_ORGANIZASSYA
	LEFT JOIN POSLE_2022
	ON POSLE_2022.BANKOVSKIE_SCHETA_ORGANIZACII=AILAR_ORGANIZASSYA.BANKOVSKIE_SCHETA_ORGANIZACII
	AND POSLE_2022.ORGANIZACIYA_GUID=AILAR_ORGANIZASSYA.ORGANIZACIYA_GUID
	AND POSLE_2022.PERIOD=AILAR_ORGANIZASSYA.PERIOD
 


	 ORDER BY 
	AILAR_ORGANIZASSYA.PERIOD
	, AILAR_ORGANIZASSYA.ORGANIZACIYA_GUID
	,AILAR_ORGANIZASSYA.BANKOVSKIE_SCHETA_ORGANIZACII
