WITH RAP_LEN AS ( 
				SELECT [OWNER_IIN_BIN]
					  ,SUM([AREA_HA]) AS [AREA_HA]
					  ,[YEAR]
					  ,[CULTURE]
					  ,REGION
				  FROM [CRM_DWH].[dbo].[CRM_SHYMBULAK_ALL_CROPS_LIST]
				  WHERE 1=1
								AND [CULTURE] LIKE '%РАПС%' OR [CULTURE] LIKE '%Лен%'

		GROUP BY [OWNER_IIN_BIN]
				,[YEAR]
				,[CULTURE]
				,REGION
)
,SHIM AS (
SELECT --[STATUS]
      [APPLICANT_NAME]
      ,[SUM_SUBSIDIES] AS [SUM_SUBSIDIES]
      ,CSP.[YEAR] AS  [YEAR]
      ,[PROVIDER] AS PROVIDER_NAME
	  ,[PESTICIDES_NAME] AS PRODUCT_NAME 
      ,[FACT_VOLUME] AS VOLUME
      ,[UNIT]
      ,CSP.[PROVIDER_IIN_BIN]
	  ,CASE WHEN CSP.[PROVIDER_IIN_BIN] = '150140002752' THEN 1 ELSE 0 END AS IS_ALEMAGRO
      ,CSP.[CORRECT_APPLICANT_IIN_BIN]
	  ,'PESTICIDES' AS [GROUP]
	  ,CSP.REGION
  FROM [CRM_DWH].[dbo].[CRM_SHYMBULAK_PESTICIDES] AS CSP
	RIGHT JOIN RAP_LEN AS RL
		ON CSP.CORRECT_APPLICANT_IIN_BIN=RL.[OWNER_IIN_BIN]
		AND CSP.YEAR=RL.YEAR

UNION ALL

SELECT [APPLICANT_NAME]
      ,[SUM_SUBSIDIES_FACT] AS [SUM_SUBSIDIES]
      , CSM.[YEAR] AS [YEAR]
	  ,PROVIDER_NAME AS PROVIDER_NAME
      ,[MINERALS_NAME] AS PRODUCT_NAME 
      ,[VOLUME] AS VOLUME
      ,[UNIT]
      ,CSM.[PROVIDER_IIN_BIN]
	  ,CASE WHEN CSM.[PROVIDER_IIN_BIN] = '150140002752' THEN 1 ELSE 0 END AS IS_ALEMAGRO
      ,CSM.[CORRECT_APPLICANT_IIN_BIN]
	  ,'MENIRALS' AS [GROUP]
	  ,CSM.REGION
  FROM [CRM_DWH].[dbo].[CRM_SHYMBULAK_MINERALS] AS CSM
	RIGHT JOIN RAP_LEN AS RL
		ON CSM.CORRECT_APPLICANT_IIN_BIN=RL.[OWNER_IIN_BIN]
		AND CSM.YEAR=RL.YEAR


UNION ALL

SELECT [APPLICANT_NAME]
      ,[SUM_SUBSIDIES]  AS [SUM_SUBSIDIES]
      ,CSS.[YEAR] AS [YEAR]
      ,[PROVIDER_NAME] AS PROVIDER_NAME
      ,[SEEDS_NAME] AS PRODUCT_NAME 
	  ,[VOLUME] VOLUME
      ,[UNIT]
	  ,CSS.PROVIDER_IIN_BIN
	  ,CASE WHEN CSS.[PROVIDER_IIN_BIN] = '150140002752' THEN 1 ELSE 0 END AS IS_ALEMAGRO
      ,CSS.[CORRECT_APPLICANT_IIN_BIN]
	  ,'SEED' AS [GROUP]
	  ,CSS.REGION
  FROM [CRM_DWH].[dbo].[CRM_SHYMBULAK_SEEDS] AS CSS
	RIGHT JOIN RAP_LEN AS RL
		ON CSS.CORRECT_APPLICANT_IIN_BIN=RL.[OWNER_IIN_BIN]
		AND CSS.YEAR=RL.YEAR
		AND CSS.CULTURE=RL.CULTURE

)


SELECT 
DISTINCT
*
FROM SHIM
--LEFT JOIN AA_DWH_X.DBO.subsidiesProductsNames AS SPN
--	ON SHIM.PRODUCT_NAME=SPN.name



-- -- ORDER BY RL.CORRECT_APPLICANT_IIN_BIN,CSP.YEAR