SELECT S.GUID name
    --,s.PROIZVODITELI man
	,SKLADY.NAIMENOVANIE Склад
    --,(a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI/7)+datepart(week,getdate()) week
	,datepart(week,GETDATE()) AS week
    ,(sum(a.KOLICHESTVO)) quan
    --,dateadd(WEEK,(a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI/7)+datepart(week,getdate()),'25/12/2022') date
FROM L1.[dbo].TOVARY_NA_SKLADAKH_OSTATKI_PO_SROKAM_GODNOSTI a
left join L1.[dbo].NOMENKLATURA s on s.GUID=a.NOMENKLATURA_GUID
LEFT JOIN L1.DBO.SKLADY 
	ON SKLADY.GUID=A.SKLAD_GUID
where a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI!=0 
  and a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI>90 
  --and S.KATEGORII_NOMENKLATURY_GROUP IN ('СЗР ' ,'Семена ' ,'Удобрения')
--  AND S.GUID IN (0x801E00155D01C90111E6E868DD13CE97,
--0x80D3000C2910767B11E5D46451E5A871)
group by S.GUID
--,s.PROIZVODITELI
,SKLADY.NAIMENOVANIE
--,(a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI/7)+datepart(week,getdate())
 -- ,dateadd(WEEK,(a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI/7)+datepart(week,getdate()),'25/12/2022')
order by SKLADY.NAIMENOVANIE