WITH AA_DOGOR AS (
					SELECT 
						  K.IIN_BIN 
						  ,K.NAIMENOVANIE AS KONTRAGENT_NAIMENOVANIE
						  ,RIGHT(S.NAIMENOVANIE,4) AS SEZON
	  
					  FROM [L1].[dbo].[DOGOVORY_KONTRAGENTOV] AS DK
					  LEFT JOIN [L1].[dbo].KONTRAGENTY AS K
						ON DK.KONTRAGENT_GUID=K.GUID
					  LEFT JOIN L1.DBO.SEZONY AS S
						ON DK.SEZON_GUID=S.GUID
					LEFT JOIN L1_X.DBO.cato 
						ON LEFT (K.KATO,2)+'0000000'=cato.cato_Id
					WHERE K.IIN_BIN IN 
						(SELECT
						[OWNER_IIN_BIN]
						 FROM (SELECT [OWNER_IIN_BIN]
										  ,SUM([AREA_HA]) AS [AREA_HA]
										  ,[YEAR]
										  ,[CULTURE]
										  ,REGION
									  FROM [CRM_DWH].[dbo].[CRM_SHYMBULAK_ALL_CROPS_LIST]
									  WHERE 1=1
													AND [CULTURE] LIKE '%–¿œ—%' OR [CULTURE] LIKE '%ÀÂÌ%'

							GROUP BY [OWNER_IIN_BIN]
									,[YEAR]
									,[CULTURE]
									,REGION

								)AS A 
					  )
					  GROUP BY 
						  K.IIN_BIN 
						  ,K.NAIMENOVANIE 
						  ,S.NAIMENOVANIE
						  ,cato .name
					--ORDER BY K.IIN_BIN 
					)




SELECT DISTINCT
	--[OWNER_IIN_BIN]
	--,SUM([AREA_HA]) OVER (PARTITION BY [OWNER_IIN_BIN],[YEAR],[CULTURE],REGION ) AS [AREA_HA]
	[YEAR]
	,[CULTURE]
	,REGION
	,CASE WHEN AD.IIN_BIN IS NULL THEN 'OTHER' ELSE 'ALEMAGRO' END AS [AA?]
	,COUNT([OWNER_IIN_BIN]) OVER (PARTITION BY [REGION],[CULTURE],[YEAR] ORDER BY REGION)AS KOLICHESTVO_KLIENTOV_OBL
	,COUNT([OWNER_IIN_BIN]) OVER (PARTITION BY [REGION],[CULTURE],[YEAR],CASE WHEN AD.IIN_BIN IS NULL THEN 'OTHER' ELSE 'ALEMAGRO' END ORDER BY REGION)AS KOLICHESTVO_KLIENTOV_AA
	,SUM([AREA_HA]) OVER (PARTITION BY [REGION],[CULTURE],[YEAR] ORDER BY REGION) AS AREA_SUM_OBL
	,SUM([AREA_HA]) OVER (PARTITION BY [REGION],[CULTURE],[YEAR],CASE WHEN AD.IIN_BIN IS NULL THEN 'OTHER' ELSE 'ALEMAGRO' END ORDER BY REGION) AS AREA_SUM_AA
FROM [CRM_DWH].[dbo].[CRM_SHYMBULAK_ALL_CROPS_LIST] AS CSA
LEFT JOIN AA_DOGOR AS AD
	ON CSA.OWNER_IIN_BIN=AD.IIN_BIN
	AND CSA.YEAR=AD.SEZON


WHERE 1=1
			AND [CULTURE] LIKE '%–¿œ—%' OR [CULTURE] LIKE '%ÀÂÌ%'

		--GROUP BY [OWNER_IIN_BIN]
		--		,[YEAR]
		--		,[CULTURE]
		--		,REGION

ORDER BY REGION,[YEAR],[CULTURE]