WITH OPLATA AS (
SELECT SUM(RSK.[SUMMA]) AS [SUMMA]
	  ,CAST(RSK.PERIOD AS DATE) AS DATA_PLATEZHA 
	  --,[SYNONYM_REGISTRATOR]
      ,DK.NAIMENOVANIE
      --,CONVERT(NVARCHAR(50),[DOGOVOR_GUID],1) AS[DOGOVOR_GUID]
	  ,[DOGOVOR_GUID]
  FROM [L1].[dbo].[RASCHETY_S_KLIENTAMI] RSK
  LEFT JOIN L1.DBO.DOGOVORY_KONTRAGENTOV DK 
	ON RSK.DOGOVOR_GUID=DK.GUID
  WHERE 1=1
  --AND DOGOVOR_GUID IN(0xAF83D4F5EF10792511EBE0AC0CC08716)
  AND [SYNONYM_REGISTRATOR] NOT IN ('Корректировка реализации','Реализация товаров и услуг','Реализация услуг и прочих активов','Заказ клиента','График исполнения договора')

GROUP BY DK.NAIMENOVANIE
      ,[DOGOVOR_GUID]
	  --,[SYNONYM_REGISTRATOR]
	  ,CAST(RSK.PERIOD AS DATE)
  --=ORDER BY [DOGOVOR_GUID] DESC
  )

,GRAFIK AS (
SELECT 
SUM(GID.SUMMA_OPLATY) AS SUMMA_OPLATY
,CAST(GID.DATA_PO_GRAFIKU AS DATE) AS DATA_PO_GRAFIKU
,GID.DOGOVOR_GUID
,1 AS FILTER
FROM L1.DBO.GRAFIK_ISPOLNENIYA_DOGOVORA AS GID
WHERE 1=1
AND GID.TIP_DOGOVORA='С покупателем / заказчиком'
--AND GID.DATA_PO_GRAFIKU BETWEEN DATEADD(DAY,1,EOMONTH(GETDATE() ,-1)) AND EOMONTH(GETDATE(),0)  
--AND GID.DATA_PO_GRAFIKU BETWEEN CAST(GETDATE()AS DATE) AND EOMONTH(GETDATE(),0)  

GROUP BY GID.DOGOVOR_GUID
		,CAST(GID.DATA_PO_GRAFIKU AS DATE)
)



SELECT 
FROM OPLATA
JOIN GRAFIK ON OPLATA.DOGOVOR_GUID=GRAFIK .DOGOVOR_GUID