/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
WITH SPEKA AS (
SELECT EOMONTH(DK.DATA) AS [PERIOD]
--,DOGOVOR_GUID
      --,S.NAIMENOVANIE AS SEZON
	  ,SUM(SPD.[SUMMA]) AS[SUMMA]
  FROM [L1].[dbo].[SPETSIFIKATSIYA_PO_DOGOVORU] AS SPD
INNER JOIN L1.dbo.DOGOVORY_KONTRAGENTOV AS DK
	ON DK.GUID=SPD.DOGOVOR_GUID
INNER JOIN L1.dbo.SEZONY AS S
	ON S.GUID=DK.SEZON_GUID
INNER JOIN L1.DBO.STRUKTURA_PREDPRIYATIYA AS SP
	ON DK.STRUKTURA_PREDPRIYATIYA_GUID=SP.GUID
WHERE S.NAIMENOVANIE >='Сезон 2022'
AND DK.TIP_DOGOVORA='С покупателем / заказчиком'
AND DK.ORGANIZATSIYA_GUID=0x80DE000C29E67B2E11E636A5C3C5D8AE
AND DK.STATUS = 'Действует'
AND SP.DIREKSYA IN ('Дирекция "ВОСТОК"',
'Дирекция "ЗАПАД"',
'Дирекция "СЕВЕР 1"',
'Дирекция "СЕВЕР 2"',
'Дирекция "ЦЕНТР"',
'Дирекция "ЮГ"')
  GROUP BY EOMONTH(DK.DATA) 
--,DOGOVOR_GUID
  --,S.NAIMENOVANIE 
--ORDER BY EOMONTH(DK.DATA)
  )

,OTGRUZKA AS (
SELECT EOMONTH([DATE]) AS[DATE]
      ,SUM(CASE WHEN [SUMMA_VYRUCHKI] > 0 THEN [SUMMA_VYRUCHKI] ELSE 0 END) AS [SUMMA_VYRUCHKI]
      ,SUM(CASE WHEN [SUMMA_VYRUCHKI] < 0 THEN [SUMMA_VYRUCHKI] ELSE 0 END) AS [SUMMA_VOZVRATA]
	  --,S.NAIMENOVANIE AS SEZON
  FROM [L1].[dbo].[VYRUCHKA_I_SEBESTOIMOST_PRODAZH] AS VISP 
INNER JOIN L1.dbo.DOGOVORY_KONTRAGENTOV AS DK
	ON DK.GUID=VISP.DOGOVOR_GUID
INNER JOIN L1.dbo.SEZONY AS S
	ON S.GUID=DK.SEZON_GUID
INNER JOIN L1.DBO.STRUKTURA_PREDPRIYATIYA AS SP
	ON DK.STRUKTURA_PREDPRIYATIYA_GUID=SP.GUID
	
WHERE S.NAIMENOVANIE >='Сезон 2022'
AND DK.TIP_DOGOVORA='С покупателем / заказчиком'
AND DK.ORGANIZATSIYA_GUID=0x80DE000C29E67B2E11E636A5C3C5D8AE
AND DK.STATUS = 'Действует'
--AND SP.DIREKSYA IN ('Дирекция "ВОСТОК"',
--'Дирекция "ЗАПАД"',
--'Дирекция "СЕВЕР 1"',
--'Дирекция "СЕВЕР 2"',
--'Дирекция "ЦЕНТР"',
--'Дирекция "ЮГ"')
  GROUP BY EOMONTH([DATE]) 
  --,S.NAIMENOVANIE
  )

,PERIODKOI AS (
SELECT S.PERIOD AS DATE 
--,S.SEZON
FROM SPEKA S
UNION 
SELECT O.DATE AS DATE 
--,SEZON
FROM OTGRUZKA O
)

SELECT 
DISTINCT
PERIODKOI.DATE
--,PERIODKOI.SEZON
,SPEKA.SUMMA AS SUMMA_ZAKLUCHENO
,OTGRUZKA.SUMMA_VOZVRATA
,OTGRUZKA.SUMMA_VYRUCHKI
FROM PERIODKOI
LEFT JOIN SPEKA
	ON PERIODKOI.DATE=SPEKA.PERIOD
LEFT JOIN OTGRUZKA 
	ON PERIODKOI.DATE=OTGRUZKA.DATE

	ORDER BY PERIODKOI.DATE