/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
WITH UNION_SPD_OTGRUZ AS 
(SELECT DISTINCT *
FROM
	(SELECT [DOGOVOR_GUID]
		  ,[NOMENKLATURA_GUID]
	  FROM [L1].[dbo].[SPETSIFIKATSIYA_PO_DOGOVORU]
	UNION ALL
	  SELECT  
		  [DOGOVOR_GUID]
		  ,[NOMENKLATURA_GUID]
	FROM [L1].[dbo].[SEBESTOIMOST_ZAKUP]
	)DIST_KOI
),



VOZVRAT AS(
  SELECT MAX(ST.DATE) AS [DATE]
      ,ST.[DOGOVOR_GUID] AS [DOGOVOR_GUID] 
      ,ST.[NOMENKLATURA_GUID] AS [NOMENKLATURA_GUID]
      ,SUM(ST.[KOLICHESTVO]) AS [KOLICHESTVO]
      ,SUM(ST.[SUMMA]) AS [SUMMA_KZT]
	  ,SUM(RSP.SUMMA) AS [SUMMA_V_VALUTE]
  FROM [L1].[dbo].[SEBESTOIMOST_TOVAROV] ST
  LEFT JOIN (
				SELECT DISTINCT [PERIOD]
					  ,[SYNONYM_REGISTRATOR]
					  ,[DOGOVOR_GUID]
					  ,[SUMMA]
					  ,[SUMMA_REGL]
				  FROM [L1].[dbo].[RASCHETY_S_POSTAVSHCHIKAMI]
				  WHERE 1=1 --DOGOVOR_GUID=0xA22B7085C2A4312A11EA5D477B275F5B
				  AND [SYNONYM_REGISTRATOR]='Возврат товаров поставщику'
				  --ORDER BY PERIOD
			  ) RSP
	ON ST.DOGOVOR_GUID=RSP.DOGOVOR_GUID
	AND ST.SYNONYM_REGISTRATOR=RSP.SYNONYM_REGISTRATOR
	AND ST.DATE=RSP.PERIOD
  GROUP BY 
		ST.[DOGOVOR_GUID]
      ,[NOMENKLATURA_GUID]
)



,OTGRUZKA AS(
SELECT MAX([PERIOD]) AS DATE 
      ,[NOMENKLATURA_GUID]
      ,[DOGOVOR_GUID]
      ,SUM([KOLICHESTVO]*[SEBESTOIMOST])SUMMA_KZT
	  ,SUM(SUMMA_ZAKUPA) AS SUMMA_ZAKUPA
	  ,SUM([KOLICHESTVO]) AS [KOLICHESTVO]
FROM [L1].[dbo].[SEBESTOIMOST_ZAKUP] 
GROUP BY [NOMENKLATURA_GUID]
		,[DOGOVOR_GUID]
--ORDER BY [DOGOVOR_GUID],[NOMENKLATURA_GUID]
  )

,SPEKA AS (
SELECT [DOGOVOR_GUID]
      ,[NOMENKLATURA_GUID]
	  ,[VIDY_KULTUR]
      ,SUM([KOLICHESTVO]) AS [KOLICHESTVO]
      ,SUM(SPD.[SUMMA]) AS [SUMMA]
      ,SUM([SUMMA_SO_SKIDKOY]) AS [SUMMA_SO_SKIDKOY]
      ,[SKLAD_OTGRUZKI_GUID]
      ,[SKLAD_OTGRUZKI]
      ,[PROSROCHENNYY_TOVAR]
      ,CAST(ROUND(SUM(SPD.[SUMMA_KZ_TG]),2)AS NUMERIC(15,2)) AS [SUMMA_KZ_TG]
  FROM [L1].[dbo].[SPETSIFIKATSIYA_PO_DOGOVORU] SPD
  LEFT JOIN [L1].[dbo].DOGOVORY_KONTRAGENTOV AS DK
	ON SPD.DOGOVOR_GUID=DK.GUID
	WHERE DK.TIP_DOGOVORA!='С покупателем / заказчиком'
GROUP BY 
	[DOGOVOR_GUID]
	,[PROSROCHENNYY_TOVAR]
    ,[NOMENKLATURA_GUID]
	,[VIDY_KULTUR]
    ,[SKLAD_OTGRUZKI_GUID]
    ,[SKLAD_OTGRUZKI]
)


,OPLATA AS (
SELECT 
      [DOGOVOR_GUID]
      ,SUM([SUMMA]) AS [SUMMA_V_VALUTE]
      ,SUM(SUMMA_REGL) AS [SUMMA_KZT]
FROM [L1].[dbo].[RASCHETY_S_POSTAVSHCHIKAMI]
WHERE [synonym_registrator] IN ('Взаимозачет задолженности','Поступление безналичных денежных средств','Приходный кассовый ордер'
,'Расходный кассовый ордер','Списание безналичных денежных средств','Списание задолженности')

GROUP BY [DOGOVOR_GUID]

)


SELECT DISTINCT USO.[DOGOVOR_GUID]
	,DK.NAIMENOVANIE AS DOGOVOR_NAIMENOVANIE
	,DK.VALYUTA_VZAIMORASCHETOV
	,DK.SUMMA AS SUMMA_DOGOVOR
	,OPL.[SUMMA_V_VALUTE] AS OPLATA_V_VALUTE
	,S.NAIMENOVANIE AS SEZON
	,M.NAIMENOVANIE AS MENEDZHER
	,K.NAIMENOVANIE AS POSTAVCHIK
	,K.FAKT_ADRES_KONTRAGENTA AS FAKT_ADRES_KONTRAGENTA
	,ORG.NAIMENOVANIE AS ORGANIZATSII
	,SP.NAIMENOVANIE AS STRUKTURA_PREDPRIYATIYA
	,ISNULL(SP.[RODITEL],SP.[NAIMENOVANIE]) AS OBLAST
	,ISNULL(SP.[RODITEL2] ,ISNULL(SP.[RODITEL],SP.[NAIMENOVANIE]))DIREKSIA
	,DK.PROGRAMMA_DOGOVORA AS PROGRAMMA_DOGOVORA
	,DK.USLOVIYA_OPLATY AS USLOVIYA_OPLATY
	,DK.SPOSOB_DOSTAVKI AS SPOSOB_DOSTAVKI
	,DK.SOSTOYANIE AS SOSTOYANIE
	,DK.STATUS AS STATUS
	,CASE 
		WHEN K.VKHODIT_V_GRUPPU_KOMPANIY_ALEM_AGRO=1 THEN 1 
		ELSE 0 
	END AS [DOGOVOR_VNUTRI_GRUPPY]
	,DK.DATA
	,N.NAIMENOVANIE AS NAIMENOVANIE_NOMENKLATURA
	,N.KATEGORII_NOMENKLATURY_GROUP AS KATEGORII_NOMENKLATURY_GROUP
    ,N.[NORMA_RASKHODOVANIYA] AS [NORMA_RASKHODOVANIYA_NOMENKLATURA]
	,USO.[NOMENKLATURA_GUID]
    ,[VIDY_KULTUR]
    ,SPD.[KOLICHESTVO] AS [KOLICHESTVO_SPETSIFIKATSIA]
	,SPD.[SUMMA] AS [SUMMA_SPETSIFIKATSIA_V_VALUTE]
	,SPD.[SUMMA_KZ_TG] AS [SUMMA_SPETSIFIKATSIA_KZT]
    ,SPD.[SUMMA_SO_SKIDKOY] AS [SUMMA_SO_SKIDKOY_SPETSIFIKATSIA]
	,SPD.[SKLAD_OTGRUZKI] AS [SKLAD_OTGRUZKI_SPETSIFIKATSIA]
    ,SPD.[PROSROCHENNYY_TOVAR] AS [PROSROCHENNYY_TOVAR_SPETSIFIKATSIA]
	--,VSP.KOLICHESTVO AS KOLICHESTVO_VIRUCHKA
	,O.DATE AS DATE_OTGRUZKA
	,O.KOLICHESTVO AS KOLICHESTVO_OTGRUZKA
	,O.SUMMA_KZT AS SUMMA_OTGRUZKA_KZT
	,O.SUMMA_ZAKUPA AS SUMMA_OTGRUZKA_V_VALUTE
	,V.DATE AS DATE_VOZVRAT
	,V.KOLICHESTVO AS KOLICHESTVO_VOZVRAT
	,V.[SUMMA_V_VALUTE] AS SUMMA_VOZVRAT_V_VALUTE
	,V.SUMMA_KZT AS SUMMA_VOZVRAT_KZT
	,CAST(ROUND((OPL.SUMMA_KZT/SUM(ISNULL(SPD.SUMMA,O.SUMMA_ZAKUPA)) OVER (PARTITION BY USO.[DOGOVOR_GUID]))*ISNULL(SPD.SUMMA,O.SUMMA_ZAKUPA),2) AS NUMERIC(15,2)) AS OPLATA_PO_NOMENKLATURE_KZT
	,CAST(ROUND((OPL.SUMMA_V_VALUTE/SUM(ISNULL(SPD.SUMMA,O.SUMMA_ZAKUPA)) OVER (PARTITION BY USO.[DOGOVOR_GUID]))*ISNULL(SPD.SUMMA,O.SUMMA_ZAKUPA),2) AS NUMERIC(15,2)) AS OPLATA_PO_NOMENKLATURE_V_VALUTE

--INTO L2.DBO.DOGOVOROV_S_POSTAVCHIKAMI
FROM UNION_SPD_OTGRUZ AS USO
LEFT JOIN SPEKA AS SPD
	ON USO.[DOGOVOR_GUID]=SPD.DOGOVOR_GUID
	AND USO.NOMENKLATURA_GUID=SPD.NOMENKLATURA_GUID
LEFT JOIN [L1].[dbo].DOGOVORY_KONTRAGENTOV AS DK
	ON USO.DOGOVOR_GUID=DK.GUID
LEFT JOIN L1.DBO.SEZONY S 
	ON DK.SEZON_GUID=S.GUID
LEFT JOIN L1.DBO.MENEDZHERY AS M
	ON DK.MENEDZHER_GUID=M.GUID
LEFT JOIN L1.DBO.KONTRAGENTY K
	ON K.GUID=DK.KONTRAGENT_GUID
LEFT JOIN L1.DBO.ORGANIZATSII AS ORG
	ON DK.ORGANIZATSIYA_GUID=ORG.GUID
LEFT JOIN L1.DBO.STRUKTURA_PREDPRIYATIYA AS SP 
	ON DK.STRUKTURA_PREDPRIYATIYA_GUID=SP.GUID
LEFT JOIN L1.DBO.NOMENKLATURA AS N 
	ON USO.NOMENKLATURA_GUID=N.GUID
LEFT JOIN OPLATA OPL
	ON DK.GUID=OPL.DOGOVOR_GUID
LEFT JOIN VOZVRAT AS V 
	ON USO.DOGOVOR_GUID=V. DOGOVOR_GUID
	AND USO.NOMENKLATURA_GUID=V.NOMENKLATURA_GUID
LEFT JOIN OTGRUZKA AS O 
	ON USO.DOGOVOR_GUID=O.DOGOVOR_GUID
	AND USO.NOMENKLATURA_GUID=O.NOMENKLATURA_GUID
WHERE DK.TIP_DOGOVORA != 'С покупателем / заказчиком'
--AND DK.GUID=0xA22B7085C2A4312A11EA5D477B275F5B
--AND DK.NAIMENOVANIE LIKE '%СРТ № 212-1976889%'
ORDER BY --DK.NAIMENOVANIE,N.NAIMENOVANIE, 
--DK.SUMMA,
DK.DATA DESC

