/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
WITH VOZVRAT AS(
SELECT MAX([DATE])[DATE]
      ,[DOGOVOR_GUID]
      ,[NOMENKLATURA_GUID]
      ,SUM([KOLICHESTVO])[KOLICHESTVO]
      ,SUM([SUMMA_VYRUCHKI])[SUMMA_VYRUCHKI]
FROM [L1].[dbo].[VYRUCHKA_I_SEBESTOIMOST_PRODAZH]
WHERE KOLICHESTVO < 0
GROUP BY 
      [DOGOVOR_GUID]
      ,[NOMENKLATURA_GUID]
)

,OTGRUZKA AS(
SELECT MAX([DATE])[DATE]
      ,[DOGOVOR_GUID]
      ,[NOMENKLATURA_GUID]
      ,SUM([KOLICHESTVO])[KOLICHESTVO]
      ,SUM([SUMMA_VYRUCHKI])[SUMMA_VYRUCHKI]
FROM [L1].[dbo].[VYRUCHKA_I_SEBESTOIMOST_PRODAZH]
WHERE KOLICHESTVO > 0
GROUP BY 
      [DOGOVOR_GUID]
      ,[NOMENKLATURA_GUID]
)

,SPEKA AS (SELECT [DOGOVOR_GUID]
      ,[NOMENKLATURA_GUID]
	  ,[VIDY_KULTUR]
      ,SUM([KOLICHESTVO]) AS [KOLICHESTVO]
      ,SUM(SPD.[SUMMA]) AS [SUMMA]
      ,SUM([SUMMA_SO_SKIDKOY]) AS [SUMMA_SO_SKIDKOY]
      ,[SKLAD_OTGRUZKI_GUID]
      ,[SKLAD_OTGRUZKI]
      ,[PROSROCHENNYY_TOVAR]
      ,CAST(ROUND(SUM(SPD.[SUMMA_KZ_TG]),2)AS NUMERIC(15,2)) AS [SUMMA_KZ_TG]
  FROM [L1].[dbo].[SPETSIFIKATSIYA_PO_DOGOVORU] SPD
  LEFT JOIN [L1].[dbo].DOGOVORY_KONTRAGENTOV AS DK
	ON SPD.DOGOVOR_GUID=DK.GUID
	WHERE DK.TIP_DOGOVORA='С покупателем / заказчиком'
GROUP BY 
	[DOGOVOR_GUID]
	,[PROSROCHENNYY_TOVAR]
    ,[NOMENKLATURA_GUID]
	,[VIDY_KULTUR]
    ,[SKLAD_OTGRUZKI_GUID]
    ,[SKLAD_OTGRUZKI]
)


,OPLATA AS (
SELECT 
      [DOGOVOR_GUID]
      ,SUM([SUMMA]) AS [SUMMA]
      ,SUM([K_OPLATE]) AS [K_OPLATE]
FROM [L1].[dbo].[RASCHETY_S_KLIENTAMI]
WHERE [synonym_registrator] NOT IN ('Корректировка реализации','Реализация товаров и услуг','Возврат товаров от клиента','Реализация услуг и прочих активов','Заказ клиента')

GROUP BY [DOGOVOR_GUID]

)


SELECT DISTINCT SPD.[DOGOVOR_GUID]
	,DK.NAIMENOVANIE AS DOGOVOR_NAIMENOVANIE
	,DK.VALYUTA_VZAIMORASCHETOV
	,DK.SUMMA AS SUMMA_DOGOVOR
	,OPL.SUMMA AS OPLATA_DOGOVOR
	,S.NAIMENOVANIE AS SEZON
	,M.NAIMENOVANIE AS MENEDZHER
	,K.NAIMENOVANIE AS KLIENTI
	,K.FAKT_ADRES_KONTRAGENTA AS FAKT_ADRES_KONTRAGENTA
	,ORG.NAIMENOVANIE AS ORGANIZATSII
	,SP.NAIMENOVANIE AS STRUKTURA_PREDPRIYATIYA
	,ISNULL(SP.[RODITEL],SP.[NAIMENOVANIE]) AS OBLAST
	,ISNULL(SP.[RODITEL2] ,ISNULL(SP.[RODITEL],SP.[NAIMENOVANIE]))DIREKSIA
	,DK.PROGRAMMA_DOGOVORA AS PROGRAMMA_DOGOVORA
	,DK.USLOVIYA_OPLATY AS USLOVIYA_OPLATY
	,DK.SPOSOB_DOSTAVKI AS SPOSOB_DOSTAVKI
	,DK.SOSTOYANIE AS SOSTOYANIE
	,DK.STATUS AS STATUS
	,CASE 
		WHEN K.VKHODIT_V_GRUPPU_KOMPANIY_ALEM_AGRO=1 THEN 1 
		ELSE 0 
	END AS [DOGOVOR_VNUTRI_GRUPPY]
	,DK.DATA
	,DK.DATA_NACHALA_DEYSTVIYA
	,DK.DATA_OKONCHANIYA_DEYSTVIYA
	,N.NAIMENOVANIE AS NAIMENOVANIE_NOMENKLATURA
	,N.KATEGORII_NOMENKLATURY_GROUP AS KATEGORII_NOMENKLATURY_GROUP
    ,N.[NORMA_RASKHODOVANIYA] AS [NORMA_RASKHODOVANIYA_NOMENKLATURA]
	,SPD.[NOMENKLATURA_GUID]
    ,[VIDY_KULTUR]
    ,SPD.[KOLICHESTVO] AS [KOLICHESTVO_SPETSIFIKATSIA]
	,SPD.[SUMMA] AS [SUMMA_SPETSIFIKATSIA]
    ,SPD.[SUMMA_SO_SKIDKOY] AS [SUMMA_SO_SKIDKOY_SPETSIFIKATSIA]
	,SPD.[SKLAD_OTGRUZKI] AS [SKLAD_OTGRUZKI_SPETSIFIKATSIA]
    ,SPD.[PROSROCHENNYY_TOVAR] AS [PROSROCHENNYY_TOVAR_SPETSIFIKATSIA]
	,SPD.[SUMMA_KZ_TG] AS [SUMMA_KZ_TG_SPETSIFIKATSIA]
	--,VSP.KOLICHESTVO AS KOLICHESTVO_VIRUCHKA
	,O.DATE AS DATE_OTGRUZKA
	,O.KOLICHESTVO AS KOLICHESTVO_OTGRUZKA
	,O.SUMMA_VYRUCHKI AS SUMMA_VYRUCHKI_OTGRUZKA
	,V.DATE AS DATE_VOZVRAT
	,V.KOLICHESTVO AS KOLICHESTVO_VOZVRAT
	,V.SUMMA_VYRUCHKI AS SUMMA_VOZVRAT
	,CAST(ROUND((OPL.SUMMA/SUM(SPD.[SUMMA]) OVER (PARTITION BY SPD.[DOGOVOR_GUID]))*SPD.SUMMA,2) AS NUMERIC(15,2)) AS OPLATA_PO_NOMENKLATURA

--INTO L2.DBO.DOGOVOROV_S_KLIENTAMI
FROM SPEKA AS SPD
LEFT JOIN [L1].[dbo].DOGOVORY_KONTRAGENTOV AS DK
	ON SPD.DOGOVOR_GUID=DK.GUID
LEFT JOIN L1.DBO.SEZONY S 
	ON DK.SEZON_GUID=S.GUID
LEFT JOIN L1.DBO.MENEDZHERY AS M
	ON DK.MENEDZHER_GUID=M.GUID
LEFT JOIN L1.DBO.KONTRAGENTY K
	ON K.GUID=DK.KONTRAGENT_GUID
LEFT JOIN L1.DBO.ORGANIZATSII AS ORG
	ON DK.ORGANIZATSIYA_GUID=ORG.GUID
LEFT JOIN L1.DBO.STRUKTURA_PREDPRIYATIYA AS SP 
	ON DK.STRUKTURA_PREDPRIYATIYA_GUID=SP.GUID
LEFT JOIN L1.DBO.NOMENKLATURA AS N 
	ON SPD.NOMENKLATURA_GUID=N.GUID
LEFT JOIN OPLATA OPL
	ON DK.GUID=OPL.DOGOVOR_GUID
--LEFT JOIN [L1].[dbo].VYRUCHKA_I_SEBESTOIMOST_PRODAZH VSP
--	ON DK.GUID=VSP.DOGOVOR_GUID
--	AND SPD.NOMENKLATURA_GUID=VSP.NOMENKLATURA_GUID
--	AND SPD.SKLAD_OTGRUZKI_GUID=VSP.SKLAD_GUID
LEFT JOIN VOZVRAT AS V 
	ON SPD.DOGOVOR_GUID=V.DOGOVOR_GUID
	AND SPD.NOMENKLATURA_GUID=V.NOMENKLATURA_GUID
LEFT JOIN OTGRUZKA AS O 
	ON SPD.DOGOVOR_GUID=O.DOGOVOR_GUID
	AND SPD.NOMENKLATURA_GUID=O.NOMENKLATURA_GUID
WHERE DK.TIP_DOGOVORA='С покупателем / заказчиком'

ORDER BY --DK.NAIMENOVANIE,N.NAIMENOVANIE, 
--DK.SUMMA,
DK.DATA DESC