USE [CRM_DWH]
GO
/****** Object:  StoredProcedure [dbo].[INSERT_SEMENA_2023]    Script Date: 07.02.2023 14:54:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[INSERT_SEMENA_2023]
AS

BEGIN
INSERT [CRM_DWH].[dbo].CRM_SEMENA_2023
SELECT
	GLAVNOE.[NOMENKLATURA_GUID]
	,[CRM_SEMENA_CHECK_2023].[NOMENKLATURA]
	,[CRM_SEMENA_CHECK_2023].[PROIZVODITELI]
	,[VIDY_KULTUR_NOMENKLATURY]
	,GLAVNOE.[MENEDZHER_GUID]
	,[CRM_SEMENA_CHECK_2023].[MENEDZHER]
	,[CRM_SEMENA_CHECK_2023].[DIREKSYA]
	,GLAVNOE.[DIREKSYA_GUID]
    ,[CRM_SEMENA_CHECK_2023].[PLAN_2023]
    ,[CRM_SEMENA_CHECK_2023].[PRODANO]
    ,[CRM_SEMENA_CHECK_2023].[OTGRUZHENO]
    ,[CRM_SEMENA_CHECK_2023].[PODTVERZHDENO_Edil]
    ,[CRM_SEMENA_CHECK_2023].[PODTVERZHDENO_Bakhyt]
	,[CRM_SEMENA_CHECK_2023].[PRODANO_SUM]
	,[CRM_SEMENA_CHECK_2023].[PLAN_SUM]
    ,[CRM_SEMENA_CHECK_2023].[OSTATOK_Edil]
    ,[CRM_SEMENA_CHECK_2023].[OSTATOK_Bakhyt]
FROM(
	SELECT [NOMENKLATURA_GUID]
		  ,[MENEDZHER_GUID]
		  ,[DIREKSYA_GUID]
	FROM [CRM_DWH].[dbo].[CRM_SEMENA_CHECK_2023]

	EXCEPT
  
	SELECT [NOMENKLATURA_GUID]
		  ,[MENEDZHER_GUID]
		  ,[DIREKSYA_GUID]
	FROM [CRM_DWH].[dbo].[CRM_SEMENA_2023]
) GLAVNOE
LEFT JOIN [CRM_DWH].[dbo].[CRM_SEMENA_CHECK_2023]
	ON [CRM_SEMENA_CHECK_2023].[NOMENKLATURA_GUID]=GLAVNOE.[NOMENKLATURA_GUID]
	AND [CRM_SEMENA_CHECK_2023].[MENEDZHER_GUID]=GLAVNOE.[MENEDZHER_GUID]
	AND [CRM_SEMENA_CHECK_2023].[DIREKSYA_GUID]=GLAVNOE.[DIREKSYA_GUID]

END
