USE [CRM_DWH]
GO
/****** Object:  StoredProcedure [dbo].[UPDATE_SEMENA_2023]    Script Date: 07.02.2023 15:00:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER procedure [dbo].[UPDATE_SEMENA_2023]
AS
BEGIN
UPDATE [CRM_DWH].dbo.CRM_SEMENA_2023
SET
[PROIZVODITELI]=CHECK_23.[PROIZVODITELI]
,[VIDY_KULTUR_NOMENKLATURY]=CHECK_23.[VIDY_KULTUR_NOMENKLATURY]
,[MENEDZHER]=CHECK_23.[MENEDZHER]
,[DIREKSYA]=CHECK_23.[DIREKSYA]
,[PLAN_2023]=CHECK_23.[PLAN_2023]
,[PRODANO]=CHECK_23.[PRODANO]
,[OTGRUZHENO]=CHECK_23.[OTGRUZHENO]
,[PRODANO_SUM]=CHECK_23.[PRODANO_SUM]
,[PLAN_SUM]=CHECK_23.[PLAN_SUM]

FROM [CRM_DWH].dbo.CRM_SEMENA_2023 AS S23
INNER JOIN [CRM_DWH].dbo.CRM_SEMENA_CHECK_2023 AS CHECK_23
	ON S23.[NOMENKLATURA_GUID]=CHECK_23.[NOMENKLATURA_GUID]
	AND S23.[MENEDZHER_GUID]=CHECK_23.[MENEDZHER_GUID]
	AND S23.[DIREKSYA_GUID]=CHECK_23.[DIREKSYA_GUID]
END
