WITH DOGOVOR AS(
SELECT 
   DK.[GUID]
  ,DK.[NAIMENOVANIE]
  ,ROW_NUMBER() OVER(ORDER BY DK.DATA DESC) AS ID
  ,DK.[DATA_NACHALA_DEYSTVIYA]
  ,DK.[DATA_OKONCHANIYA_DEYSTVIYA]
  ,DK.[DATA]
  ,DK.[NOMER]
  ,DK.[SOGLASOVAN]
  ,DK.STATUS
  ,DK.[ORGANIZATSIYA_GUID]
  ,K.NAIMENOVANIE AS KONTRAGENT
  ,DK.[KONTRAGENT_GUID]
  ,M.NAIMENOVANIE AS MENEDZHER
  ,DK.[MENEDZHER_GUID]
  ,S.NAIMENOVANIE AS SEZON
  ,DK.[SEZON_GUID]
  ,SK.NAIMENOVANIE AS SKLAD
  ,DK.[SKLAD_GUID]
  ,DK.[USLOVIYA_OPLATY]
  ,DK.[SPOSOB_DOSTAVKI]
  ,DK.[ADRES_DOSTAVKI]
  ,DK.[SUMMA_KZ_TG]
  ,DK.NOMER_DOP_SOGLASHENIYA
  ,DK.OSNOVNOY_DOGOVOR
FROM [L1].[dbo].[DOGOVORY_KONTRAGENTOV] DK
  LEFT JOIN L1.dbo.MENEDZHERY M
    ON M.GUID = DK.MENEDZHER_GUID
  LEFT JOIN L1.dbo.KONTRAGENTY K
    ON K.GUID = DK.KONTRAGENT_GUID
  LEFT JOIN L1.dbo.SKLADY SK
    ON SK.GUID = DK.SKLAD_GUID
  LEFT JOIN L1.dbo.SEZONY S
    ON S.GUID = DK.SEZON_GUID
  LEFT JOIN L1.dbo.DOGOVORY_KONTRAGENTOV DK1
    ON DK1.GUID = DK.OSNOVNOY_DOGOVOR
WHERE 1=1
  AND DK.TIP_DOGOVORA = 'С покупателем / заказчиком'
  AND DK.DOGOVOR_VNUTRI_GRUPPY = 0

)
SELECT 
   D.[GUID]
  ,D.[NAIMENOVANIE]
  ,D.[DATA_NACHALA_DEYSTVIYA]
  ,D.[DATA_OKONCHANIYA_DEYSTVIYA]
  ,D.[DATA]
  ,D.[NOMER]
  ,D.[SOGLASOVAN]
  ,D.[STATUS]
  ,D.[ORGANIZATSIYA_GUID]
  ,D.[KONTRAGENT]
  ,D.[KONTRAGENT_GUID]
  ,D.[MENEDZHER]
  ,D.[MENEDZHER_GUID]
  ,D.[SEZON]
  ,D.[SEZON_GUID]
  ,D.[SKLAD]
  ,D.[SKLAD_GUID]
  ,D.[USLOVIYA_OPLATY]
  ,D.[SPOSOB_DOSTAVKI]
  ,D.[ADRES_DOSTAVKI]
  ,D.[SUMMA_KZ_TG]
  ,D.[ID]
  ,D.[NOMER_DOP_SOGLASHENIYA]
  ,D.[OSNOVNOY_DOGOVOR]
  ,ISNULL(D1.ID, 0) AS OSNOVNOY_DOGOVOR_ID
--INTO CRM_DWH.DBO.CRM_DOGOVOR
FROM DOGOVOR D 
  LEFT JOIN DOGOVOR D1
   ON D1.GUID = D.OSNOVNOY_DOGOVOR