WITH ANALIZ AS(
SELECT DISTINCT
   AD.[ssylka]
  ,AD.[data]
  ,MAX(AD.data) OVER(PARTITION BY AD.dogovor) AS MAX_DATE
  ,AD.dogovor
  ,AD.marzhinalnost
FROM [L0].[dbo].[analiz_dogovora] AD
WHERE 1=1
)
, ANALIZ_DOGOVORA AS(
SELECT 
   A.data
  ,A.dogovor
  ,A.marzhinalnost
FROM ANALIZ A
WHERE 1=1
  AND A.data = A.MAX_DATE
)
, DOGOVOR AS(
SELECT 
   DK.[GUID]
  ,DK.[DATA]
  ,DK.[NOMER]
  ,M.GUID AS MENEDZHER_GUID
  ,M.NAIMENOVANIE AS MENEDZHER
  ,MG.GRADE
  ,DK.[SUMMA_KZ_TG]
  ,AD.marzhinalnost
  ,DK.SUMMA_KZ_TG * AD.marzhinalnost / 100 AS MARZHA
FROM [L1].[dbo].[DOGOVORY_KONTRAGENTOV] DK
  LEFT JOIN L1.dbo.MENEDZHERY M
    ON M.GUID = DK.MENEDZHER_GUID
  INNER JOIN ANALIZ_DOGOVORA AD
    ON AD.dogovor = DK.GUID
  LEFT JOIN CRM_DWH.dbo.CRM_KPI_MANAGER_GRADE MG
    ON MG.GUID = DK.MENEDZHER_GUID
WHERE 1=1
  AND DK.SEZON_GUID = 0xAF90D4F5EF10792511ECEC824678758E
  AND DK.TIP_DOGOVORA = 'С покупателем / заказчиком'
  AND DK.DOGOVOR_VNUTRI_GRUPPY = 0
  AND DK.ORGANIZATSIYA_GUID = 0x80DE000C29E67B2E11E636A5C3C5D8AE
  AND M.NAIMENOVANIE <> 'Даутов Нуржан Оразалиевич'
  AND DK.SUMMA_KZ_TG > 10
  AND DK.STATUS = 'Действует'
--ORDER BY  
--  DK.DATA DESC
)
, PLAN_PRODAZH AS(
SELECT 
   M.NAIMENOVANIE AS MENEDZHER
  ,PP.MENEDZHER_GUID
  ,SUM(PP.[KOLICHESTVO]) AS KOLICHESTVO
  ,SUM(PP.[SUMMA]) AS SUM_PLAN
FROM [L1].[dbo].[PLAN_PRODAZH] PP
  LEFT JOIN L1.dbo.MENEDZHERY M
    ON M.GUID = PP.MENEDZHER_GUID 
WHERE 1=1
  AND PP.SEZON_GUID = 0xAF90D4F5EF10792511ECEC824678758E
  AND PP.VIDY_PLANOV = 'План продаж бюджетный'
GROUP BY
   M.NAIMENOVANIE
  ,PP.MENEDZHER_GUID
)
, SUM_MARZHA AS(
SELECT 
   D.MENEDZHER
  ,D.MENEDZHER_GUID
  ,CU.ID
  ,D.GRADE
  ,PP.SUM_PLAN
  ,SUM(D.SUMMA_KZ_TG) AS SUM_DOGOVOR
  ,CAST(SUM(D.MARZHA) / SUM(D.SUMMA_KZ_TG) * 100 AS decimal(4, 2)) AS MARZHA
  ,PP.SUM_PLAN * CAST(SUM(D.MARZHA) / SUM(D.SUMMA_KZ_TG) * 100 AS int) / 100  AS PLAN_MARZHA
  ,SUM(D.MARZHA) AS SUM_MARZHA
  ,CASE
     WHEN SUM(D.MARZHA) - (PP.SUM_PLAN * CAST(SUM(D.MARZHA) / SUM(D.SUMMA_KZ_TG) * 100 AS int) / 100) < 0
	   THEN 0
	 ELSE SUM(D.MARZHA) - (PP.SUM_PLAN * CAST(SUM(D.MARZHA) / SUM(D.SUMMA_KZ_TG) * 100 AS int) / 100)
   END AS OUT_OF_PLAN
FROM DOGOVOR D
  LEFT JOIN PLAN_PRODAZH PP
    ON PP.MENEDZHER_GUID = D.MENEDZHER_GUID
  LEFT JOIN CRM_DWH.dbo.CRM_USERS CU
    ON CU.GUID = D.MENEDZHER_GUID
WHERE 1=1
  AND D.GRADE IS NOT NULL
  AND PP.SUM_PLAN IS NOT NULL
GROUP BY
   D.MENEDZHER
  ,D.MENEDZHER_GUID
  ,CU.ID
  ,D.GRADE
  ,PP.SUM_PLAN
--ORDER BY 
--  D.GRADE DESC
)
, MARZHA_STEP AS(
SELECT
   SM.MENEDZHER
  ,SM.MENEDZHER_GUID
  ,SM.GRADE
  ,SM.SUM_DOGOVOR
  ,SM.SUM_PLAN
  ,SM.PLAN_MARZHA
  ,SM.SUM_MARZHA
  ,SM.OUT_OF_PLAN
  ,SM.MARZHA
  ,CASE 
     WHEN SM.OUT_OF_PLAN = 0
	   THEN 
	     CASE
	       WHEN SM.SUM_MARZHA < 100000000
	 	 	 THEN SM.SUM_MARZHA
	 	   ELSE 100000000
	     END
	 ELSE 
	   CASE
	     WHEN SM.PLAN_MARZHA < 100000000
	 	   THEN SM.PLAN_MARZHA
	 	 ELSE 100000000
	   END
   END AS [1]
  ,CASE
     WHEN SM.OUT_OF_PLAN = 0
	   THEN 
	     CASE 
		   WHEN SM.SUM_MARZHA BETWEEN 100000001 AND 200000000
		     THEN SM.SUM_MARZHA - 100000000
		   WHEN SM.SUM_MARZHA > 200000000 
		     THEN 100000000 
		   ELSE 0 
		 END
	 ELSE 
	   CASE 
		 WHEN SM.PLAN_MARZHA BETWEEN 100000001 AND 200000000
		   THEN SM.PLAN_MARZHA - 100000000
		 WHEN SM.PLAN_MARZHA > 200000000 
		   THEN 100000000 
		 ELSE 0 
	   END
   END AS [2]
  ,CASE
     WHEN SM.OUT_OF_PLAN = 0
	   THEN 
	     CASE 
		   WHEN SM.SUM_MARZHA BETWEEN 200000001 AND 300000000
		     THEN SM.SUM_MARZHA - 200000000
		   WHEN SM.SUM_MARZHA > 300000000
		     THEN 100000000
		   ELSE 0
		 END
	 ELSE 
	   CASE 
		 WHEN SM.PLAN_MARZHA BETWEEN 200000001 AND 300000000
		   THEN SM.PLAN_MARZHA - 200000000
		 WHEN SM.PLAN_MARZHA > 300000000
		   THEN 100000000 
		 ELSE 0
	   END 
   END AS [3]
  ,CASE 
     WHEN SM.OUT_OF_PLAN = 0
	   THEN 
	     CASE 
	 	   WHEN SM.SUM_MARZHA > 300000000
	 	     THEN SM.SUM_MARZHA - 300000000
	 	   ELSE 0
	     END  
	 ELSE 
	   CASE 
	 	 WHEN SM.PLAN_MARZHA > 300000000
	 	   THEN SM.PLAN_MARZHA - 300000000
	 	 ELSE 0 
	   END
   END AS [4]
FROM SUM_MARZHA SM
--ORDER BY
--   SM.SUM_MARZHA DESC
)
, OOP_1 AS(
SELECT 
   MS.MENEDZHER
  ,MS.MENEDZHER_GUID
  ,MS.GRADE
  ,MS.SUM_DOGOVOR
  ,MS.SUM_PLAN
  ,MS.PLAN_MARZHA
  ,MS.SUM_MARZHA
  ,MS.OUT_OF_PLAN
  ,MS.[1]
  ,MS.MARZHA
  ,CASE
     WHEN MS.OUT_OF_PLAN = 0
	   THEN 0 
	 ELSE 
	   CASE 
	     WHEN MS.[1] = 100000000
		   THEN 0
		 ELSE
		     CASE 
		       WHEN MS.OUT_OF_PLAN + MS.[1] <= 100000000
		 	     THEN MS.OUT_OF_PLAN 
		 	   ELSE 100000000 - MS.[1] 
		 	 END
	     END
   END AS OOP_1
  ,MS.[2]
  ,MS.[3]
  ,MS.[4]   
FROM MARZHA_STEP MS
)
, OOP_2 AS(
SELECT 
   O1.MENEDZHER
  ,O1.MENEDZHER_GUID
  ,O1.GRADE
  ,O1.SUM_DOGOVOR
  ,O1.SUM_PLAN
  ,O1.PLAN_MARZHA
  ,O1.SUM_MARZHA
  ,O1.OUT_OF_PLAN
  ,O1.[1]
  ,O1.OOP_1
  ,O1.[2]
  ,O1.MARZHA
  ,CASE
     WHEN O1.[2] = 100000000
	   THEN 0           
	 ELSE 
	   CASE 
	     WHEN O1.[1] = 100000000
		   THEN 
		     CASE 
			   WHEN O1.[2] + O1.OUT_OF_PLAN <= 100000000
			     THEN O1.OUT_OF_PLAN
               ELSE 100000000 - O1.[2]
			 END
	     ELSE 
		   CASE
		     WHEN O1.[OUT_OF_PLAN] - O1.OOP_1 > 100000000
			   THEN 100000000
			 ELSE O1.[OUT_OF_PLAN] - O1.OOP_1
		   END 
	   END
   END AS OOP_2
  ,O1.[3]
  ,O1.[4]
FROM OOP_1 O1
)
, OOP_3 AS(
SELECT
   O2.MENEDZHER
  ,O2.MENEDZHER_GUID
  ,O2.GRADE
  ,O2.SUM_DOGOVOR
  ,O2.SUM_PLAN
  ,O2.PLAN_MARZHA
  ,O2.SUM_MARZHA
  ,O2.OUT_OF_PLAN AS OUT_OF_PLAN
  ,O2.[1]
  ,O2.OOP_1
  ,O2.[2]
  ,O2.OOP_2
  ,O2.[3]
  ,O2.MARZHA
  ,CASE 
     WHEN O2.[3] = 100000000
	   THEN 0
     WHEN O2.OUT_OF_PLAN = 0
	   THEN 0 
	 WHEN O2.OUT_OF_PLAN = O2.OOP_1
	   THEN 0  
	 WHEN O2.OUT_OF_PLAN = (O2.OOP_1 + O2.OOP_2)
	   THEN 0 
	 ELSE 
	   CASE
	     WHEN O2.[2] = 100000000
		   THEN 
		     CASE
			   WHEN O2.[3] + O2.OUT_OF_PLAN > 100000000
			     THEN 100000000 - O2.[3]  
			   ELSE O2.OUT_OF_PLAN 
			 END 
		 ELSE 
		   CASE
			 WHEN O2.OUT_OF_PLAN - O2.OOP_2 = 0
			   THEN 0
			 ELSE 
			   CASE
			     WHEN O2.OUT_OF_PLAN - O2.OOP_2 > 100000000
				   THEN 100000000
				 ELSE O2.OUT_OF_PLAN - O2.OOP_2
			   END 
		   END 
		     
	   END 
   END AS OOP_3 
  ,O2.[4]
FROM OOP_2 O2
)
, OOP_4 AS(
SELECT 
   O3.MENEDZHER
  ,O3.MENEDZHER_GUID
  ,O3.GRADE
  ,O3.SUM_DOGOVOR
  ,O3.SUM_PLAN
  ,O3.MARZHA
  ,O3.PLAN_MARZHA
  ,O3.SUM_MARZHA
  ,CAST(O3.OUT_OF_PLAN  AS decimal(38,2)) AS OUT_OF_PLAN
  ,CAST(O3.[1] AS decimal(38,2)) AS [1]
  ,CAST(O3.[2] AS decimal(38,2)) AS [2]
  ,CAST(O3.[3] AS decimal(38,2)) AS [3]
  ,CAST(O3.[4] AS decimal(38,2)) AS [4]
  ,CAST(O3.OOP_1 AS decimal(38,2)) AS OOP_1
  ,CAST(O3.OOP_2 AS decimal(38,2)) AS OOP_2
  ,CAST(O3.OOP_3 AS decimal(38,2)) AS OOP_3
  ,CASE 
     WHEN O3.[4] = 100000000
	   THEN CAST(O3.OUT_OF_PLAN AS decimal(38,2))
	 WHEN O3.OUT_OF_PLAN = 0
	   THEN CAST(0 AS decimal(38,2))
	 WHEN O3.OUT_OF_PLAN = (O3.OOP_1 + O3.OOP_2 + O3.OOP_3)
	   THEN CAST(0 AS decimal(38,2))
	 WHEN O3.[3] = 100000000
	   THEN CAST(O3.OUT_OF_PLAN AS decimal(38,2))
	 WHEN O3.[2] = 100000000
	   THEN 
	     CASE 
		   WHEN O3.OUT_OF_PLAN + O3.[3] > 100000000
		     THEN CAST(O3.OUT_OF_PLAN - O3.OOP_3 AS decimal(38,2))
		   ELSE CAST(0 AS decimal(38,2))
		 END       
   END AS OOP_4
FROM OOP_3 O3
)
, KPI_1 AS(
SELECT 
   [MENEDZHER]
  ,[MENEDZHER_GUID]
  ,[GRADE]
  ,[SUM_DOGOVOR]
  ,[SUM_PLAN]
  ,[MARZHA]
  ,[SUM_MARZHA]
  ,PLAN_MARZHA
  ,OUT_OF_PLAN
  ,STEP
  ,VALUE
FROM OOP_4
UNPIVOT(
  VALUE FOR STEP IN ([1], [2], [3], [4])
) UNPVT
)
, KPI_2 AS(
SELECT 
   [MENEDZHER]
  ,[MENEDZHER_GUID]
  ,[GRADE]
  ,[SUM_DOGOVOR]
  ,[SUM_PLAN]
  ,[MARZHA]
  ,[SUM_MARZHA]
  ,OUT_OF_PLAN
  ,PLAN_MARZHA
  ,CASE
     WHEN STEP = 'OOP_1'
       THEN 1
	 WHEN STEP = 'OOP_2'
       THEN 2
	 WHEN STEP = 'OOP_3'
       THEN 3
	 WHEN STEP = 'OOP_4'
       THEN 4
   END AS STEP
  ,VALUE
FROM OOP_4
UNPIVOT(
  VALUE FOR STEP IN (OOP_1, OOP_2, OOP_3, OOP_4)
) UNPVT
)
--, SEPARATED AS(
SELECT 
   K1.[MENEDZHER] AS MANAGER
  ,CONVERT(nvarchar(50), K1.[MENEDZHER_GUID], 1) AS MANAGER_GUID
  ,CU.ID AS MANAGER_ID
  ,K1.[GRADE]
  ,K1.[SUM_DOGOVOR]
  ,K1.[SUM_PLAN]
  ,K1.MARZHA / 100 AS MARGIN
  ,K1.[SUM_MARZHA] AS SUM_MARGINALITY
  ,K1.PLAN_MARZHA AS PLAN_MARGINALITY
  ,K1.OUT_OF_PLAN AS 'SUM_OUT_OF_PLAN'
  ,K1.VALUE AS 'PLAN'
  ,K2.VALUE AS OUT_OF_PLAN
  ,K1.STEP
  ,SG.PLANNED
  ,SG.UNPLANNED
  ,K1.[VALUE] * SG.PLANNED / 100 AS PLANNED_SUM
  ,K2.[VALUE] * SG.UNPLANNED / 100 AS UNPLANNED_SUM
  ,(K1.[VALUE] * SG.PLANNED / 100) + (K2.[VALUE] * SG.UNPLANNED / 100) AS BASIS
--INTO CRM_DWH.dbo.CRM_KPI_BASIS
FROM KPI_1 K1
  LEFT JOIN KPI_2 K2
    ON K2.MENEDZHER = K1.MENEDZHER
	  AND K2.STEP = K1.STEP
  LEFT JOIN CRM_DWH.dbo.CRM_KPI_SPR_GRADE SG
    ON SG.GRADE = K1.GRADE
	  AND SG.STEP = K1.STEP
  LEFT JOIN CRM_DWH.dbo.CRM_USERS CU
    ON CU.GUID = K1.MENEDZHER_GUID
ORDER BY
   K1.SUM_MARZHA DESC

  

  