/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT [NOMENKLATURA_GUID]
      ,[NOMENKLATURA]
      ,[PROIZVODITELI]
      ,[VIDY_KULTUR_NOMENKLATURY]
      ,[MENEDZHER_GUID]
      ,[MENEDZHER]
      ,[DIREKSYA]
      ,[DIREKSYA_GUID]
      ,[PLAN_2023]
      ,[PRODANO]
      ,[OTGRUZHENO]
      ,[PODTVERZHDENO_Edil]
      ,[PODTVERZHDENO_Bakhyt]
      ,[PRODANO_SUM]
      ,[PLAN_SUM]
      ,[OSTATOK_Edil]
      ,[OSTATOK_Bakhyt]
--INTO [CRM_DWH].[dbo].[CRM_SEMENA_2023]
  FROM [CRM_DWH].[dbo].[CRM_SEMENA_CHECK_2023]