 WITH ALL_NOM_MENED AS(
 SELECT 
     [NOMENKLATURA_GUID] AS [NOMENKLATURA_GUID]
    ,DK.MENEDZHER_GUID AS [MENEDZHER_GUID]
  FROM [L1].[dbo].[SPETSIFIKATSIYA_PO_DOGOVORU] SD
    LEFT JOIN L1.dbo.NOMENKLATURA N
      ON N.GUID = SD.NOMENKLATURA_GUID
    LEFT JOIN L1.dbo.DOGOVORY_KONTRAGENTOV DK
    ON DK.GUID = SD.DOGOVOR_GUID
  WHERE 1=1
    AND N.RODITEL2 = 'Семена'
    AND DK.SEZON_GUID = 0xAF90D4F5EF10792511ECEC824678758E
	AND DK.TIP_DOGOVORA='С покупателем / заказчиком'

UNION 

	SELECT 
			[NOMENKLATURA_GUID] AS [NOMENKLATURA_GUID]
			,[MENEDZHER_GUID] AS [MENEDZHER_GUID]
	FROM [L1].[dbo].[PLAN_PRODAZH] AS PP
		LEFT JOIN [L1].[dbo].NOMENKLATURA AS N
		ON PP.NOMENKLATURA_GUID=N.GUID
		LEFT JOIN [L1].[dbo].SEZONY AS S
		ON PP.SEZON_GUID=S.GUID
		LEFT JOIN [L1].[dbo].MENEDZHERY AS M 
		ON PP.MENEDZHER_GUID=M.GUID
		WHERE 1=1
		AND VIDY_PLANOV='План продаж оперативный'
		AND N.KATEGORII_NOMENKLATURY_GROUP='Семена'
		AND S.GUID=0xAF90D4F5EF10792511ECEC824678758E-----Сезон 2023

UNION 


	  SELECT 
		 VYR.[NOMENKLATURA_GUID]
		 ,DK.MENEDZHER_GUID
	  FROM [L1].[dbo].[VYRUCHKA_I_SEBESTOIMOST_PRODAZH] VYR
		LEFT JOIN L1.dbo.NOMENKLATURA N
		  ON N.GUID = VYR.NOMENKLATURA_GUID
		LEFT JOIN L1.dbo.DOGOVORY_KONTRAGENTOV DK
		  ON DK.GUID = VYR.DOGOVOR_GUID
	  WHERE 1=1
		AND N.RODITEL2 = 'Семена'
		AND DK.SEZON_GUID = 0xAF90D4F5EF10792511ECEC824678758E

)

,SPETSIFIKATSIYA
AS (
  SELECT 
     [NOMENKLATURA_GUID]
    ,DK.MENEDZHER_GUID
    ,SUM([KOLICHESTVO]) AS [KOLICHESTVO]
  FROM [L1].[dbo].[SPETSIFIKATSIYA_PO_DOGOVORU] SD
    LEFT JOIN L1.dbo.NOMENKLATURA N
      ON N.GUID = SD.NOMENKLATURA_GUID
    LEFT JOIN L1.dbo.DOGOVORY_KONTRAGENTOV DK
    ON DK.GUID = SD.DOGOVOR_GUID
  WHERE 1=1
    AND N.RODITEL2 = 'Семена'
    AND DK.SEZON_GUID = 0xAF90D4F5EF10792511ECEC824678758E
	AND DK.TIP_DOGOVORA='С покупателем / заказчиком'
GROUP BY 
     [NOMENKLATURA_GUID]
    ,DK.MENEDZHER_GUID
),
VYRUCHKA AS(
  SELECT 
     VYR.[NOMENKLATURA_GUID]
    ,DK.MENEDZHER_GUID
    ,SUM(VYR.[KOLICHESTVO]) AS [KOLICHESTVO]
  FROM [L1].[dbo].[VYRUCHKA_I_SEBESTOIMOST_PRODAZH] VYR
    LEFT JOIN L1.dbo.NOMENKLATURA N
      ON N.GUID = VYR.NOMENKLATURA_GUID
    LEFT JOIN L1.dbo.DOGOVORY_KONTRAGENTOV DK
      ON DK.GUID = VYR.DOGOVOR_GUID
  WHERE 1=1
    AND N.RODITEL2 = 'Семена'
    AND DK.SEZON_GUID = 0xAF90D4F5EF10792511ECEC824678758E
GROUP BY 
	VYR.[NOMENKLATURA_GUID]
    ,DK.MENEDZHER_GUID
),
PLAN_2023 AS (SELECT 
				  N.NAIMENOVANIE AS [NOMENKLATURA]
				  ,[NOMENKLATURA_GUID]
				  ,M.NAIMENOVANIE AS [MENEDZHER]
				  ,[MENEDZHER_GUID]
				  ,SUM([KOLICHESTVO]) AS [KOLICHESTVO]
			FROM [L1].[dbo].[PLAN_PRODAZH] AS PP
			  LEFT JOIN [L1].[dbo].NOMENKLATURA AS N
			  ON PP.NOMENKLATURA_GUID=N.GUID
			  LEFT JOIN [L1].[dbo].SEZONY AS S
			  ON PP.SEZON_GUID=S.GUID
			  LEFT JOIN [L1].[dbo].MENEDZHERY AS M 
			  ON PP.MENEDZHER_GUID=M.GUID
			  WHERE 1=1
			  AND VIDY_PLANOV='План продаж оперативный'
			  AND N.KATEGORII_NOMENKLATURY_GROUP='Семена'
			  AND S.GUID=0xAF90D4F5EF10792511ECEC824678758E-----Сезон 2023

			  GROUP BY N.NAIMENOVANIE
				  ,[NOMENKLATURA_GUID]
				  ,[MENEDZHER_GUID]
				  ,M.NAIMENOVANIE 
	  )

SELECT 
	ALL_NOM_MENED.NOMENKLATURA_GUID
	,N.NAIMENOVANIE AS NOMENKLATURA
	,N.PROIZVODITELI
	,N.VIDY_KULTUR_NOMENKLATURY
	,ALL_NOM_MENED.MENEDZHER_GUID
	,M.NAIMENOVANIE AS MENEDZHER
	,SP.DIREKSYA
	,SP.DIREKSYA_GUID
	,ISNULL(P23.KOLICHESTVO,0) AS PLAN_2023
	,ISNULL(S.KOLICHESTVO,0) AS PRODANO
	,ISNULL(V.KOLICHESTVO,0) AS OTGRUZHENO
	,0 AS PODTVERZHDENO_Edil
	,0 AS PODTVERZHDENO_Bakhyt
	,ISNULL(SUM(S.KOLICHESTVO) OVER(PARTITION BY SP.DIREKSYA_GUID,ALL_NOM_MENED.NOMENKLATURA_GUID),0) AS PRODANO_SUM
	,ISNULL(SUM(P23.KOLICHESTVO) OVER (PARTITION BY SP.DIREKSYA_GUID,ALL_NOM_MENED.NOMENKLATURA_GUID),0) AS PLAN_SUM
	,0 AS OSTATOK_Edil
	,0 AS OSTATOK_Bakhyt
--INTO CRM_DWH.dbo.CRM_SEMENA_CHECK_2023
FROM ALL_NOM_MENED 
LEFT JOIN SPETSIFIKATSIYA AS S
	ON S.NOMENKLATURA_GUID=ALL_NOM_MENED.NOMENKLATURA_GUID
	AND S.MENEDZHER_GUID=ALL_NOM_MENED.MENEDZHER_GUID
LEFT JOIN PLAN_2023 AS P23
	ON P23.NOMENKLATURA_GUID=ALL_NOM_MENED.NOMENKLATURA_GUID
	AND P23.MENEDZHER_GUID=ALL_NOM_MENED.MENEDZHER_GUID
LEFT JOIN VYRUCHKA AS V 
	ON V.NOMENKLATURA_GUID=ALL_NOM_MENED .NOMENKLATURA_GUID
	AND V.MENEDZHER_GUID=ALL_NOM_MENED.MENEDZHER_GUID
LEFT JOIN L1.dbo.NOMENKLATURA AS N
	ON ALL_NOM_MENED .NOMENKLATURA_GUID=N.GUID
LEFT JOIN L1.dbo.MENEDZHERY AS M 
	ON ALL_NOM_MENED .MENEDZHER_GUID=M.GUID
LEFT JOIN L1.DBO.STRUKTURA_PREDPRIYATIYA AS SP
	ON M.STRUKTURA_PREDPRIYATIYA_GUID=SP.GUID
