
--DECLARE @NEXT_WEEK INT = DATEPART(WEEK,CAST(GETDATE() AS DATE)) + 1;
CREATE PROCEDURE OPLATY_ETOGO_NEDELI 

@manager_guid BINARY(16)


AS 
BEGIN 
DECLARE @THIS_WEEK INT = DATEPART(WEEK,CAST(GETDATE() AS DATE));
	WITH OPLATA AS (
	/****** OPLATY ******/
	SELECT     
			SUM(RSK.[SUMMA]) AS [SUMMA]
		  ,RSK.[KONTRAGENT_GUID]
		  ,[DOGOVOR_GUID]
	  FROM [L1].[dbo].[RASCHETY_S_KLIENTAMI_PO_DOKUMENTAM] AS RSK
	INNER JOIN L1.DBO.DOGOVORY_KONTRAGENTOV AS DK
		ON RSK.DOGOVOR_GUID=DK.GUID

	  WHERE [TIP_DOKUMENTA] IN ('Расчет курсовых разниц','Списание задолженности','Приходный кассовый ордер'
	  ,'Поступление безналичных денежных средств','Взаимозачет задолженности','Операция по платежной карте'
	  ,'Списание безналичных денежных средств','Расходный кассовый ордер','Ввод начальных остатков','Корректировка реализации')
	 --AND DOGOVOR_GUID=0xAF9AD4F5EF10792511EDEFDE4C05CE08
		AND DK.STATUS='Действует'
		AND DK.TIP_DOGOVORA='С покупателем / заказчиком'
		AND [ORGANIZATSYA_GUID]=0x80DE000C29E67B2E11E636A5C3C5D8AE

	  GROUP BY RSK.[KONTRAGENT_GUID]
		  ,[DOGOVOR_GUID]
	)
	, SPEKA AS (
	/******ZAKLUCHENO******/

	SELECT SPD.[DOGOVOR_GUID] AS [DOGOVOR_GUID]
			,DK.KONTRAGENT_GUID
		  ,SUM(SPD.[SUMMA]) AS [SUMMA]
	  FROM [L1].[dbo].[SPETSIFIKATSIYA_PO_DOGOVORU] AS SPD
	  LEFT JOIN L1.DBO.DOGOVORY_KONTRAGENTOV AS DK
		ON SPD.DOGOVOR_GUID=DK.GUID
	LEFT JOIN L1.DBO.SEZONY S
		ON DK.SEZON_GUID=S.GUID
	LEFT JOIN L1.DBO.ORGANIZATSII AS O
		ON DK.ORGANIZATSIYA_GUID=O.GUID
	WHERE 1=1
	  --AND S.NAIMENOVANIE = 'Сезон 2023'
		AND DK.STATUS='Действует'
		AND DK.TIP_DOGOVORA='С покупателем / заказчиком'
		AND O.NAIMENOVANIE=N'ТОО «Alem Agro Holding (АлемАгро Холдинг)»'
	--AND DK.GUID=0x80B900155D01C90111E74115A747A883
	GROUP BY SPD.[DOGOVOR_GUID] 
	,DK.KONTRAGENT_GUID
		)
	,GRAFIK AS (
	/****** GRAFIK OPLATY BYGINGE DEIN +7 KYN ******/
	SELECT 
	[DOGOVOR_GUID]
		  ,DK.KONTRAGENT_GUID
		  ,SUM([SUMMA_OPLATY]) as [SUMMA_OPLATY_PO_GRAFIKGU]
	  FROM [L1].[dbo].[GRAFIK_ISPOLNENIYA_DOGOVORA] AS GID
		LEFT JOIN L1.DBO.DOGOVORY_KONTRAGENTOV AS DK
		ON GID.DOGOVOR_GUID=DK.GUID
	LEFT JOIN L1.DBO.SEZONY S
		ON DK.SEZON_GUID=S.GUID
	LEFT JOIN L1.DBO.ORGANIZATSII AS O
		ON DK.ORGANIZATSIYA_GUID=O.GUID
	WHERE 1=1
	   -- AND S.NAIMENOVANIE = 'Сезон 2023'
		AND DK.STATUS='Действует'
		AND DK.TIP_DOGOVORA='С покупателем / заказчиком'
		AND O.NAIMENOVANIE=N'ТОО «Alem Agro Holding (АлемАгро Холдинг)»'
		--AND [DATA_PO_GRAFIKU]>'2023'
	AND [DATA_PO_GRAFIKU]<=CAST(DATEADD(dd, 7-(DATEPART(dw, getdate())), getdate()) AS DATE) /***END OF WEEK***/

	GROUP BY GID.[DOGOVOR_GUID] 
	,DK.KONTRAGENT_GUID
	)



	,SPRAVKA AS (

	SELECT
	GRAFIK.DOGOVOR_GUID
	--,SPEKA.KONTRAGENT_GUID
	FROM GRAFIK

	UNION 

	SELECT
	OPLATA.DOGOVOR_GUID
	--,OPLATA.KONTRAGENT_GUID
	FROM OPLATA

	)

	,BASTYSI AS (
	SELECT 
	SPRAVKA.DOGOVOR_GUID
	--,SPRAVKA.KONTRAGENT_GUID
	,ISNULL(GRAFIK.SUMMA_OPLATY_PO_GRAFIKGU,DK.SUMMA) AS SUMMA_OPLATY_PO_GRAFIKGU
	,OPLATA.SUMMA AS OPLATA
	,(ISNULL(OPLATA.SUMMA,0) - ISNULL(GRAFIK.SUMMA_OPLATY_PO_GRAFIKGU,0) )*(-1) AS OSTATOK

	FROM SPRAVKA
	LEFT JOIN L1.dbo.DOGOVORY_KONTRAGENTOV DK ON DK.GUID=SPRAVKA.DOGOVOR_GUID
	LEFT JOIN GRAFIK ON SPRAVKA.DOGOVOR_GUID=GRAFIK.DOGOVOR_GUID
	LEFT JOIN OPLATA  ON OPLATA.DOGOVOR_GUID=SPRAVKA.DOGOVOR_GUID
	LEFT JOIN SPEKA ON SPRAVKA.DOGOVOR_GUID=SPEKA.DOGOVOR_GUID
	--WHERE SPRAVKA.DOGOVOR_GUID=0x801E00155D01C90111E6E8F2D90DB98A
	)

	SELECT
	BASTY.DOGOVOR_GUID
	,BASTY.OPLATA
	,GID.SUMMA_OPLATY AS SUMMA_PO_GRAFIGU
	,BASTY.OSTATOK
	,DK.NOMER
	,S.NAIMENOVANIE AS SEZON
	,GID.DATA_PO_GRAFIKU
	,M.NAIMENOVANIE AS MENEDZHER
	,K.NAIMENOVANIE AS KONTRAGENT
	,DATEPART(WEEK,GID.DATA_PO_GRAFIKU)
	FROM BASTYSI AS BASTY
	INNER JOIN GRAFIK AS GRA
		ON BASTY.DOGOVOR_GUID=GRA.DOGOVOR_GUID
	INNER JOIN L1.dbo.DOGOVORY_KONTRAGENTOV AS DK
		ON BASTY.DOGOVOR_GUID=DK.GUID
	INNER JOIN L1.dbo.SEZONY AS S
		ON DK.SEZON_GUID=S.GUID
	INNER JOIN [L1].[dbo].[GRAFIK_ISPOLNENIYA_DOGOVORA] AS GID
		ON BASTY.DOGOVOR_GUID=GID.DOGOVOR_GUID
	INNER JOIN L1.dbo.MENEDZHERY AS M
		ON DK.MENEDZHER_GUID=M.GUID
	INNER JOIN L1.dbo.KONTRAGENTY AS K
		ON DK.KONTRAGENT_GUID=K.GUID
	WHERE BASTY.OSTATOK>0
	AND [DATA_PO_GRAFIKU]>'2023'
	AND DK.MENEDZHER_GUID=@manager_guid
	--AND GID.DATA_PO_GRAFIKU BETWEEN CAST(GETDATE() AS DATE) AND  DATEADD (DD, 7, CAST(GETDATE() AS DATE)  )  
	AND DATEPART(WEEK,GID.DATA_PO_GRAFIKU) = @THIS_WEEK /*** OSY APTANIN TOLEU KEREK DOGOVORLARY***/
	ORDER BY GID.DATA_PO_GRAFIKU, S.NAIMENOVANIE DESC ,DK.NOMER 
END 