SELECT [ssylka] AS [GUID]
      ,[pometka_udaleniya] AS [POMETKA_UDALENIYA]
      ,[roditel] AS [RODITEL]
      ,[naimenovanie] AS [NAIMENOVANIE]
      ,[osnovnoy_menedzher] AS [OSNOVNOY_MENEDZHER]
      ,[geograficheskiy_region] AS [GEOGRAFICHESKIY_REGION]
      ,[sezonnaya_gruppa] AS [SEZONNAYA_GRUPPA]
      ,[kod_regiona] AS [KOD_REGIONA]
      ,[geograficheskaya_zona] AS [GEOGRAFICHESKAYA_ZONA]
      ,[c_r_m___vremya_po_grinvichu___g_m_t] AS [C_R_M___VREMYA_PO_GRINVICHU___G_M_T]
      ,[zona_komandirovki] AS [ZONA_KOMANDIROVKI]
      ,[oblast_dannykh_osnovnye_dannye] AS [OBLAST_DANNYKH_OSNOVNYE_DANNYE]
      ,CAST(GETDATE() AS DATE) A_DATE
  FROM [L0].[dbo].[biznes_regiony]