SELECT [ssylka] AS [GUID]
      ,[pometka_udaleniya] AS [POMETKA_UDALENIYA]
      ,DATEADD(YEAR, -2000, [data]) AS [DATA]
      ,[nomer] AS [NOMER]
      ,[proveden] AS [PROVEDEN]
      ,[avtor] AS [AVTOR_GUID]
      ,[dokument_osnovanie] AS [DOKUMENT_OSNOVANIE]
      ,[sotrudnik] AS [FIZICHESKOE_LITSO_GUID]
      ,[organizatsiya] AS [ORGANIZATSIYA_GUID]
      ,[podrazdelenie] AS [PODRAZDELENIE_GUID]
      ,[oblast_dannykh_osnovnye_dannye] AS [OBLAST_DANNYKH_OSNOVNYE_DANNYE]   
         ,CAST(GETDATE() AS DATE) A_DATE
FROM [L0].[dbo].[otchet_o_komandirovke]