SELECT dateadd(year,-2000,cast([period]as date))as[PERIOD]
      ,[synonym_registrator] as [SYNONYM_REGISTRATOR]
      ,[type_registrator] as [TYPE_REGISTRATOR]
      ,[registrator] as [REGISTRATOR]
      ,[nomer_stroki] as [NOMER_STROKI]
      ,[aktivnost] as [AKTIVNOST]
      ,[stsenariy] as [STSENARIY]
      ,[status] as [STATUS]
      ,[nomenklatura] as [NOMENKLATURA]
      ,[podrazdelenie] as [PODRAZDELENIE]
      ,[plan_prodazh] as [PLAN_PRODAZH]
      ,[menedzher] as [MENEDZHER]
      ,[kolichestvo] as [KOLICHESTVO]
      ,[summa] as [SUMMA]
  FROM [L0].[dbo].[plany_prodazh]