/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT [SOURCE_DATABASE]
      ,[PERIOD]
      ,[RECORDER_TYPE_SYNONYM]
      ,[RECORDER_NUMBER]
      ,[REGISTRATOR]
	  ,DK.NOMER
      ,CASE WHEN [SCHET_KT] IN('1210','3510') THEN RBH.[SUMMA]*(-1) ELSE RBH.[SUMMA] END 
	  ,RBH.[SUMMA]
	  ,O.NAIMENOVANIE
      ,[NOMER_STROKI]
      ,[SCHET_DT]
      ,[SCHET_KT]
      ,[ORGANIZACIYA]
      ,[VALYUTA_DT]
      ,[VALYUTA_KT]
      ,[PODRAZDELENIE_DT]
      ,[PODRAZDELENIE_KT]
      ,[NAPRAVLENIE_DEYATELNOSTI_DT]
      ,[NAPRAVLENIE_DEYATELNOSTI_KT]
      ,[VALYUTNAYA_SUMMA_DT]
      ,[VALYUTNAYA_SUMMA_KT]
      ,[KOLICHESTVO_DT]
      ,[KOLICHESTVO_KT]
      ,[SUMMA_NU_DT]
      ,[SUMMA_NU_KT]
      ,[SUMMA_PR_DT]
      ,[SUMMA_PR_KT]
      ,[SUMMA_VR_DT]
      ,[SUMMA_VR_KT]
      ,[SUMMS_UU]
      ,[SUMMS_FO]
      ,[SODERZHANIE]
      ,[NE_KORREKTIROVAT_STOIMOST_FVTOMATICHESKI]
      ,[OBLASTDANNYHOSNOVNYEDANNYE]
      ,[SUBCONTO_DT_1_TYPE]
      ,[SUBCONTO_DT_1_GUID]
      ,[SUBCONTO_DT_2_TYPE]
      ,[SUBCONTO_DT_2_GUID]
      ,[SUBCONTO_DT_3_TYPE]
      ,[SUBCONTO_DT_3_GUID]
      ,[SUBCONTO_CT_1_TYPE]
      ,[SUBCONTO_CT_1_GUID]
      ,[SUBCONTO_CT_2_TYPE]
      ,[SUBCONTO_CT_2_GUID]
      ,[SUBCONTO_CT_3_TYPE]
      ,[SUBCONTO_CT_3_GUID]
      ,[KASPI]
  FROM (SELECT * FROM [L1].[dbo].[REGISTR_BUHGALTERII_HOZRASCHETNYI] WHERE [SCHET_DT] IN ('1210','3510')OR [SCHET_KT] IN ('1210','3510'))RBH
LEFT JOIN L1.dbo.DOGOVORY_KONTRAGENTOV AS DK
		ON DK.GUID = CASE WHEN [SUBCONTO_DT_1_TYPE]='ДоговорыКонтрагентов' THEN [SUBCONTO_DT_1_GUID]
			WHEN [SUBCONTO_DT_2_TYPE]='ДоговорыКонтрагентов' THEN [SUBCONTO_DT_2_GUID]
			WHEN [SUBCONTO_DT_3_TYPE]='ДоговорыКонтрагентов' THEN [SUBCONTO_DT_3_GUID]
			WHEN [SUBCONTO_CT_1_TYPE]='ДоговорыКонтрагентов' THEN [SUBCONTO_CT_1_GUID]
			WHEN [SUBCONTO_CT_2_TYPE]='ДоговорыКонтрагентов' THEN [SUBCONTO_CT_2_GUID]
			WHEN [SUBCONTO_CT_3_TYPE]='ДоговорыКонтрагентов' THEN [SUBCONTO_CT_3_GUID]
		END
LEFT JOIN L1.dbo.KONTRAGENTY AS K
	ON K.GUID=CASE WHEN [SUBCONTO_DT_1_TYPE]='Контрагенты' THEN [SUBCONTO_DT_1_GUID]
					WHEN [SUBCONTO_DT_2_TYPE]='Контрагенты' THEN [SUBCONTO_DT_2_GUID]
					WHEN [SUBCONTO_DT_3_TYPE]='Контрагенты' THEN [SUBCONTO_DT_3_GUID]
					WHEN [SUBCONTO_CT_1_TYPE]='Контрагенты' THEN [SUBCONTO_CT_1_GUID]
					WHEN [SUBCONTO_CT_2_TYPE]='Контрагенты' THEN [SUBCONTO_CT_2_GUID]
					WHEN [SUBCONTO_CT_3_TYPE]='Контрагенты' THEN [SUBCONTO_CT_3_GUID]
				END
LEFT JOIN L1.dbo.ORGANIZATSII O ON RBH.ORGANIZACIYA=O.GUID
WHERE 1=1
--AND DK.NOMER='2310/02/09-17'
--AND K.NAIMENOVANIE ='ТОО "ЯССАН"'
ORDER BY RBH.ORGANIZACIYA