--CREATE VIEW PROSROCHKA_BAF AS 
WITH OPLATA AS (SELECT SUM(RSK_ALL.SUMMA) AS SUMMA_OPLAT
						,RSK_ALL.DOGOVOR_GUID
						,CAST(RSK_ALL.DATA_OPLATY_VOZVRATA AS DATE) AS DATA_OPLATY
				FROM [L1].[dbo].[RASCHETY_S_KLIENTAMI_PO_DOKUMENTAM] RSK_ALL
				WHERE RSK_ALL.TIP_DOKUMENTA 
				IN ( 'Корректировка реализации','Расчет курсовых разниц',
					'Приходный кассовый ордер','Списание задолженности',
					'Ввод начальных остатков','Поступление безналичных денежных средств',
					'Операция по платежной карте', 'Взаимозачет задолженности',
					'Списание безналичных денежных средств'
											)
				GROUP BY RSK_ALL.DOGOVOR_GUID
				,CAST(RSK_ALL.DATA_OPLATY_VOZVRATA AS DATE) 
					)



SELECT GID.[NOMER_DOGOVORA],
		DK.DATA AS DATA_DOGOVORA,
		K.NAIMENOVANIE AS KONTRAGENTY,
		K.IIN_BIN,
		K.GUID AS KONTRAGENTY_GUID,
       --DENSE_RANK() OVER (ORDER BY GID.[DOGOVOR_GUID]) ID_GUID,
       --DENSE_RANK() OVER (PARTITION BY GID.[DOGOVOR_GUID]
       --                   ORDER BY GID.[DOGOVOR_GUID],
       --                            [DATA_PO_GRAFIKU]
       --                  ) ID_GRAFIK,
       GID.[DOGOVOR_GUID],
	   DK.USLOVIYA_OPLATY ,
	   --CASE WHEN (SUM(GID.[SUMMA_OPLATY]) OVER(PARTITION BY GID.[DOGOVOR_GUID]) - ISNULL(SUMMA_OPLATALAR.SUMMA_SUM,0))>0 THEN 1 ELSE 0 END ,
       CAST([DATA_PO_GRAFIKU] AS DATE) AS [DATA_PO_GRAFIKU],
       GID.[SUMMA_OPLATY] AS SUMMA_GRAFIK,
       --GID_PREV.SUMMA_GRAFIKOV,
       --  PMT_ALL.DATA_OPLAYU,
       --RSK.DATA_OPLATY,
	   SUM(GID.[SUMMA_OPLATY]) OVER(PARTITION BY GID.[DOGOVOR_GUID]) - ISNULL(SUMMA_OPLATALAR.SUMMA_SUM,0) AS DOLG,
	   OPLATY_PREV.SUMMA_SUM AS OPLATY,
	   CASE WHEN GID.DATA_PO_GRAFIKU >= GETDATE() OR GID.DATA_PO_GRAFIKU >= RSK.DATA_OPLATY THEN 0
		   ELSE
		   COALESCE(
		   DATEDIFF("D", GID.DATA_PO_GRAFIKU, RSK.DATA_OPLATY),
		   DATEDIFF("D", GID.DATA_PO_GRAFIKU, GETDATE())
		   )
	   END AS DNI_PROSROCHKI,
	   CASE WHEN GID.DATA_PO_GRAFIKU >= GETDATE() OR GID_PREV.SUMMA_GRAFIKOV - ISNULL(OPLATY_PREV.SUMMA_SUM,0) <= 0 THEN 0 
			ELSE GID_PREV.SUMMA_GRAFIKOV - ISNULL(OPLATY_PREV.SUMMA_SUM,0) 
	   END AS SUMMA_PROSROCHKI

--INTO L1_X.dbo.PROSROCHKA_BAF_ANALIZ

FROM [L1].[dbo].[GRAFIK_ISPOLNENIYA_DOGOVORA] GID
    LEFT JOIN L1.dbo.DOGOVORY_KONTRAGENTOV AS DK
        ON GID.DOGOVOR_GUID = DK.GUID
    LEFT JOIN L1.dbo.KONTRAGENTY AS K
        ON DK.KONTRAGENT_GUID = K.GUID
    CROSS APPLY
(
    SELECT SUM(GP.SUMMA_OPLATY) AS SUMMA_GRAFIKOV
    FROM L1.dbo.GRAFIK_ISPOLNENIYA_DOGOVORA GP
    WHERE CAST(GP.DATA_PO_GRAFIKU AS DATE) <= CAST(GID.DATA_PO_GRAFIKU AS DATE)
          AND GID.DOGOVOR_GUID = GP.DOGOVOR_GUID
) GID_PREV
    CROSS APPLY
    (
        SELECT MIN([DATA_OPLATY]) AS DATA_OPLATY
        FROM OPLATA RSK
		CROSS APPLY ( SELECT SUM(RSK_ALL.SUMMA_OPLAT) AS SUMMA_OPLAT
					--,SUM([SUMMA])*(-1) AS [SUMMA]
					FROM OPLATA RSK_ALL
					WHERE 1=1
						  AND RSK_ALL.DOGOVOR_GUID = RSK.DOGOVOR_GUID
						  AND RSK_ALL.DATA_OPLATY <= RSK.DATA_OPLATY
					) PMT
		WHERE 1=1
		AND RSK.DOGOVOR_GUID = GID.DOGOVOR_GUID
		AND PMT.SUMMA_OPLAT >= GID_PREV.SUMMA_GRAFIKOV
		) RSK
--CROSS APPLY (SELECT SUM(GP.SUMMA_OPLATY) AS SUMMA_GRAFIKOV
--					FROM L1.dbo.GRAFIK_ISPOLNENIYA_DOGOVORA GP
--					WHERE CAST(GP.DATA_PO_GRAFIKU AS DATE) <= CAST(GID.DATA_PO_GRAFIKU AS DATE)
--						  AND GID.DOGOVOR_GUID = GP.DOGOVOR_GUID
--				)GID_SUM
CROSS APPLY (
			SELECT SUM(RSKD.SUMMA_OPLAT) AS SUMMA_SUM
			FROM OPLATA RSKD
			  WHERE 1=1
				AND RSKD.DOGOVOR_GUID=GID.DOGOVOR_GUID
				AND CAST(GID.DATA_PO_GRAFIKU AS DATE)>=RSKD.DATA_OPLATY
			)OPLATY_PREV

CROSS APPLY (SELECT SUM(RSKD.SUMMA_OPLAT) AS SUMMA_SUM
			 FROM OPLATA RSKD
			  WHERE 1=1
			  AND RSKD.DOGOVOR_GUID=GID.DOGOVOR_GUID
				) SUMMA_OPLATALAR

WHERE 1 = 1
      --AND K.NAIMENOVANIE=@kontragent
      --AND DK.KONTRAGENT_GUID = @KONTRAGENT_GUID
      AND GID.TIP_DOGOVORA = 'С покупателем / заказчиком'
      AND GID.STATUS = 'Действует'
	--AND DOGOVOR_GUID=0x80B900155D01C90111E73EBBE8BF5218

--ORDER BY K.NAIMENOVANIE,DOGOVOR_GUID,
--         GID.DATA_PO_GRAFIKU,
--         RSK.DATA_OPLATY