USE CRM_DWH;
GO
CREATE PROCEDURE [BAF_12M_CONTRACTS] AS
DECLARE @IIN_BIN NVARCHAR(12);
--WHERE CAST(PB.DATA_DOGOVORA AS DATE) > CAST(DATEADD(year, -1, GETDATE()) AS DATE)
WITH DIST AS (
SELECT [KONTRAGENTY_GUID], COUNT([DOGOVOR_GUID]) COUNT_DOGOVOR ,SUM(SUMMA_DOGOVORA) AS SUMMA_DOGOVORA  FROM (
SELECT DISTINCT [KONTRAGENTY_GUID] 
			  ,[DOGOVOR_GUID]
			  ,SUM([SUMMA_GRAFIK]) AS SUMMA_DOGOVORA
			  FROM [L1_X].[dbo].[PROSROCHKA_BAF_ANALIZ]
			  WHERE CAST(DATA_DOGOVORA AS DATE) > CAST(DATEADD(year, -1, GETDATE()) AS DATE)
			  GROUP BY[KONTRAGENTY_GUID] 
			  ,[DOGOVOR_GUID]
			  )A GROUP BY [KONTRAGENTY_GUID]
			  )
,PROVERKA AS (SELECT PB.*,ROW_NUMBER()OVER (PARTITION BY KONTRAGENTY ORDER BY SUMMA_PROSROCHKI DESC) AS rn_SUMMA
		,ROW_NUMBER() OVER (PARTITION BY KONTRAGENTY ORDER BY DNI_PROSROCHKI DESC) AS rn_DNI FROM [L1_X].[dbo].[PROSROCHKA_BAF_ANALIZ] AS PB
		WHERE CAST(DATA_DOGOVORA AS DATE) > CAST(DATEADD(year, -1, GETDATE()) AS DATE)
		)
SELECT 
      DISTINCT [KONTRAGENTY]
      ,[IIN_BIN]
      ,PBA.[KONTRAGENTY_GUID]
	  ,DIST.COUNT_DOGOVOR AS [Общее кол-во]
	  ,DIST.SUMMA_DOGOVORA AS [Общая сумма]
	  ,MAX(PBA.[SUMMA_PROSROCHKI])OVER (PARTITION BY PBA.[KONTRAGENTY_GUID]) [Макс. сумма просрочки],
	SRN.DNI_PROSROCHKI AS [Макс. кол-во дней просрочки по макс. сумме просроченной задолженности],
    MAX(CASE WHEN PBA.DNI_PROSROCHKI > 0 THEN PBA.DNI_PROSROCHKI END) OVER (PARTITION BY PBA.[KONTRAGENTY_GUID]) AS [Максимальное количество дней просрочки],
	DRN.[SUMMA_PROSROCHKI] AS [Сумма по макс. кол-ву дней просрочки]
  FROM PROVERKA AS PBA
  LEFT JOIN DIST AS DIST ON PBA.[KONTRAGENTY_GUID]= DIST.[KONTRAGENTY_GUID]
LEFT JOIN (SELECT DNI_PROSROCHKI, [KONTRAGENTY_GUID]FROM PROVERKA WHERE rn_SUMMA=1
)AS SRN ON SRN.[KONTRAGENTY_GUID]=PBA.[KONTRAGENTY_GUID]
LEFT JOIN (SELECT [SUMMA_PROSROCHKI], [KONTRAGENTY_GUID]FROM PROVERKA WHERE rn_DNI=1
)AS DRN ON DRN.[KONTRAGENTY_GUID]=PBA.[KONTRAGENTY_GUID]
WHERE IIN_BIN=@IIN_BIN
  ORDER BY  PBA.[KONTRAGENTY_GUID]