USE CRM_DWH;
GO
CREATE PROCEDURE [CURRENT_CONTRACTS] AS
DECLARE @IIN_BIN NVARCHAR(12);
SELECT DISTINCT
    [KONTRAGENTY],
    [IIN_BIN],
    [KONTRAGENTY_GUID],
    COUNT(CASE WHEN [DOLG] > 0 THEN [DOGOVOR_GUID] END) OVER (PARTITION BY [KONTRAGENTY_GUID]) AS [Общее кол-во]
	,(SELECT SUM(DISTINCT SPB.[DOLG]) AS SUM_DOLG FROM [L1_X].[dbo].[PROSROCHKA_BAF] AS SPB WHERE PB.[KONTRAGENTY_GUID]=SPB.[KONTRAGENTY_GUID] AND SPB.[DOLG]>0 GROUP BY SPB.[KONTRAGENTY_GUID])[Общая сумма задолженности],
	  --,
   -- SUM(CASE WHEN [DOLG] > 0 THEN [DOLG] END) OVER (PARTITION BY [KONTRAGENTY_GUID]) AS [Общая сумма задолженности],
    COUNT(CASE WHEN [DOLG] > 0 AND DNI_PROSROCHKI > 0 THEN [DOGOVOR_GUID] END) OVER (PARTITION BY [KONTRAGENTY_GUID]) AS [Кол-во просроченных],
    SUM(CASE WHEN [DOLG] > 0 AND DNI_PROSROCHKI > 0 THEN [SUMMA_PROSROCHKI] END) OVER (PARTITION BY [KONTRAGENTY_GUID]) AS [Общая сумма задолженности по просроченным],
    MAX(CASE WHEN [DOLG] > 0 AND DNI_PROSROCHKI > 0 THEN DNI_PROSROCHKI END) OVER (PARTITION BY [KONTRAGENTY_GUID]) AS [Максимальное количество дней просрочки]
FROM [L1_X].[dbo].[PROSROCHKA_BAF] PB

WHERE IIN_BIN=@IIN_BIN
ORDER BY [KONTRAGENTY_GUID];