USE CRM_DWH;
GO
CREATE PROCEDURE [BAF_LATEST_CONTRACT]  @IIN_BIN NVARCHAR(12) AS
WITH MIN_CONTRAC AS (
SELECT PB.*,ROW_NUMBER()OVER (PARTITION BY KONTRAGENTY ORDER BY SUMMA_PROSROCHKI DESC) AS rn_SUMMA
		,ROW_NUMBER() OVER (PARTITION BY KONTRAGENTY ORDER BY DNI_PROSROCHKI DESC) AS rn_DNI
FROM [L1_X].[dbo].[PROSROCHKA_BAF_ANALIZ] PB
JOIN (SELECT [KONTRAGENTY_GUID],MAX(DATA_DOGOVORA) AS DATA_DOGOVORA FROM [L1_X].[dbo].[PROSROCHKA_BAF_ANALIZ] GROUP BY[KONTRAGENTY_GUID])
AS MAX_CONTRACT ON PB.[KONTRAGENTY_GUID]=MAX_CONTRACT.[KONTRAGENTY_GUID] AND MAX_CONTRACT.DATA_DOGOVORA=PB.DATA_DOGOVORA
--ORDER BY [KONTRAGENTY_GUID]
)


SELECT DISTINCT
    MIN_CONTRAC.[KONTRAGENTY],
    MIN_CONTRAC.[IIN_BIN],
    MIN_CONTRAC.[KONTRAGENTY_GUID],
	MIN_CONTRAC.DATA_DOGOVORA,
	MIN_CONTRAC.USLOVIYA_OPLATY,
	SUM(MIN_CONTRAC.[SUMMA_GRAFIK]) OVER(PARTITION BY MIN_CONTRAC.[KONTRAGENTY_GUID])AS [Сумма],
	MAX(MIN_CONTRAC.[SUMMA_PROSROCHKI])OVER (PARTITION BY MIN_CONTRAC.[KONTRAGENTY_GUID]) [Макс. сумма просрочки],
	SRN.DNI_PROSROCHKI AS [Макс. кол-во дней просрочки по макс. сумме просроченной задолженности],
    MAX(CASE WHEN MIN_CONTRAC.DNI_PROSROCHKI > 0 THEN MIN_CONTRAC.DNI_PROSROCHKI END) OVER (PARTITION BY MIN_CONTRAC.[KONTRAGENTY_GUID]) AS [Максимальное количество дней просрочки],
	DRN.[SUMMA_PROSROCHKI] AS [Сумма по макс. кол-ву дней просрочки]
FROM MIN_CONTRAC
LEFT JOIN (SELECT DNI_PROSROCHKI, [KONTRAGENTY_GUID]FROM MIN_CONTRAC WHERE rn_SUMMA=1
)AS SRN ON SRN.[KONTRAGENTY_GUID]=MIN_CONTRAC.[KONTRAGENTY_GUID]
LEFT JOIN (SELECT [SUMMA_PROSROCHKI], [KONTRAGENTY_GUID]FROM MIN_CONTRAC WHERE rn_DNI=1
)AS DRN ON DRN.[KONTRAGENTY_GUID]=MIN_CONTRAC.[KONTRAGENTY_GUID]

WHERE IIN_BIN=@IIN_BIN

ORDER BY [KONTRAGENTY_GUID];