/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT TOP (1000) [nomenklatura_guid]
      ,[direksiya]
      ,[Компании]
      ,[Культура]
      ,[Регион]
      ,[Название продукта]
      ,[Технология]
      ,[Подтверждение]
      ,[Продано]
	  ,0 AS [Остаток]
      ,[Отгружено]
      ,[Не отгружено]
      ,[Стоки 2021]
      ,[Поступление]
into [CRM_DWH].[dbo].[2_SEMENA_TEST]
 delete FROM [CRM_DWH].[dbo].[SEMENA_TEST]