/****** ƒŒœ –¿—’Œƒ€ ******/
WITH RASXODY AS (SELECT 
      SUM([SUMMA]) [SUMMA]
      ,[ANALITIKA_RASKHODOV]
FROM [L0].[DBO].[TAB_RASKHODY_PRIOBRETENIEUSLUGPROCHIKHAKTIVOV] TRP
LEFT JOIN [L0].[DBO].[PRIOBRETENIE_USLUG_PROCHIKH_AKTIVOV] PTU ON TRP.SSYLKA=PTU.SSYLKA
WHERE 1=1 
AND PTU.PROVEDEN=0X01
  AND TRP.STATYA_RASKHODOV IN (0X970000155D01C90111E7169631979771,
								0XAF8DD4F5EF10792511EC7F546263ED9C,
								0X80DE000C29E67B2E11E628A464E5C16A,
								0X80D3000C2910767B11E5E125C0C80DD8,
								0XA23F00155D01C80911E9F159B283211F,
								0XA2187085C2A4312A11E9B51E5096E963,
								0XA21B7085C2A4312A11E9BA6FAE16B1EB,
								0XA2307085C2A4312A11EADB8940929075,
								0XA23F00155D01C80911E9F15A50BDC23B )
GROUP BY [ANALITIKA_RASKHODOV]
)


SELECT DATEADD(YEAR, -2000,Z.[PERIOD]) AS [PERIOD]
	  ,Z.istochnik_g_f_u_nomenklatury AS [NOMENKLATURA_GUID]
	  
	  ,Z.DOGOVOR AS DOGOVOR_GUID
	  --,[TAMOZHENNAYA_STOIMOST]
      ,CASE WHEN [SUMMA_POSHLINY] IS NULL THEN 0 
			ELSE [SUMMA_POSHLINY] 
		END AS [SUMMA_POSHLINY]
	  ,V.naimenovanie AS valyuta_vzaimoraschetov
	  ,Z.summa_v_valyute_vzaimoraschetov AS SUMMA_ZAKUPA
	  ,Z.SUMMA AS SUMMA_KZT
	  ,Z.[KOLICHESTVO]
	  --,TRP.SUMMA / SUM(Z.[KOLICHESTVO]) OVER (PARTITION BY [REGISTRATOR]) AS [DOP_RASXODI_/_KOLICHESTVO_NOMEENKLATUR]
	  ,CASE WHEN ((TRP.SUMMA / SUM(Z.[KOLICHESTVO]) OVER (PARTITION BY [REGISTRATOR])) * Z.[KOLICHESTVO])IS NULL THEN 0 
		ELSE (TRP.SUMMA / SUM(Z.[KOLICHESTVO]) OVER (PARTITION BY [REGISTRATOR])) * Z.[KOLICHESTVO] END AS [DOP_RASXODI_NOMEENKLATUR]
	  --,CAST(ROUND(([TAMOZHENNAYA_STOIMOST] + [SUMMA_POSHLINY] + Z.SUMMA + ((TRP.SUMMA / SUM(Z.[KOLICHESTVO]) OVER (PARTITION BY [REGISTRATOR])) * Z.[KOLICHESTVO]))/Z.[KOLICHESTVO],2) AS NUMERIC(12,2)) AS SEBE_STOIMOST_S_TAMOZHENNAYA_STOIMOSTIOU
	  
/****** –¿—◊≈“»‹ —≈¡—“Œ»ÃŒ—“» = ((“¿ÃŒ∆Õ œŒÿÀ»Õ¿ + ƒŒœ –¿—’Œƒ€ + «¿ ”œ ) / «¿ ”œ  ŒÀ»◊≈—“¬Œ)  ******/
	  ,CAST(ROUND((CASE WHEN [SUMMA_POSHLINY] IS NULL THEN 0 
						ELSE [SUMMA_POSHLINY] 
					END  + Z.SUMMA + (CASE WHEN ((TRP.SUMMA / SUM(Z.[KOLICHESTVO]) OVER (PARTITION BY [REGISTRATOR])) * Z.[KOLICHESTVO]) IS NULL THEN 0 
											ELSE (TRP.SUMMA / SUM(Z.[KOLICHESTVO]) OVER (PARTITION BY [REGISTRATOR])) * Z.[KOLICHESTVO] END)
									   )/Z.[KOLICHESTVO],2) AS NUMERIC(12,2)) AS SEBESTOIMOST

--INTO L1.DBO.SEBESTOIMOST_ZAKUP
  FROM [L0].[DBO].[ZAKUPKI] Z
LEFT JOIN [L0].[DBO].[TAMOZHENNAYA_DEKLARATSIYA_IMPORT] AS TDI
	ON TDI.ANALITIKA_RASKHODOV_SBOR=Z.REGISTRATOR
LEFT JOIN [L0].[DBO].[TAB_TOVARY_TAMOZHENNAYADEKLARATSIYAIMPORT] AS TTDI 
	ON TDI.[SSYLKA]=TTDI.[SSYLKA] AND TTDI.NOMENKLATURA=Z.ISTOCHNIK_G_F_U_NOMENKLATURY
LEFT JOIN RASXODY TRP 
	ON Z.REGISTRATOR=TRP.ANALITIKA_RASKHODOV
LEFT JOIN L0.DBO.valyuty V
	ON Z.valyuta_vzaimoraschetov=V.ssylka

WHERE 1=1
AND  Z.kolichestvo<>0
AND Z.ORGANIZATSIYA=0X80DE000C29E67B2E11E636A5C3C5D8AE
--AND Z.dogovor=0x970000155D01C90111E712DD760A14A0
  --ORDER BY [SUMMA_POSHLINY],Z.PERIOD, Z.kolichestvo,Z.istochnik_g_f_u_nomenklatury