WITH DOGOVOR AS(
SELECT DISTINCT
   RSP.[PERIOD]
  ,[SYNONYM_REGISTRATOR]
  ,RSP.[DOGOVOR_GUID]
FROM [L1].[dbo].[RASCHETY_S_POSTAVSHCHIKAMI]RSP
  LEFT JOIN L1.DBO.SPETSIFIKATSIYA_PO_DOGOVORU SPD
    ON RSP.DOGOVOR_GUID=SPD.DOGOVOR_GUID
  LEFT JOIN L1.DBO.NOMENKLATURA N 
    ON SPD.NOMENKLATURA_GUID=N.GUID
WHERE [SYNONYM_REGISTRATOR] IN ('Приобретение товаров и услуг','Списание безналичных денежных средств','Расходный кассовый ордер')
  AND N.RODITEL2 IN ('СЗР','Семена','Удобрения')
)
,avans as (
SELECT 
   DISTINCT DOGOVOR_GUID
  ,SYNONYM_REGISTRATOR
  ,PERIOD 
  ,ROW_NUMBER() over(partition by [DOGOVOR_GUID] order by [PERIOD]) ROW_NUMBER_DOGOVOR
  ,ROW_NUMBER() over(partition by [DOGOVOR_GUID],[SYNONYM_REGISTRATOR] order by [PERIOD]) ROW_NUMBER_DOGOVOR_SYNONYM_REGISTRATOR
FROM dogovor
--WHERE DOGOVOR_GUID IN (0xAF8ED4F5EF10792511ECAFE6C230E06F,0xAF8ED4F5EF10792511EC9898A09349FE)
--ORDER BY DOGOVOR_GUID,PERIOD
)
,OPLATA AS (
SELECT 
   A.PERIOD
  ,A.DOGOVOR_GUID
  ,SYNONYM_REGISTRATOR
  ,CASE 
     WHEN A.ROW_NUMBER_DOGOVOR=ROW_NUMBER_DOGOVOR_SYNONYM_REGISTRATOR 
	  AND SYNONYM_REGISTRATOR!='Приобретение товаров и услуг' 
	   THEN 'Аванс' 
	 ELSE 'Оплата' 
   END AS AVANS
FROM avans A
WHERE SYNONYM_REGISTRATOR!='Приобретение товаров и услуг'
--ORDER BY ID_DOGOVOR,DATA
)

SELECT 
   RSP.[PERIOD]
  ,RSP.[SYNONYM_REGISTRATOR]
  ,CONVERT(nvarchar(50), RSP.[DOGOVOR_GUID], 1) AS [DOGOVOR_GUID]
  ,CASE
	 WHEN RSP.SYNONYM_REGISTRATOR = 'Взаимозачет задолженности' 
	   THEN 'Оплата'
     ELSE A.AVANS
   END AS AVANS
  ,RSP.[SUMMA]
  ,CONVERT(NUMERIC(15,2),ISNULL(RSP.[SUMMA]*KVA.KURS,RSP.[SUMMA]),1)[SUMMA]
  ,CONVERT(nvarchar(50), [TYPE_REGISTRATOR], 1) AS [TYPE_REGISTRATOR]
  ,CONVERT(nvarchar(50), [REGISTRATOR_GUID], 1) AS [REGISTRATOR_GUID]
  ,[NOMER_STROKI]
  ,CONVERT(nvarchar(50), [AKTIVNOST], 1) AS [AKTIVNOST]
FROM [L1].[dbo].[RASCHETY_S_POSTAVSHCHIKAMI] RSP
  LEFT JOIN OPLATA A 
    ON RSP.DOGOVOR_GUID=A.DOGOVOR_GUID
      AND RSP.PERIOD=A.PERIOD
      AND RSP.[SYNONYM_REGISTRATOR]=A.SYNONYM_REGISTRATOR
LEFT JOIN L1.DBO.KURSY_VALYUT_ALL KVA 
	ON KVA.VALYUTA_GUID=RSP.VALYUTA_GUID
	AND CAST(RSP.PERIOD AS DATE)=KVA.PERIOD
WHERE RSP.[SYNONYM_REGISTRATOR] != 'Приобретение товаров и услуг'
  --AND RSP.DOGOVOR_GUID = 0xA2337085C2A4312A11EB24AA989BDFC2
ORDER BY 
   RSP.[SYNONYM_REGISTRATOR] 
   ,AVANS
  ,RSP.[SUMMA]
  ,DOGOVOR_GUID
  ,PERIOD desc