/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT DK.[GUID]
,DK.[SUMMA]
,K.NAIMENOVANIE

,N.NAIMENOVANIE
,SPD.NOMENKLATURA_GUID
      ,[AVTOSOGLASOVANIE]
      ,[VALYUTA_VZAIMORASCHETOV]
      ,[STATUS_PODPISANIYA]
      ,[TIP_DOGOVORA]
      ,[STATUS]
      ,DK.[NAIMENOVANIE]
      ,[DOGOVOR_VNUTRI_GRUPPY]
      ,[DATA_NACHALA_DEYSTVIYA]
      ,[DATA_OKONCHANIYA_DEYSTVIYA]
      ,[DATA]
      ,[NOMER]
      ,[SOGLASOVAN]
      ,[ORGANIZATSIYA_GUID]
      ,[KONTRAGENT_GUID]
      ,[MENEDZHER_GUID]
      ,[BIZNES_REGION_GUID]
      ,[STRUKTURA_PREDPRIYATIYA_GUID]
      ,[SEZON_GUID]
      ,[SKLAD_GUID]
      ,DK.[SUMMA]
      ,[PROGRAMMA_DOGOVORA]
      ,[STAVKA_NDS]
      ,[STAVKA_NSP]
      ,[VIDSTAVKI_NDS]
      ,[BEZNALICHNYY_RASCHET]
      ,[USLOVIYA_OPLATY]
      ,DK.[SOURCE_BASE]
      ,[AGENT_PARTNER_GUID]
      ,[PROTSENT_AGENTSKIKH]
      ,[SUMMA_AGENTSKIKH]
      ,[ZAKAZ_KLIENTA_GUID]
      ,[SPOSOB_DOSTAVKI]
      ,[adres_dostavki]
      ,[SOSTOYANIE]
      ,[STANDARTNYE_USLOVIYA_ZAKLYUCHENIYA]
      ,DK.[SUMMA_KZ_TG]
	  ,SPD.*
  FROM [L1].[dbo].[DOGOVORY_KONTRAGENTOV]DK
  left join L1.DBO.SPETSIFIKATSIYA_PO_DOGOVORU SPD 
	ON SPD.DOGOVOR_GUID=DK.GUID
left join l1.dbo.KONTRAGENTY k 
	on	DK.KONTRAGENT_GUID=K.GUID
left join L1.DBO.NOMENKLATURA N  
	ON SPD.NOMENKLATURA_GUID=N.GUID
  where 1=1
 and dk.TIP_DOGOVORA<>'С покупателем / заказчиком'
 AND DK.NAIMENOVANIE LIKE '%Договор №: DCP- 12/22 от 05.05.2022%'
 --AND DK.GUID=0x810E000C29EF79CA11E8F7D5FF5A399C
  --spd.tsena
  --and NAIMENOVANIE like '%АЛМ-51%'
  --AND NOMENKLATURA_GUID=0x99D40021856269C211E3F069BD0170A4