/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT --[period]
K.NAIMENOVANIE
,N.NAIMENOVANIE
      ,SUM([kolichestvo])[kolichestvo]
      ,SUM([summa])[summa]
      --,[synonym_registrator]
      --,[type_registrator]
      --,[registrator]
      --,[nomer_stroki]
      --,[aktivnost]
      --,[khozyaystvennaya_operatsiya]
      --,[organizatsiya]
      --,[podrazdelenie]
      --,[menedzher]
      --,[analitika_ucheta_nomenklatury]
      --,[synonym_sklad]
      --,[type_sklad]
      --,[sklad]
      --,[tip_zapasov]
      --,[vid_zapasov]
      --,[partner]
      --,[synonym_kontragent]
      --,[type_kontragent]
      --,[kontragent]
      --,[soglashenie]
      --,[synonym_dogovor]
      --,[type_dogovor]
      ,[dogovor]
      --,[synonym_zakaz]
      --,[type_zakaz]
      --,[zakaz]
      --,[napravlenie_deyatelnosti_nomenklatury]
      --,[napravlenie_deyatelnosti_kontragenta]
      --,[podotchetnoe_litso]
      --,[summa_bez_n_d_s]
      --,[summa_regl]
      --,[summa_regl_bez_n_d_s]
      --,[summa_skidki]
      --,[stoimost]
      --,[stoimost_bez_n_d_s]
      --,[stoimost_regl]
      --,[summa_dop_raskhodov]
      --,[summa_dop_raskhodov_bez_n_d_s]
      --,[valyuta_dokumenta]
      --,[summa_v_valyute_dokumenta]
      --,[summa_bez_n_d_s_v_valyute_dokumenta]
      --,[valyuta_vzaimoraschetov]
      --,[summa_v_valyute_vzaimoraschetov]
      --,[summa_bez_n_d_s_v_valyute_vzaimoraschetov]
      --,[synonym_istochnik_g_f_u_nomenklatury]
      --,[type_istochnik_g_f_u_nomenklatury]
      --,[istochnik_g_f_u_nomenklatury]
      --,[synonym_istochnik_g_f_u_raschetov]
      --,[type_istochnik_g_f_u_raschetov]
      --,[istochnik_g_f_u_raschetov]
      --,[synonym_dokument_dvizheniya]
      --,[type_dokument_dvizheniya]
      --,[dokument_dvizheniya]
      --,[raschet_sebestoimosti]
      --,[oblast_dannykh_osnovnye_dannye]
  FROM [L0].[dbo].[zakupki]Z
  LEFT JOIN L1.DBO.KONTRAGENTY K 
	ON Z.kontragent=K.GUID
LEFT JOIN L1.DBO.NOMENKLATURA N 
	ON Z.istochnik_g_f_u_nomenklatury=N.GUID
WHERE K.NAIMENOVANIE LIKE '%сИНГЕНТА%'
GROUP BY K.NAIMENOVANIE
,N.NAIMENOVANIE
,[dogovor]
ORDER BY N.NAIMENOVANIE