WITH KADRRRR AS (
				SELECT MAX([PERIOD])[PERIOD] 
				  ,[FIZICHESKOE_LITSO_GUID]
				FROM [L1].[dbo].[KADROVAYA_ISTORIYA_SOTRUDNIKOV] AS KIS
					LEFT JOIN L1.dbo.STRUKTURA_PREDPRIYATIYA SP
				ON SP.GUID = KIS.STRUKTURA_PREDPRIYATIYA_GUID
				  --WHERE FIZICHESKOE_LITSO_GUID=0xA2137085C2A4312A11E9A92404B92546
				GROUP BY [FIZICHESKOE_LITSO_GUID]
			  )
,DIREKSIA_ROKOVODITELI AS (

		SELECT DISTINCT
		FL.NAIMENOVANIE AS RUKOVODITELI
		--,SP.naimenovanie AS SP
		--,SP1.naimenovanie AS SP1
		--,SP2.naimenovanie AS SP2
		--,ISNULL(SP2.naimenovanie,ISNULL(SP1.naimenovanie,SP.naimenovanie))
		--,ISNULL(SP2.naimenovanie,ISNULL(SP1.naimenovanie,SP.naimenovanie)) DIREKSYA--='Головной офис' THEN SP.naimenovanie ELSE ISNULL(SP2.naimenovanie,ISNULL(SP1.naimenovanie,SP.naimenovanie)) END AS DIREKSYA
		,sp.NAIMENOVANIE AS STRUKTURA_PRED
		  FROM [L1].[dbo].[struktura_predpriyatiya] AS SP
		  --LEFT JOIN [L0].[dbo].[struktura_predpriyatiya] AS SP1
		  --ON SP.roditel=SP1.ssilka
		  --LEFT JOIN [L0].[dbo].[struktura_predpriyatiya] AS SP2
		  --ON SP1.roditel=SP2.ssilka
		  LEFT JOIN L1.DBO.FIZICHESKIE_LITSA AS FL
		  ON SP.TEKUSHCHIY_RUKOVODITEL=FL.GUID
		--WHERE ISNULL(SP2.naimenovanie,ISNULL(SP1.naimenovanie,SP.naimenovanie)) IN ('ВКО','Павлодар','Центральная дирекция','Северная дирекция','Западная дирекция','Южная дирекция','Головной офис')
		WHERE  FL.NAIMENOVANIE IS NOT NULL

		--ORDER BY FL.NAIMENOVANIE


	)



SELECT DISTINCT
  M.[GUID]
 ,M.NAIMENOVANIE
 ,sp.DIREKSYA AS DIREKTSYA
 ,DR.RUKOVODITELI AS RUKOVODITELI_DIREKTSYI
 ,CD.CRM_CATO
 ,D.NAIMENOVANIE AS DOLZHNOST
 ,M.ADRES_E_P
 --,KIFL.[NOMER_TELEFONA] AS TELEFON
 ,M.TELEGRAM_ID
 ,M.FIZICHESKOE_LITSO_GUID
 ,SP.NAIMENOVANIE AS PODRAZDELENIE
 ,FL.I_I_N

 --INTO [CRM_DWH].[dbo].[CRM_USERS_2]
FROM KADRRRR 
  LEFT JOIN L1.dbo.KADROVAYA_ISTORIYA_SOTRUDNIKOV KIS
    ON KIS.FIZICHESKOE_LITSO_GUID = KADRRRR.FIZICHESKOE_LITSO_GUID
	AND KIS.PERIOD=KADRRRR.PERIOD
  LEFT JOIN L1.dbo.FIZICHESKIE_LITSA FL
	ON KIS.FIZICHESKOE_LITSO_GUID=FL.GUID
  LEFT JOIN [L1].[dbo].[MENEDZHERY] M
    ON KIS.FIZICHESKOE_LITSO_GUID= M.FIZICHESKOE_LITSO_GUID
  LEFT JOIN L1.dbo.DOLZHNOSTI D
    ON D.GUID = KIS.DOLZHNOST_GUID
  LEFT JOIN L1.dbo.STRUKTURA_PREDPRIYATIYA SP
    ON SP.GUID = KIS.STRUKTURA_PREDPRIYATIYA_GUID
  LEFT JOIN L1.dbo.KONTAKTNAYA_INFORMATSIYA_FIZICHESKIELITSA KIFL
    ON KIFL.SSYLKA = FL.GUID
  LEFT JOIN CRM_DWH.dbo.CRM_DIREKTSYA CD
    ON CD.NAME = ISNULL(SP.RODITEL2, ISNULL(SP.RODITEL, SP.NAIMENOVANIE))
  LEFT JOIN DIREKSIA_ROKOVODITELI DR
	ON SP.DIREKSYA=DR.STRUKTURA_PRED
	WHERE M.GUID IS NOT NULL
	AND KIS.VIDSOBYTIYA!='Увольнение'
	ORDER BY M.NAIMENOVANIE