/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/



WITH 
SKLAD_INFO AS
(
   SELECT
    ADRES_SKLADA
   ,GUID
   FROM L1.DBO.SKLADY 
   WHERE ADRES_SKLADA IS NOT NULL
)
--INSERT CRM_DWH.dbo.KOORDINATY_KONTRAGENTA
SELECT *,NULL AS [TO_LONGITUDE] 
	,NULL AS [TO_LATITUDE]
	,NULL AS [FROM_LONGITUDE]
	,NULL AS [FROM_LATITUDE] 
	,GETDATE() AS GETDATE
FROM
(
SELECT 
   DOGOVORY.[GUID]
  ,DOGOVORY.[NAIMENOVANIE]
  ,MENEDZHER.NAIMENOVANIE AS MENEDZHER
  ,SEZON.NAIMENOVANIE AS SEZON
  ,DOGOVORY.SEZON_GUID
  ,DOGOVORY.[NOMER]
  ,SPETSIFIKATSIYA.[DATA_OTGRUZKI] 
  ,DOGOVORY.[DATA_NACHALA_DEYSTVIYA]
  ,DOGOVORY.[DATA_OKONCHANIYA_DEYSTVIYA]
  ,DOGOVORY.[DATA]
  ,SUM(SPETSIFIKATSIYA.[SUMMA])[SUMMA]
  ,SUM(SPETSIFIKATSIYA.KOLICHESTVO)KOLICHESTVO
  ,DOGOVORY.[TIP_DOGOVORA] 
  ,DOGOVORY.[USLOVIYA_OPLATY]
  ,DOGOVORY.[SPOSOB_DOSTAVKI]
  ,DOGOVORY.[ADRES_DOSTAVKI]
  ,SPETSIFIKATSIYA.SKLAD_OTGRUZKI
  ,SPETSIFIKATSIYA.SKLAD_OTGRUZKI_GUID
  ,SKLAD_INFO.ADRES_SKLADA
 -- ,NULL AS [TO_LONGITUDE] 
	--,NULL AS [TO_LATITUDE]
	--,NULL AS [FROM_LONGITUDE]
	--,NULL AS [FROM_LATITUDE] 
--INTO CRM_DWH.dbo.KOORDINATY_KONTRAGENTA
FROM [L1].[dbo].[DOGOVORY_KONTRAGENTOV] DOGOVORY
  LEFT JOIN L1.dbo.SPETSIFIKATSIYA_PO_DOGOVORU SPETSIFIKATSIYA
    ON SPETSIFIKATSIYA.DOGOVOR_GUID = DOGOVORY.GUID
  LEFT JOIN L1.dbo.SEZONY SEZON
    ON SEZON.GUID = DOGOVORY.SEZON_GUID
  LEFT JOIN SKLAD_INFO 
    ON SKLAD_INFO.GUID= SPETSIFIKATSIYA.SKLAD_OTGRUZKI_GUID
  LEFT JOIN L1.dbo.ORGANIZATSII ORGANIZATSII
    ON ORGANIZATSII.GUID = DOGOVORY.ORGANIZATSIYA_GUID
  LEFT JOIN L1.DBO.SEZONY S 
	ON S.GUID=DOGOVORY.SEZON_GUID
  LEFT JOIN L1.dbo.MENEDZHERY MENEDZHER
    ON MENEDZHER.GUID = DOGOVORY.MENEDZHER_GUID
WHERE CAST(DOGOVORY.DATA AS date) BETWEEN DATEADD(month, -3, CAST( GETDATE() AS Date)) AND DATEADD(month, 3, CAST( GETDATE() AS Date))
  AND DOGOVORY.TIP_DOGOVORA = 'С покупателем / заказчиком'
  AND ORGANIZATSII.NAIMENOVANIE = 'ТОО «Alem Agro Holding (АлемАгро Холдинг)»' 
  AND S.NAIMENOVANIE>='Сезон 2022'
GROUP BY 
   DOGOVORY.[GUID]
  ,DOGOVORY.[NAIMENOVANIE]
  ,MENEDZHER.NAIMENOVANIE
  ,SEZON.NAIMENOVANIE
  ,DOGOVORY.SEZON_GUID
  ,DOGOVORY.[NOMER]
  --,SPETSIFIKATSIYA.[DATA_OTGRUZKI] 
  ,DOGOVORY.[DATA_NACHALA_DEYSTVIYA]
  ,DOGOVORY.[DATA_OKONCHANIYA_DEYSTVIYA]
  ,DOGOVORY.[DATA]
  ,SPETSIFIKATSIYA.DATA_OTGRUZKI
  ,DOGOVORY.[TIP_DOGOVORA] 
  ,DOGOVORY.[USLOVIYA_OPLATY]
  ,DOGOVORY.[SPOSOB_DOSTAVKI]
  ,DOGOVORY.[ADRES_DOSTAVKI]
  ,SPETSIFIKATSIYA.SKLAD_OTGRUZKI
  ,SPETSIFIKATSIYA.SKLAD_OTGRUZKI_GUID
  ,SKLAD_INFO.ADRES_SKLADA

  except


SELECT [GUID]
      ,[NAIMENOVANIE]
      ,[MENEDZHER]
      ,[SEZON]
      ,[SEZON_GUID]
      ,[NOMER]
      ,[DATA_OTGRUZKI]
      ,[DATA_NACHALA_DEYSTVIYA]
      ,[DATA_OKONCHANIYA_DEYSTVIYA]
      ,[DATA]
      ,[SUMMA]
	  ,[KOLICHESTVO]
      ,[TIP_DOGOVORA]
      ,[USLOVIYA_OPLATY]
      ,[SPOSOB_DOSTAVKI]
      ,[ADRES_DOSTAVKI]
      ,[SKLAD_OTGRUZKI]
      ,[SKLAD_OTGRUZKI_GUID]
      ,ADRES_SKLADA
      --,[TO_LONGITUDE]
      --,[TO_LATITUDE]
      --,[FROM_LONGITUDE]
      --,[FROM_LATITUDE]
  FROM [CRM_DWH].[dbo].[KOORDINATY_KONTRAGENTA]
  )A