WITH SPETSIFIKATSIYA
AS (
  SELECT 
     [NOMENKLATURA_GUID]
    ,SD.DOGOVOR_GUID
    ,[KOLICHESTVO]
  FROM [L1].[dbo].[SPETSIFIKATSIYA_PO_DOGOVORU] SD
    LEFT JOIN L1.dbo.NOMENKLATURA N
      ON N.GUID = SD.NOMENKLATURA_GUID
    LEFT JOIN L1.dbo.DOGOVORY_KONTRAGENTOV DK
    ON DK.GUID = SD.DOGOVOR_GUID
  WHERE 1=1
    AND N.RODITEL2 = 'Семена'
    AND DK.SEZON_GUID = 0xAF83D4F5EF10792511EBE2FB064EBC27
),
VYRUCHKA AS(
  SELECT 
     VYR.[NOMENKLATURA_GUID]
    ,DK.GUID AS DOGOVOR_GUID
    ,VYR.[KOLICHESTVO]
  FROM [L1].[dbo].[VYRUCHKA_I_SEBESTOIMOST_PRODAZH] VYR
    LEFT JOIN L1.dbo.NOMENKLATURA N
      ON N.GUID = VYR.NOMENKLATURA_GUID
    LEFT JOIN L1.dbo.DOGOVORY_KONTRAGENTOV DK
      ON DK.GUID = VYR.DOGOVOR_GUID
  WHERE 1=1
    AND N.RODITEL2 = 'Семена'
    AND DK.SEZON_GUID = 0xAF83D4F5EF10792511EBE2FB064EBC27
),
ZAKUP AS
(
  SELECT 
     SUM([TSENA])[TSENA]
    ,SUM([KOLICHESTVO]) [KOLICHESTVO]
    ,[NOMENKLATURA_GUID]
  FROM [L1].[dbo].[ZAKAZ_POSTAVSHIKU]ZP
    LEFT JOIN L1.DBO.NOMENKLATURA N 
      ON ZP.NOMENKLATURA_GUID=N.GUID
  WHERE 1=1
    AND N.RODITEL2 = 'Семена '
    AND DATA > '01-10-2021'
  GROUP BY [NOMENKLATURA_GUID]
),
STOCK AS
(SELECT * FROM 
  (SELECT 
     NOMENKLATURA_GUID
    ,N.NAIMENOVANIE
    ,SUM(case 
         when TNS.[VID_DVIZHENIYA]=1 
         then [v_nalichii]*(-1) 
         else [v_nalichii] 
       end) AS [v_nalichii]
    FROM [L1].[dbo].[tovary_na_skladakh] TNS
    LEFT JOIN L1.DBO.SKLADY S 
      ON TNS.SKLAD_GUID=S.GUID
    LEFT JOIN L1.DBO.NOMENKLATURA N 
    ON TNS.NOMENKLATURA_GUID=N.GUID
    WHERE N.RODITEL2='Семена '
    AND S.ADRES_SKLADA IS NOT NULL
    AND TNS.PERIOD<'01-10-2021'
    GROUP BY 
     [NOMENKLATURA_GUID]
    ,N.NAIMENOVANIE
  --ORDER BY [v_nalichii] DESC
  )A WHERE [v_nalichii]>0
),
MAIN AS
(
SELECT 
  n.GUID nomenklatura_guid
  ,sp.GUID as direksiya
   ,N.PROIZVODITELI AS 'Компании'
  ,N.VIDY_KULTUR_NOMENKLATURY AS 'Культура'
  ,isnull(SP.RODITEL2,isnull(SP.RODITEL,SP.NAIMENOVANIE)) as 'Регион'
  ,N.NAIMENOVANIE AS 'Название продукта'
  ,N.VIDY_TEKHNOLOGIY AS 'Технология'
  ,0 AS 'Подтверждение'
  ,SUM(S.KOLICHESTVO) AS 'Продано'
  ,case when (SUM(S.KOLICHESTVO)) is NOT null then 0 else SUM(V.KOLICHESTVO) end AS 'Отгружено'
  ,SUM(S.KOLICHESTVO) - case when (SUM(V.KOLICHESTVO)) is null then 0 else SUM(V.KOLICHESTVO) end AS 'Не отгружено'
  ,AVG(STOCK.v_nalichii) AS 'Стоки 2021'
  ,AVG(Z.KOLICHESTVO) AS 'Поступление'
FROM [L1].[dbo].[NOMENKLATURA] N
  LEFT JOIN SPETSIFIKATSIYA S
    ON S.NOMENKLATURA_GUID = N.GUID
  LEFT JOIN VYRUCHKA V
    ON V.NOMENKLATURA_GUID = N.GUID
    AND V.DOGOVOR_GUID = S.DOGOVOR_GUID
  LEFT JOIN L1.dbo.DOGOVORY_KONTRAGENTOV DK
    ON DK.GUID = S.DOGOVOR_GUID
  LEFT JOIN L1.dbo.STRUKTURA_PREDPRIYATIYA SP
    ON SP.GUID = DK.STRUKTURA_PREDPRIYATIYA_GUID
  LEFT JOIN ZAKUP Z
    ON Z.NOMENKLATURA_GUID = N.GUID
  LEFT JOIN STOCK 
    ON STOCK.NOMENKLATURA_GUID = N.GUID
WHERE 1=1
  AND N.RODITEL2 = 'Семена'
  AND N.VIDY_KULTUR_NOMENKLATURY IN ('Подсолнечник','Кукуруза','Рапс','Люцерна')
GROUP BY
  n.GUID 
  ,sp.GUID 
  ,N.PROIZVODITELI
  ,N.VIDY_KULTUR_NOMENKLATURY
  ,isnull(SP.RODITEL2,isnull(SP.RODITEL,SP.NAIMENOVANIE))
  ,N.NAIMENOVANIE
  ,N.VIDY_TEKHNOLOGIY
--ORDER BY 
--   N.PROIZVODITELI
--  ,N.VIDY_KULTUR_NOMENKLATURY
 -- N.NAIMENOVANIE
 --,direksiya
 --,N.VIDY_KULTUR_NOMENKLATURY
 )
 SELECT 
 nomenklatura_guid
 ,ISNULL(direksiya,0) AS direksiya
   ,M.Компании
  ,M.Культура
  ,M.[Название продукта]
  ,Регион
  ,M.Технология
  ,M.Подтверждение
  ,M.Продано
  ,M.Подтверждение - M.Продано AS 'Остаток'
  ,M.Отгружено
  ,M.[Не отгружено]
  ,M.[Стоки 2021]
  ,M.Поступление
--into CRM_DWH.dbo.SEMENA_TEST
 FROM MAIN M

 order by M.[Название продукта]