/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT [ssylka] AS GUID
      --,[pometka_udaleniya]
      ,DATEADD(YEAR,-2000,[data]) AS [DATA]
      --,[nomer]
      --,[proveden]
      ,[DOGOVOR] AS [DOGOVOR_GUID] 
      ,[DIREKTSIYA] AS [DIREKTSIYA_GUID]
      ,[KONTRAGENT] AS [KONTRAGENT_GUID]
      ,[MENEDZHER] AS [MENEDZHER_GUID]
      --,[protsent_predoplaty]
      --,[vse_usloviya_soblyudeny]
      --,[kolichestvo_vypolneno_uspeshno]
      --,[kolichestvo_uslovie_proydeno]
      --,[polucheny_vse_proveryaemye_znacheniya]
      --,[avtor]
      --,[eto_chastnoe_litso]
      --,[eto_k_kh]
      --,[tip_kontragenta_fiz_litso]
      --,[tekushchiy_kreditnyy_limit]
      --,[summa_zadolzhennosti]
      --,[postoplata]
      --,[sebestoimost_po_vsem_strokam]
      --,[srednyaya_marzhinalnosti_po_tovaram]
      --,[summa]
      --,[summa_po_prays_listu]
      --,[summa_sebestoimost]
      --,[summa_skidki]
      --,[rasschitany_vse_sroki_postavki]
      --,[tovary_v_ramkakh_srokov_postavki]
      --,[rukovoditel]
      --,[predydushchiy_analiz]
      ,[marzhinalnost] AS [MARZHINALNOST]
--INTO [L1].[DBO].[ANALIZ_DOGOVORA]
  FROM [L0].[dbo].[analiz_dogovora]