/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT [PERIOD]
      ,[SCHET]
      ,[ORGANIZACIYA_GUID]
      ,[VALYUTA]
      ,[SALDO_NA_NACHALO_PERIODA_V_VALYUTE]
      ,[SALDO_NA_NACHALO_PERIODA]
      ,[OBOROTY_ZA_PERIOD_DT]
      ,[OBOROTY_ZA_PERIOD_KT]
      ,[OBOROTY_ZA_PERIOD_DT_V_VALYUTE]
      ,[OBOROTY_ZA_PERIOD_KT_V_VALYUTE]
      ,[SALDO_NA_KONEC_PERIODA_V_VALYUTE]
      ,[SALDO_NA_KONEC_PERIODA]
	  --INTO L1.[dbo].[ITOGI_PO_SCHETAM_HOZRASCHETNYJ]
  FROM [L0].[dbo].[itogi_po_schetam_hozraschetnyj]