SELECT [proizvoditel]
      ,[1_prioritet]
      ,[2_prioritet]
      ,[3_prioritet]
      ,[4_prioritet]
      ,[5_prioritet]
      ,[6_prioritet]
      ,[7_prioritet]
  FROM [L0].[dbo].[matritsa_po_proizvoditelyam_zakup]