SELECT  dateadd(year,-2000,[period])[period]
      ,[synonym_registrator]
	  ,dogovor.ssylka as dogovor_guid
      ,[type_registrator]
      ,[registrator]
      ,[nomer_stroki]
      ,[aktivnost]
      ,[analitika_ucheta_po_partneram]
      ,[synonym_zakaz_klienta]
      ,[type_zakaz_klienta]
      ,rsk.[zakaz_klienta]
      ,[valyuta]
      ,rsk.[summa]
      ,[k_oplate]
      ,[oplachivaetsya]
      ,[k_otgruzke]
      ,[otgruzhaetsya]
      ,rsk.[khozyaystvennaya_operatsiya]
      ,rsk.[forma_oplaty]
      ,[schet_na_oplatu]
      ,[synonym_prodazha_po_zakazu]
      ,[type_prodazha_po_zakazu]
      ,[prodazha_po_zakazu]
      ,dateadd(year,-2000,[data_registratora])[data_registratora]
      ,dateadd(year,-2000,[data_platezha])[data_platezha]
      ,[summa_regl]
      ,[summa_upr]
      ,[isklyuchat_pri_kontrole]
      ,rsk.[dopustimaya_summa_zadolzhennosti]
      ,[zalog_za_taru]
      ,rsk.[statya_dvizheniya_denezhnykh_sredstv]
      ,[synonym_raschetnyy_dokument]
      ,[type_raschetnyy_dokument]
      ,[raschetnyy_dokument]
  FROM [L0].[dbo].[raschety_s_klientami] rsk
  	 LEFT JOIN [L0].dbo.klyuchi_analitiki_ucheta_po_partneram AS analitika ON rsk.analitika_ucheta_po_partneram = analitika.ssylka 
	 LEFT JOIN [L0].dbo.dogovory_kontragentov AS dogovor ON analitika.dogovor = dogovor.ssylka