/****** СКРИПТ ДЛЯ КОМАНДЫ SELECTTOPNROWS ИЗ СРЕДЫ SSMS  ******/
SELECT DATEADD(YEAR, -2000,[PERIOD]) AS [PERIOD]
      ,[SYNONYM_REGISTRATOR]
      ,[ZAKAZ_POSTAVSHCHIKU] AS [ZAKAZ_POSTAVSHCHIKU_GUID]
      ,[VALYUTA] AS [VALYUTA_GUID]
      ,[KHOZYAISTVENNAYA_OPERACIYA] AS [KHOZYAISTVENNAYA_OPERACIYA_GUID]
      ,[STATYA_DVIZHENIYA_DENEZHNIKH_SREDSTV] AS [STATYA_DVIZHENIYA_DENEZHNIKH_SREDSTV_GUID]
	  ,DOGOVOR.SSYLKA AS DOGOVOR_GUID
	  ,ANALITIKA.KONTRAGENT AS KONTRAGENT_GUID
	  ,SUM(CASE WHEN [VID_DVIZHENIYA]=0 THEN ((DOLG_REGL + PREDOPLATA_REGL)*(-1)) ELSE (DOLG_REGL + PREDOPLATA_REGL) END) AS SUMMA_KZT
	  ,SUM(CASE WHEN [VID_DVIZHENIYA]=0 THEN ([PREDOPLATA]*(-1)) ELSE [PREDOPLATA] END ) AS SUMMA_VALUTA
	  ,valyuty.naimenovanie AS [VALYUTA_NAIMENOVANIE]
--INTO [L1].[DBO].[RASCHETY_S_POSTAVSHCHIKAMI_PO_DOKUMENTAM] 

  FROM [L0].[DBO].[RASCHETI_S_POSTAVSHCHIKAMI_PO_DOKUMENTAM] AS RSPD
LEFT JOIN [L0].DBO.KLYUCHI_ANALITIKI_UCHETA_PO_PARTNERAM AS ANALITIKA 
	ON RSPD.ANALITIKA_UCHETA_PO_PARTNERAM = ANALITIKA.SSYLKA 
LEFT JOIN [L0].DBO.DOGOVORY_KONTRAGENTOV AS DOGOVOR 
	ON ANALITIKA.DOGOVOR = DOGOVOR.SSYLKA
LEFT JOIN L0.dbo.valyuty
	ON valyuta=valyuty.ssylka

	 GROUP BY [PERIOD]
      ,[SYNONYM_REGISTRATOR]
      ,[ZAKAZ_POSTAVSHCHIKU]
      ,[VALYUTA]
      ,[UDALIT_DATA_PLATEZHA]
      ,[KHOZYAISTVENNAYA_OPERACIYA]
      ,[STATYA_DVIZHENIYA_DENEZHNIKH_SREDSTV]
	  ,DOGOVOR.SSYLKA
	  ,ANALITIKA.KONTRAGENT
	  ,valyuty.naimenovanie
	 ORDER BY valyuty.naimenovanie,PERIOD