/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT DISTINCT SP1.[DateInserted],ID,SP1.[productCode],SP1.[product]
--INTO [L1_X].[dbo].[DUPLICATE_SUBSIDIES_PARSER]
FROM [L1_X].[dbo].[SUBSIDIES_PARSER] SP1
INNER JOIN (
SELECT [DateInserted]
      ,[region]
      ,[appDate]
      ,[applicant]
      ,[provider]
      ,[applicantIn]
      ,[providerIn]
      ,[product]
      ,[volume]
      ,[unit]
      ,[usageArea]
      ,[status]
      ,[appType]
      ,[appAcceptanceDate]
      ,[appRejectionDate]
      ,[subsidies]
      ,[rejectionReason]
      ,[noteOnNegativeResolution]
      ,[group]
      ,[year]
      ,[applicantID]
      ,[isAA]
      ,[isSubsAaClient]
      ,[catoCode]
	  --,[productCode]
      ,count(*)[productCode]
  FROM [L1_X].[dbo].[SUBSIDIES_PARSER]

  GROUP BY [DateInserted]
      ,[region]
      ,[appDate]
      ,[applicant]
      ,[provider]
      ,[applicantIn]
      ,[providerIn]
      ,[product]
      ,[volume]
      ,[unit]
      ,[usageArea]
      ,[status]
      ,[appType]
      ,[appAcceptanceDate]
      ,[appRejectionDate]
      ,[subsidies]
      ,[rejectionReason]
      ,[noteOnNegativeResolution]
      ,[group]
      ,[year]
      ,[applicantID]
      ,[isAA]
      ,[isSubsAaClient]
      ,[catoCode]
	  --,[productCode]
	  HAVING COUNT(*)>1
	  )SP2
ON SP1.[DateInserted]=SP2.[DateInserted]

ORDER BY SP1.[DateInserted]