
CREATE VIEW SVOBODNI_OSTATOK AS 

WITH SPEKA AS 
(
SELECT SPD.[DOGOVOR_GUID] AS [DOGOVOR_GUID]
      ,[PERIOD]
      ,SPD.[NOMENKLATURA_GUID] AS [NOMENKLATURA_GUID]
      ,SPD.[KOLICHESTVO]
	  --,VISP.KOLICHESTVO AS OTGRUZKA
   --   ,SPD.[KOLICHESTVO]-VISP.KOLICHESTVO AS OSTALOS
      ,SPD.[SUMMA]
      ,[DATA_OTGRUZKI]
      ,[SKLAD_OTGRUZKI_GUID] AS [SKLAD_OTGRUZKI_GUID]
      ,[SKLAD_OTGRUZKI]
      ,SPD.[SUMMA_KZ_TG]
	 , S.NAIMENOVANIE
	 ,SKL.BIZNES_REGION_GUID
  FROM [L1].[dbo].[SPETSIFIKATSIYA_PO_DOGOVORU] AS SPD
  LEFT JOIN L1.DBO.DOGOVORY_KONTRAGENTOV AS DK
	ON SPD.DOGOVOR_GUID=DK.GUID
LEFT JOIN L1.DBO.SEZONY S
	ON DK.SEZON_GUID=S.GUID
LEFT JOIN L1.DBO.ORGANIZATSII AS O
	ON DK.ORGANIZATSIYA_GUID=O.GUID
INNER JOIN L1.DBO.SKLADY AS SKL
	ON SPD.SKLAD_OTGRUZKI_GUID=SKL.GUID
WHERE 1=1
  AND S.NAIMENOVANIE = 'Сезон 2023'
	AND DK.STATUS='Действует'
	AND DK.TIP_DOGOVORA='С покупателем / заказчиком'
	AND O.NAIMENOVANIE=N'ТОО «Alem Agro Holding (АлемАгро Холдинг)»'

	--ORDER BY SPD.DOGOVOR_GUID
	--,SPD.NOMENKLATURA_GUID
)

, VIRUCHKA AS 
(
SELECT [DATE]
      ,[DOGOVOR_GUID]
      ,VISP.[KONTRAGENT_GUID] AS [KONTRAGENT_GUID]
      ,VISP.[MENEDZHER_GUID] AS [MENEDZHER_GUID]
      ,[NOMENKLATURA_GUID] AS [NOMENKLATURA_GUID]
      ,VISP.[ORGANIZATSIYA_GUID] AS [ORGANIZATSIYA_GUID]
      ,VISP.[SKLAD_GUID] AS [SKLAD_GUID]
      ,[KOLICHESTVO]
      ,[STOIMOST]
      ,[STOIMOST_BEZ_NDS]
      ,[SUMMA_VYRUCHKI]
      ,[SUMMA_VYRUCHKI_BEZ_NDS]
      ,VISP.[VALYUTA_VZAIMORASCHETOV] AS [VALYUTA_VZAIMORASCHETOV]
	  ,SKL.BIZNES_REGION_GUID
  FROM [L1].[dbo].[VYRUCHKA_I_SEBESTOIMOST_PRODAZH] AS VISP
  LEFT JOIN L1.DBO.DOGOVORY_KONTRAGENTOV AS DK
	ON VISP.DOGOVOR_GUID=DK.GUID
LEFT JOIN L1.DBO.SEZONY S
	ON DK.SEZON_GUID=S.GUID
LEFT JOIN L1.DBO.ORGANIZATSII AS O
	ON DK.ORGANIZATSIYA_GUID=O.GUID
INNER JOIN L1.DBO.SKLADY AS SKL
	ON VISP.SKLAD_GUID=SKL.GUID
WHERE 1=1
  AND S.NAIMENOVANIE = 'Сезон 2023'
	AND DK.STATUS='Действует'
	AND DK.TIP_DOGOVORA='С покупателем / заказчиком'
	AND O.NAIMENOVANIE=N'ТОО «Alem Agro Holding (АлемАгро Холдинг)»'
  --ORDER BY DATE
)

, SKLADY AS 
(
SELECT S.[GUID] AS [GUID]
      ,S.[RODITEL]
      ,S.[NAIMENOVANIE]
      ,[PODRAZDELENIE_GUID]
      ,[BIZNES_REGION_GUID] AS [BIZNES_REGION_GUID]
	  ,BR.NAIMENOVANIE  AS [BIZNES_REGION]
      ,[ORGANIZATSIYA_GUID]
      ,[ADRES_SKLADA]
      ,[SOURCE_BASE]
  FROM [L1].[dbo].[SKLADY] S
  LEFT JOIN L1.DBO.BIZNES_REGIONY BR
	ON S.BIZNES_REGION_GUID=BR.GUID
  WHERE 1=1
  and S.NAIMENOVANIE not in (
	'A Trade  - Шымкент склад ',
'Материалы Центральный склад' ,
'AA Trade - Алматы склад',
'Alem Astyk Export',
'AA KG - Бишкек склад', 
'Agro Smart Logistics (Склад ответхранения)',
'Материалы СКО общее',
'ОФПСХ (Склад ответхранения)',
'Материалы Акмолинская область общее' )
)
,OSTATOK AS 
(
SELECT 
	   a.NOMENKLATURA_GUID AS NOMENKLATURA_GUID
	  ,sk.GUID AS sklad_guid
	  ,CAST(sum(a.KOLICHESTVO) AS NUMERIC(15,2)) AS OSTALOS_STOK
	  ,BR.GUID AS BIZNES_REGION_GUID
	  ,BR.NAIMENOVANIE AS BIZNES_REGION
	  --,dateadd(WEEK,(a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI/7)+datepart(week,getdate()),'25/12/2022')  AS date
	  --,CAST((a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI/7)+datepart(week,getdate()) AS INT) AS week
	  --,CAST(datepart(week,GETDATE()) AS INT ) AS week
---INTO #STOKKOI
FROM [L1].[dbo].[TOVARY_NA_SKLADAKH_OSTATKI_PO_SROKAM_GODNOSTI] a
	left join [L1].[dbo].[NOMENKLATURA] s 
	on s.GUID=a.NOMENKLATURA_GUID
	left join L1.dbo.SKLADY sk
	on a.SKLAD_GUID=sk.GUID
	LEFT JOIN L1.dbo.BIZNES_REGIONY AS BR
	ON SK.BIZNES_REGION_GUID=BR.GUID

where 1=1
	and a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI!=0
	--and a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI>90
	and s.KATEGORII_NOMENKLATURY_GROUP in  ('СЗР ','Семена ','Удобрения')
	and sk.NAIMENOVANIE not in (
	'A Trade  - Шымкент склад ',
'Материалы Центральный склад' ,
'AA Trade - Алматы склад',
'Alem Astyk Export',
'AA KG - Бишкек склад', 
'Agro Smart Logistics (Склад ответхранения)',
'Материалы СКО общее',
'ОФПСХ (Склад ответхранения)',
'Материалы Акмолинская область общее' )

--AND NOMENKLATURA_GUID=@NAME_NOMENKLATUR
group by a.NOMENKLATURA_GUID
	    --,sk.NAIMENOVANIE
		,BR.GUID
		,sk.GUID,CONVERT(NVARCHAR(50),BR.GUID,1)
	  ,BR.NAIMENOVANIE
		--,dateadd(WEEK,(a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI/7)+datepart(week,getdate()),'25/12/2022')
		--,(a.DNEY_DO_ISTECHENIYA_SROKA_GODNOSTI/7)+datepart(week,getdate())

)
,SPRAVKA AS (
SELECT 
	S.GUID AS SKLAD_GUID
	,s.BIZNES_REGION_GUID
	,NULL AS NOMENKLATURA_GUID
FROM SKLADY AS S 

UNION

SELECT 
SPEKA.SKLAD_OTGRUZKI_GUID AS SKLAD_GUID
,SPEKA.BIZNES_REGION_GUID AS BIZNES_REGION_GUID
,SPEKA.NOMENKLATURA_GUID AS NOMENKLATURA_GUID
FROM SPEKA

UNION 

SELECT 
VIR.SKLAD_GUID
,VIR.BIZNES_REGION_GUID AS BIZNES_REGION_GUID
,NOMENKLATURA_GUID AS NOMENKLATURA_GUID
FROM VIRUCHKA AS VIR 

UNION 

SELECT 
OSTATOK.sklad_guid  AS SKLAD_GUID
,OSTATOK.BIZNES_REGION_GUID AS BIZNES_REGION_GUID
,OSTATOK.NOMENKLATURA_GUID AS NOMENKLATURA_GUID
FROM OSTATOK
)


SELECT 
SKLADY.NAIMENOVANIE AS SKLADY
,SKLADY.BIZNES_REGION
,NOMEN.NAIMENOVANIE AS NOMENKLATURA
,SUM(SPEKA.KOLICHESTVO) AS KOLICHESTVO_ZAKLUCHENO

,SUM(VIRUCHKA.KOLICHESTVO) AS KOLICHESTVO_OTGRUZKI

,SUM(SPEKA.KOLICHESTVO)-SUM(VIRUCHKA.KOLICHESTVO) AS OSTALOS_OTGRUZIT
,SUM(OSTATOK.OSTALOS_STOK) AS STOK 
,SUM(OSTATOK.OSTALOS_STOK) - (CASE WHEN (SUM(SPEKA.KOLICHESTVO)-SUM(VIRUCHKA.KOLICHESTVO))<0 THEN (SUM(SPEKA.KOLICHESTVO)-SUM(VIRUCHKA.KOLICHESTVO))*(-1) 
									ELSE (SUM(SPEKA.KOLICHESTVO)-SUM(VIRUCHKA.KOLICHESTVO)) END 
								) AS SVOBODNI_OSTATOK
,SPRAVKA.SKLAD_GUID
,SPRAVKA.BIZNES_REGION_GUID
,SPRAVKA.NOMENKLATURA_GUID

FROM SPRAVKA
LEFT JOIN SPEKA
	ON SPRAVKA.NOMENKLATURA_GUID=SPEKA.NOMENKLATURA_GUID
	AND SPRAVKA.SKLAD_GUID=SPEKA.SKLAD_OTGRUZKI_GUID
LEFT JOIN VIRUCHKA
	ON SPRAVKA.NOMENKLATURA_GUID=VIRUCHKA.NOMENKLATURA_GUID
	AND SPRAVKA.SKLAD_GUID=VIRUCHKA.SKLAD_GUID
LEFT JOIN OSTATOK
	ON SPRAVKA.NOMENKLATURA_GUID=OSTATOK.NOMENKLATURA_GUID
	AND SPRAVKA.SKLAD_GUID=OSTATOK.sklad_guid
LEFT JOIN SKLADY
	ON SPRAVKA.SKLAD_GUID=SKLADY.GUID
LEFT JOIN L1.DBO.NOMENKLATURA AS NOMEN
	ON SPRAVKA.NOMENKLATURA_GUID=NOMEN.GUID

GROUP BY 
SPRAVKA.SKLAD_GUID
,SPRAVKA.BIZNES_REGION_GUID
,SPRAVKA.NOMENKLATURA_GUID
,SKLADY.NAIMENOVANIE
,SKLADY.BIZNES_REGION
,NOMEN.NAIMENOVANIE 

--ORDER BY SKLADY.NAIMENOVANIE 