
CREATE TABLE [L1].[DBO].[MATRITSA_PO_MENEDZHERAM](
	[MENEDZHER_GUID] [BINARY](16) NULL,
	[DIREKTSIYA] [NVARCHAR](20) NULL,
	[1_PRIORITET] [BINARY](16) NULL,
	[2_PRIORITET] [BINARY](16) NULL
) ON [PRIMARY]



