USE [L1]
GO

/****** Object:  Table [dbo].[sklady_po_ostatkam]    Script Date: 11.01.2022 17:31:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [DBO].[SKLADY_PO_OSTATKAM](
	[SKLAD_ZAKUPA] [NVARCHAR](50) NULL,
	[SKLAD] [NVARCHAR](50) NULL,
	[PRIORITET] [NVARCHAR](5) NULL,
	[PRIORITET_PARENT] [NVARCHAR](5) NULL
) ON [PRIMARY]
GO


